### ISSUE TITLE
Activation-based FEM network validation

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1002]
The Forward/Inverse toolkit network activation-based-fem needs validation.

**Comment by aylakhan** [comment]
Emphasis should be on BuildFEMatrix -> ... -> SolveLinearSystem pipeline in the network.

**Comment by aylakhan** [comment]
FYI toolkit networks have been moved to the [FwdInvToolkit] repo (https://github.com/SCIInstitute/FwdInvToolkit) (see #925).

**Comment by aylakhan** [comment]
@jessdtate - status?

**Comment by jessdtate** [comment]
this network hasn't had any developements, mainly because the functionality that the network is trying to acheive isn't really supported in SCIRun.  We are waiting on a collaborator that can help us with that.

**Comment by jessdtate** [comment]
the buildFEMatrix and solvelinearsystems are working.

**Comment by aylakhan** [comment]
@jessdtate - can you close this issue then?

**Comment by jessdtate** [comment]
You can close it.  I don't have such permissions.
