### ISSUE TITLE
Forward problem network validation

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1004]
The Forward/Inverse toolkit network forward_problem needs validation.

**Comment by aylakhan** [comment]
Emphasis should be on BuildFEMatrix -> AddKnownsToLinearSystem -> SolveLinearSystem pipeline in the network.

**Comment by aylakhan** [comment]
FYI toolkit networks have been moved to the [FwdInvToolkit] repo (https://github.com/SCIInstitute/FwdInvToolkit) (see #925).

**Comment by aylakhan** [comment]
Any updates, or can we close this issue?

**Comment by jessdtate** [comment]
The tests that Brianna and I did showed that the pipeline was identical to SCIRun4.  We only tested one or two cases.   Let me double check this in the next few days and see if I can/should do another couple examples.

**Comment by jessdtate** [comment]
Yes, I'm running some comparisons with the two methods.  there are some differences, but I'm not sure the source of the differences.

**Comment by aylakhan** [comment]
Can you write up a brief description of the differences you're seeing?

**Comment by jessdtate** [comment]
I can.  I need to do a little more testing first.

**Comment by jessdtate** [comment]
There are some differences in forward solutions with BEM and FEM in the same geometries.  Both solutions look accurate, but are different enough to cause worry.  I check both against the analytical solution of the concentric spheres.  FEM is showing similar solutions to the analytical solutions, but BEM is not.  There is some matlab code that is testing better on analytical solution, so I will compare FEM to that code with some other examples.
see #1005

**Comment by dcwhite** [comment]
Could you make simplified test networks that compute solutions for the concentric sphere case for both FEM and BEM? Make them small enough geometries that we can quickly compare the entire output matrices.

**Comment by jessdtate** [comment]
There are some networks in /home/sci/jess/SCIRun_5_nets/forward_problem_spheres on the server.  To run the FEM one, mash play on the getMatrixSlice (without executing before).  Or use the FEM_sphere_test.srn5 for a single time point.

**Comment by dcwhite** [comment]
@jessdtate @zaracay Are there still numerical diffs? Is this one ready to close?

**Comment by zaracay** [comment]
Based on simulations using torso/heart based FEM and BEM comparison, the differences appear to be minimal.  We should compare them to the analytical solutions again before closing this down though.

**Comment by dcwhite** [comment]
@jessdtate wants to close this issue. Any objections @zaracay?
