### ISSUE TITLE
ShowField: enable transparency in faces makes the faces disappear

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1008]
Tried plotting a heart surface geometry (faces determined by triangles).

Enabled transparency in show field an the heart disappeared. If I ask to show nodes or edges those work fine.

**Comment by dcwhite** [comment]
Was the transparency alpha set to 0?

**Comment by jcollfont** [comment]
I tried changing the alpha level and didn't make any difference. (while it was working fine for the edges)

**Comment by dcwhite** [comment]
@jessdtate Interns can probably close this one too.
