### ISSUE TITLE
ShowField: enable amount of transparency does not seem to do anything without enabling/disabling transparency again

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1009]
Working with a triangular surface mesh:

When working with edges only, enable transparency works fine (opposite to faces).
However, when selecting the amount of transparency to be used (in the 0-1 box right next to it) the plot does not change. However if I disable transparency and enable again, the shading changed accordingly to the selected amount.

**Comment by dcwhite** [comment]
That spin box does not trigger auto-execute, only the checkboxes do that. We can try hooking up auto-execute if you want.

**Comment by dcwhite** [comment]
You can re-execute quickly by right-clicking on the module UI and clicking execute.

**Comment by jessdtate** [comment]
We can probably use the course to test this set up and see which way would be better.  I prefer it to not auto-execute.

**Comment by dcwhite** [comment]
Change transparency widget to slider to enable easier re-execution.

**Comment by dcwhite** [comment]
@jessdtate Interns need to verify this can be closed.

**Comment by dcwhite** [comment]
ShowField is getting some updated controls. Closing this as a result.
