### ISSUE TITLE
ShowField: fails to show a field with data

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1010]
Using a surface triangular mesh with 502 nodes.
I am using SetFieldData with a vector of 502 entries. The module does not complain (if I change the input size does, so that's OK).

Then I try to plot the field using ShowField and ViewScene and the geometry does not appear in the render. In the other hand, if I directly input the geometry, it does show.

Using reportFieldInfo, it indicates that the geometry has data on it and with the same range of values as the input data.

**Comment by dcwhite** [comment]
Can you provide a test network with data?

**Comment by jessdtate** [comment]
I don't know how consistent this is, but these kind of bugs should be high priority for the course.

**Comment by dcwhite** [comment]
We saw this again in the lunch yesterday--it had to do with the scale of the mesh, which was ~1e9. How big is your mesh here?

**Comment by jessdtate** [comment]
I remember seeing something similar to this.  It wasn't the size of the mesh, but something to do with the colormap.  I haven't seen these issues in a while.

**Comment by dcwhite** [comment]
@jcollfont @jessdtate Let's discuss at tomorrow's toolkit meeting!

**Comment by jessdtate** [comment]
@jcollfont any data for this?

**Comment by jessdtate** [comment]
possibly related to #1539?  closing unless we get more data
