### ISSUE TITLE
BEM Output does not match SCIRun4.7

### ISSUE THREAD

**Issue by brikindall** [SCIInstitute/SCIRun#1018]
I worked with @jessdtate on the torso-tank-ben example net using the cage data and the UCLA heart data. The output of the BuildBEMatrix module has a different minimum and maximum value than the output min/max of the same module in SCIRun 4.7 despite using the same input data.

**Comment by aylakhan** [comment]
Related to #1005.

**Comment by dcwhite** [comment]
@jessdtate @brikindall @aylakhan @buuuurak I found a bug in the SCIRun 4 BuildBE code, after fixing that the matrices match up (at least from a min/max point-of-view). 

When calculating the deflation constant for the EE matrix, integer division was used so the deflation constant value was always zero, thus deflation did nothing. During conversion I rewrote that section a little bit, and wound up with the correct float division, viz.:
```
// v4 code, incorrect AFAIK: (BuildBEMatrix.cc line 413 or so)
// Perform deflation on EE matrix
  double deflationconstant = 1/((EE.to_dense())->ncols()); // 1/(# cols of EE)
//-----
//v5 code, should be correct:
// Perform deflation on EE matrix
  const double deflationconstant = 1.0/EE.matrix().ncols();
```

**Comment by jessdtate** [comment]
I will do some testing, but sounds like this is resolved.

**Comment by dcwhite** [comment]
@jessdtate Let me know if I can close this one.

**Comment by jessdtate** [comment]
I did some more testing.  everything is working fine.  You can probably close this.
