### ISSUE TITLE
Tikhonov-inverse network validation.

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1025]
The Forward/Inverse toolkit network tikhonov-inverse needs validation. Emphasis should be on the output of the tikhonov module.

**Comment by aylakhan** [comment]
FYI toolkit networks have been moved to the [FwdInvToolkit] repo (https://github.com/SCIInstitute/FwdInvToolkit) (see #925).

**Comment by dcwhite** [comment]
@jcollfont discovered the output is null. I should probably fix that first, assigning back to me.

**Comment by dcwhite** [comment]
The tests I have validate the output compared to v4. We need to bolster the test coverage before major refactoring is attempted. Assigning this one to @jcollfont--we need more test networks.

**Comment by dcwhite** [comment]
Any updates on this issue? In addition to unit tests it would be nice to have more test networks with small input data, testing over/under/etc.

**Comment by jcollfont** [comment]
Have implemented tests for the sizes of the input variables.

Still missing tests on the functionality, but can't figure out how to properly use the testing macro EXPECT_MATRIX_EQ
