### ISSUE TITLE
SCIRun does not run when I execute

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1028]
updated to the most recent version of SCIRun in the master branch.
Compiled with no errors and now it does not execute (using "make -j4" in bin/).
I am not sure if I am doing something wrong or it is a problem with my system.

Here's my terminal output:
Jaumes-MacBook-Pro:bin jaume$ pwd
/Users/jaume/Documents/Research/SCIRun5/bin

Jaumes-MacBook-Pro:bin jaume$ ./SCIRun.app/Contents/MacOS/SCIRun 
dyld: Symbol not found: __ZN6SCIRun8Dataflow8Networks6Module14executionStateEv
  Referenced from: /Users/jaume/Documents/Research/SCIRun5/bin/./SCIRun.app/Contents/MacOS/../Frameworks/libModules_Legacy_MatlabInterface.dylib
  Expected in: /Users/jaume/Documents/Research/SCIRun5/bin/./SCIRun.app/Contents/MacOS/../Frameworks/libDataflow_Network.dylib
 in /Users/jaume/Documents/Research/SCIRun5/bin/./SCIRun.app/Contents/MacOS/../Frameworks/libModules_Legacy_MatlabInterface.dylib
Trace/BPT trap: 5

**Comment by dcwhite** [comment]
The app bundle does not get rebuilt properly, it's calling out-of-date dependencies. Try running ./SCIRun_test. To run via the bundle, you have to blow it away before rebuilding.
