### ISSUE TITLE
glyphs on unstructured surface meshes and point clouds

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1030]
ShowFieldGlyphs will not display any glyphs if the vector data is located on an unstructured surface mesh or point cloud.  Tet and hex meshes (regular and unstuctured) appear to work normally.  This could be an issue with tri surfaces and point cloud, but I also have problems with quad surfaces when data is on the faces.  The glyphs do not show up in these cases.  I will send some fields to test.

**Comment by jessdtate** [comment]
I mostly care about visualizing a single vector, as we will be using that in the IBBM course, so this is moderately  Important.

**Comment by cbrightsci** [comment]
@jessdtate Can you test out branch glyphs_unstructred_surfaces to see if things render correctly now?
