### ISSUE TITLE
Menu scroll on ViewScene

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1041]
The side arrow which allows the user to see configure/ views does not work. The user must completely expand the window to access these features.

**Comment by dcwhite** [comment]
ViewScene should have a minimum size that show all toolbar buttons. Or start moving widgets into the config window.

**Comment by jessdtate** [comment]
I would like this working for the class in some form.  There are some work arounds (making the objects smaller so they all fit ) or adding more to the config window.  It will be confusing to the students as is I think.
