### ISSUE TITLE
TDCS_TOY_EXAMPLE.srn5 Crash

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1043]
I loaded the TDCS_TOY_EXAMPLE network, which had some lag in loading but this is a known behavior. I then ran the network without any data and it had the error messages pop up. I tried to click OK on the error messages and it crashed.

**Comment by allywarner** [comment]
When I load the TMS_TOY_EXAMPLE network and run it with no data, the error messages pop up and when I initially press OK there is a lag (I get the wheel on my mac). After that, I'm able to click OK on all the error messages.

**Comment by dcwhite** [comment]
There are general GUI lag issues with large networks. More developer testing is required.

**Comment by dcwhite** [comment]
Duplicate
