### ISSUE TITLE
Moving Error Messages

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1045]
I would like to be able to move an error message after it's popped up. Pinning them by clicking on them could also be nice.

**Comment by dcwhite** [comment]
* Error items are movable
* Double-click to pin/unpin. When pinned, a box appears around the item, the text is bolded, and you can't move it. 

Same:
* Left-click to show errored module
* Right-click to remove (whether pinned or unpinned)

**Comment by allywarner** [comment]
Can we move several error messages or all error messages together or only one at a time?

**Comment by dcwhite** [comment]
Only one at a time now. Make a new issue for "move multiple error items"
