### ISSUE TITLE
Get Tensors to work in ShowFieldGlyphs

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#1047]

**Comment by jessdtate** [comment]
Unless it is close, it should be ok to push for after IBBM.

**Comment by ajanson** [comment]
What is the status of this? We talked about this briefly last week so I just wanted to add a comment. Also, can I add a request to get "Normalize before scaling" as well.

**Comment by dcwhite** [comment]
We haven't looked at SFG in a while. We're going through the backlog at a meeting tomorrow. If you want it in the next couple months, we can try to prioritize it.
