### ISSUE TITLE
CrashReport - Isosurface output drag connection to ShowField

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1059]
I had run an isosurface on a segmentation file, which completed.  I then placed a ShowField and tried to drag the output of Isosurface to the ShowField.  The pipe never connected, a pinwheel of death appeared, SCIRun crashed and the following report was made

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000030

VM Regions Near 0x30:
--> 
    __TEXT                 0000000108bdb000-0000000108bf6000 [  108K] r-x/rwx SM=COW  /Users/USER/Documents/*/SCIRun.app/Contents/MacOS/SCIRun

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libInterface_Application.dylib	0x0000000108c83ece SCIRun::Gui::PortWidget::performDrag(QPointF const&) + 334
1   libInterface_Application.dylib	0x0000000108c83d69 SCIRun::Gui::PortWidget::doMouseMove(QFlags<Qt::MouseButton>, QPointF const&) + 121
2   libInterface_Application.dylib	0x0000000108c4da0a SCIRun::Gui::ModuleProxyWidget::mouseMoveEvent(QGraphicsSceneMouseEvent*) + 122
3   QtGui                         	0x000000010dc226e2 QGraphicsItem::sceneEvent(QEvent*) + 1234
4   QtGui                         	0x000000010dc77d9d QGraphicsWidget::sceneEvent(QEvent*) + 13
5   QtGui                         	0x000000010dc40a21 QGraphicsScene::setFocus(Qt::FocusReason) + 2241
6   QtGui                         	0x000000010dc413d4 QGraphicsScene::keyPressEvent(QKeyEvent*) + 1300
7   QtGui                         	0x000000010dc44d88 QGraphicsScene::mouseMoveEvent(QGraphicsSceneMouseEvent*) + 88
8   QtGui                         	0x000000010dc5a16b QGraphicsScene::event(QEvent*) + 1419
9   QtGui                         	0x000000010d64e5ed QApplicationPrivate::notify_helper(QObject*, QEvent*) + 189
10  QtGui                         	0x000000010d654c64 QApplication::notify(QObject*, QEvent*) + 1060
11  QtCore                        	0x000000010e488bdc QCoreApplication::notifyInternal(QObject*, QEvent*) + 124
12  QtGui                         	0x000000010d64e89c QApplication::topLevelWidgets() + 492
13  QtGui                         	0x000000010dc6c7ff QGraphicsViewPrivate::mouseMoveEventHandler(QMouseEvent*) + 1119
14  QtGui                         	0x000000010dc75f38 QGraphicsView::mouseMoveEvent(QMouseEvent*) + 72
15  libInterface_Application.dylib	0x0000000108caa66d SCIRun::Gui::NetworkEditor::mouseMoveEvent(QMouseEvent*) + 381
16  QtGui                         	0x000000010d6a949b QWidget::event(QEvent*) + 2475
17  QtGui                         	0x000000010da3b0ac QFrame::event(QEvent*) + 44
18  QtGui                         	0x000000010dac76e7 QAbstractScrollArea::viewportEvent(QEvent*) + 23
19  QtGui                         	0x000000010dc7350b QGraphicsView::viewportEvent(QEvent*) + 123
20  QtGui                         	0x000000010dac9a70 QAbstractScrollArea::qt_metacall(QMetaObject::Call, int, void**) + 336
21  QtCore                        	0x000000010e488687 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 151
22  QtGui                         	0x000000010d64e5be QApplicationPrivate::notify_helper(QObject*, QEvent*) + 142
23  QtGui                         	0x000000010d655190 QApplication::notify(QObject*, QEvent*) + 2384
24  QtCore                        	0x000000010e488bdc QCoreApplication::notifyInternal(QObject*, QEvent*) + 124
25  QtGui                         	0x000000010d652bdd QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) + 333
26  QtGui                         	0x000000010d6026cb QMacCocoaAutoReleasePool::~QMacCocoaAutoReleasePool() + 18779
27  com.apple.AppKit              	0x00007fff8ffedb81 -[NSWindow sendEvent:] + 8504
28  QtGui                         	0x000000010d5f77d7 QMacInputContext::reset() + 24823
29  com.apple.AppKit              	0x00007fff8ffe9644 -[NSApplication sendEvent:] + 5761
30  QtGui                         	0x000000010d5fc814 QMacInputContext::reset() + 45364
31  com.apple.AppKit              	0x00007fff8feff21a -[NSApplication run] + 636
32  QtGui                         	0x000000010d607680 QDesktopWidget::resizeEvent(QResizeEvent*) + 13040
33  QtCore                        	0x000000010e487af4 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 68
34  QtCore                        	0x000000010e487ea4 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 324
35  QtCore                        	0x000000010e48a58c QCoreApplication::exec() + 188
36  libInterface_Application.dylib	0x0000000108c1b6a7 SCIRun::Gui::GuiApplication::run(int, char const**) + 231
37                                	0x0000000108bf5c94 start + 52

**Comment by moritzdannhauer** [comment]
That seems to be a general problem for connecting modules.
I had that on my mac and on another windows laptop.

**Comment by dcwhite** [comment]
Sorry about the bad code; admittedly, this was not a real release so what you got was just "normal" instability :smirk:
