### ISSUE TITLE
bundle read error in ReadBundle

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1062]
There is an error when I read this bundle from the sci server:  /usr/sci/projects/sciweb/devbuilds/scirun5/lunch_150625/IBBM2015_bigfiles/Defib_simulation_results.bdl.
This is the error in scrirun:
ERROR: BinaryPiostream error reading unsigned int.

**Comment by dcwhite** [comment]
This one has revealed some bugs in the Field IO logic. Very yucky, must fix.
