### ISSUE TITLE
ViewScene Object Selection dropdown does not move when Viewer window is moved

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1066]
If the Object Selection dropdown is open, it remains where it is on the screen if I click and drag the ViewScene window around my screen.

**Comment by jessdtate** [comment]
annoying, but can wait.

**Comment by dcwhite** [comment]
@cbrightsci This is Mac only it seems. I'll take a look.

**Comment by cbrightsci** [comment]
@dwhite I'm working on getting this in the config menu. It won't matter if what I'm doing works.

**Comment by dcwhite** [comment]
ok i'll assign back to you...reparenting didn't work anyway
