### ISSUE TITLE
ViewScene Object Selection dropdown hides when clicked with no mouse move

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1067]
If I select or de-select and item, but keep my mouse on a single location (no movement), then click again (say to re-activate the layer) the Object Selection tab will disappear without acknowledging my selection.  If I move my mouse, this isn't a problem, it is only when my cursor position remains static.

**Comment by jessdtate** [comment]
Not sure what this is.  It sounds like a minor thing that can wait.

**Comment by zaracay** [comment]
Not a priority...just annoying.  Try clicking an object checkbox from the dropdown menu in the ViewScene window.  Then, without moving your mouse, click the now empty checkbox.  Instead of re-checking the box, the drop down menu will disappear.  If you move your mouse, however, you can re-check the box without the menu disappearing.
