### ISSUE TITLE
CrashReport - Deleting and reconnecting inputs to BuildBEMMatrix module

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1069]
I reproduced this error twice:
In the PotBased BEM forward solution, if I execute the BEM network, then delete the input pipes from the FlipSurfaceNormal modules and try to reconnect new pipes into those input ports, I will crash SCIRun.

Here's the log
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000030

VM Regions Near 0x30:
--> 
    __TEXT                 000000010a86a000-000000010a885000 [  108K] r-x/rwx SM=COW  /Users/USER/Documents/*/SCIRun.app/Contents/MacOS/SCIRun

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libInterface_Application.dylib	0x000000010a911ece SCIRun::Gui::PortWidget::performDrag(QPointF const&) + 334
1   libInterface_Application.dylib	0x000000010a911d69 SCIRun::Gui::PortWidget::doMouseMove(QFlags<Qt::MouseButton>, QPointF const&) + 121
2   libInterface_Application.dylib	0x000000010a8dba0a SCIRun::Gui::ModuleProxyWidget::mouseMoveEvent(QGraphicsSceneMouseEvent*) + 122
3   QtGui                         	0x000000010f8c46e2 QGraphicsItem::sceneEvent(QEvent*) + 1234
4   QtGui                         	0x000000010f919d9d QGraphicsWidget::sceneEvent(QEvent*) + 13
5   QtGui                         	0x000000010f8e2a21 QGraphicsScene::setFocus(Qt::FocusReason) + 2241
6   QtGui                         	0x000000010f8e33d4 QGraphicsScene::keyPressEvent(QKeyEvent*) + 1300
7   QtGui                         	0x000000010f8e6d88 QGraphicsScene::mouseMoveEvent(QGraphicsSceneMouseEvent*) + 88
8   QtGui                         	0x000000010f8fc16b QGraphicsScene::event(QEvent*) + 1419
9   QtGui                         	0x000000010f2f05ed QApplicationPrivate::notify_helper(QObject*, QEvent*) + 189
10  QtGui                         	0x000000010f2f6c64 QApplication::notify(QObject*, QEvent*) + 1060
11  QtCore                        	0x0000000110127bdc QCoreApplication::notifyInternal(QObject*, QEvent*) + 124
12  QtGui                         	0x000000010f2f089c QApplication::topLevelWidgets() + 492
13  QtGui                         	0x000000010f90e7ff QGraphicsViewPrivate::mouseMoveEventHandler(QMouseEvent*) + 1119
14  QtGui                         	0x000000010f917f38 QGraphicsView::mouseMoveEvent(QMouseEvent*) + 72
15  libInterface_Application.dylib	0x000000010a93866d SCIRun::Gui::NetworkEditor::mouseMoveEvent(QMouseEvent*) + 381
16  QtGui                         	0x000000010f34b49b QWidget::event(QEvent*) + 2475
17  QtGui                         	0x000000010f6dd0ac QFrame::event(QEvent*) + 44
18  QtGui                         	0x000000010f7696e7 QAbstractScrollArea::viewportEvent(QEvent*) + 23
19  QtGui                         	0x000000010f91550b QGraphicsView::viewportEvent(QEvent*) + 123
20  QtGui                         	0x000000010f76ba70 QAbstractScrollArea::qt_metacall(QMetaObject::Call, int, void**) + 336
21  QtCore                        	0x0000000110127687 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 151
22  QtGui                         	0x000000010f2f05be QApplicationPrivate::notify_helper(QObject*, QEvent*) + 142
23  QtGui                         	0x000000010f2f7190 QApplication::notify(QObject*, QEvent*) + 2384
24  QtCore                        	0x0000000110127bdc QCoreApplication::notifyInternal(QObject*, QEvent*) + 124
25  QtGui                         	0x000000010f2f4bdd QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) + 333
26  QtGui                         	0x000000010f2a46cb QMacCocoaAutoReleasePool::~QMacCocoaAutoReleasePool() + 18779
27  com.apple.AppKit              	0x00007fff8be1cb81 -[NSWindow sendEvent:] + 8504
28  QtGui                         	0x000000010f2997d7 QMacInputContext::reset() + 24823
29  com.apple.AppKit              	0x00007fff8be18644 -[NSApplication sendEvent:] + 5761
30  QtGui                         	0x000000010f29e814 QMacInputContext::reset() + 45364
31  com.apple.AppKit              	0x00007fff8bd2e21a -[NSApplication run] + 636
32  QtGui                         	0x000000010f2a9680 QDesktopWidget::resizeEvent(QResizeEvent*) + 13040
33  QtCore                        	0x0000000110126af4 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 68
34  QtCore                        	0x0000000110126ea4 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 324
35  QtCore                        	0x000000011012958c QCoreApplication::exec() + 188
36  libInterface_Application.dylib	0x000000010a8a96a7 SCIRun::Gui::GuiApplication::run(int, char const**) + 231
37                                	0x000000010a884c94 start + 52

**Comment by zaracay** [comment]
Turns out, you don't need to run the network before the crash occurs...Nor is it confined to the BuildBEM module, I just crashed 2 more times just by deleting a pipe and then trying to drag an output pipe away from a nearby module.  This is on my laptop with OS X 10.8.6

**Comment by dcwhite** [comment]
This is the same as the one you caught in the lunch--it's fixed in a branch, will be in master soon.
