### ISSUE TITLE
Converting Scirun 4 network files to Scirun 5 format

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1070]
I am not sure if there exists an issue already on this but ...
So, I got 2 requests, form Sumientra and Burak, regarding the conversion of old scirun4 networks.

In that context I wondered if it would be possible to support the old scirun4 network importer in coexistence with the one for scirun5. And, if a SCIRun4  module is not yet supported in SCIRun5 it just leaves out that particular module.

**Comment by dcwhite** [comment]
This is definitely on the list, and probably an item on one of the wishlists, but probably not an issue by itself yet. Looks like the demand is there. We really need an XML/XSLT expert to whip up a converter. Otherwise it will take a lot longer to implement. I will discuss with @lizutah.

**Comment by aylakhan** [comment]
SCIRun 4 has a script to convert SCIRun 3 networks. We could use that as a starting point.

**Comment by dcwhite** [comment]
Changed title so this issue shows up in searches.

**Comment by dcwhite** [comment]
@moritzdannhauer Do you or any of your fellow requesters need subnet support? I won't be able to deliver that for a while. But it looks good for a simple importer coming soon.

**Comment by dcwhite** [comment]
v4net conversion steps:
- [ ] Modules
- [ ] Correct module IDs (needed for GUI to load)
- [ ] Connections
- [ ] Module notes
- [ ] Connection notes
- [ ] Module state
- [ ] Other settings

**Comment by moritzdannhauer** [comment]
Github did not send me an email about Dan's question. I dont think subnets is required yet. I have some people that would like to test or give feedback related to the importer.

**Comment by dcwhite** [comment]
Check out File Menu-->*Import...
