### ISSUE TITLE
SCIrun crashed when running the dipolesourceexample test network. 

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/SCIRun#1074]
Below is my crash report. 

I was using a Macbook Air with 8 Gb of RAM, an I7 processor, and a intel HD Graphics 5000
.
..
...
....

Process:               SCIRun [16235]
Path:                  /Applications/SCIRun.app/Contents/MacOS/SCIRun
Identifier:            ???
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SCIRun [16235]
User ID:               501

Date/Time:             2015-07-02 12:41:25.870 -0600
OS Version:            Mac OS X 10.10.2 (14C109)
Report Version:        11
Anonymous UUID:        D27F8815-A199-7248-379A-639D7ECD0D3B

Sleep/Wake UUID:       847BD068-4F82-4FE7-87D7-3643FDDC2F69

Time Awake Since Boot: 100000 seconds
Time Since Wake:       2500 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 00000001065a9000-00000001065c4000 [  108K] r-x/rwx SM=COW  /Applications/SCIRun.app/Contents/MacOS/SCIRun

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libInterface_Modules_Render.dylib   0x0000000106ddcbee SCIRun::Render::SRInterface::handleGeomObject(boost::shared_ptrSCIRun::Core::Datatypes::GeometryObject, int) + 526
1   libInterface_Modules_Render.dylib   0x0000000106dc58b6 SCIRun::Gui::ViewSceneDialog::newGeometryValue() + 870
2   QtCore                          0x000000010bea8191 QObject::event(QEvent_) + 1073
3   QtGui                           0x000000010b0b8b3e QWidget::event(QEvent_) + 78
4   QtGui                           0x000000010b05e5ed QApplicationPrivate::notify_helper(QObject_, QEvent_) + 189
5   QtGui                           0x000000010b064c64 QApplication::notify(QObject_, QEvent_) + 1060
6   QtCore                          0x000000010be93bdc QCoreApplication::notifyInternal(QObject_, QEvent_) + 124
7   QtCore                          0x000000010be95000 QCoreApplicationPrivate::sendPostedEvents(QObject_, int, QThreadData_) + 736
8   com.apple.CoreFoundation        0x00007fff8b9eb681 **CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
9   com.apple.CoreFoundation        0x00007fff8b9dd80d __CFRunLoopDoSources0 + 269
10  com.apple.CoreFoundation        0x00007fff8b9dce3f __CFRunLoopRun + 927
11  com.apple.CoreFoundation        0x00007fff8b9dc858 CFRunLoopRunSpecific + 296
12  com.apple.HIToolbox             0x00007fff970daaef RunCurrentEventLoopInMode + 235
13  com.apple.HIToolbox             0x00007fff970da76e ReceiveNextEventCommon + 179
14  com.apple.HIToolbox             0x00007fff970da6ab _BlockUntilNextEventMatchingListInModeWithFilter + 71
15  com.apple.AppKit                0x00007fff8df03f81 _DPSNextEvent + 964
16  com.apple.AppKit                0x00007fff8df03730 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
17  com.apple.AppKit                0x00007fff8def7593 -[NSApplication run] + 594
18  QtGui                           0x000000010b017680 QDesktopWidget::resizeEvent(QResizeEvent_) + 13040
19  QtCore                          0x000000010be92af4 QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) + 68
20  QtCore                          0x000000010be92ea4 QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) + 324
21  QtCore                          0x000000010be9558c QCoreApplication::exec() + 188
22  libInterface_Application.dylib  0x00000001065e7057 SCIRun::Gui::GuiApplication::run(int, char const_*) + 231
23                                  0x00000001065c3c94 start + 52

**Comment by dcwhite** [comment]
This one is common and part of renderer instability.

**Comment by aylakhan** [comment]
@cbrightsci - please test

**Comment by dcwhite** [comment]
Duplicate
