### ISSUE TITLE
SolveLinearSystem Module - Method: Jacobi, giving bad solution

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1075]
The Jacobi method in SolveLinearSystem on the network DipoleSourveExample.srn5 gives all blue torso. See images: 

Expected Solution: 
![screen shot 2015-07-02 at 12 47 49 pm](https://cloud.githubusercontent.com/assets/12956701/8485158/e4b645e6-20b8-11e5-9c71-ecbb7836b288.png)

Jacobi Solution: 

![screen shot 2015-07-02 at 12 51 50 pm](https://cloud.githubusercontent.com/assets/12956701/8485203/2541bd5c-20b9-11e5-86f1-23dc8a011a9c.png)

**Comment by dcwhite** [comment]
This is probably the same display bug. When the solver method was changed, 1 was passed down as the max iteration, which will lead to the bad "solution" shown. Closed with 877ed1f43fc7584b92bac74715a4a7567249581d
