### ISSUE TITLE
SolveLinearSystem Module - Maximum Iterations error

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1076]
After putting the maximum iteration up to 5 and then back to 1 with method Conjugate Gradient, it gives a different soluton. 

Original solution: 
![screen shot 2015-07-02 at 12 59 47 pm](https://cloud.githubusercontent.com/assets/12956701/8485355/41d717ae-20ba-11e5-99a2-68f576ff6c1d.png)

After putting max iterations back to 1: 
![screen shot 2015-07-02 at 12 57 33 pm](https://cloud.githubusercontent.com/assets/12956701/8485310/fce51f2e-20b9-11e5-8eb1-dae3e6e009f9.png)

**Comment by jessdtate** [comment]
Max iterations is a parameter of the solver.  With only one iteration, it is unlikely to solve any problem.  This probably isn't a bug.  It is a good idea to change the default iterations to something more useful, like 100 or so.

**Comment by dcwhite** [comment]
This was a display bug. When adding a new SLS or opening the UI for the first time, 1 is displayed for max iterations (not a useful option), whereas 500 is the internal setting. If you then change to 5 and back to 1, the module works correctly and will use 1 for that setting, hence the crappy solution. I fixed the display bug in 877ed1f43fc7584b92bac74715a4a7567249581d, so this can be closed.
