### ISSUE TITLE
Module Porting: TransformMeshwithMatrix

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1079]

**Comment by jessdtate** [comment]
Correct name in SCIRun4 is TransformMeshWithTransform.  This is a very useful module in general.

**Comment by jessdtate** [comment]
Important

**Comment by dcwhite** [comment]
@jessdtate I'll merge this in Tuesday, can you add it to IBBM networks? We need some mesh shrinkage...

**Comment by jessdtate** [comment]
yes, I can add them to the networks.
