### ISSUE TITLE
Error messages appear over the SCIRun desktop

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1080]
I am not sure if it is a bug or a design choice. It looks cool, but it's not very practical.

The error messages from the modules appear on top of the SCIRun desktop in red and slowly fade away. Here's a screenshot.
![screen shot 2015-07-02 at 2 51 59 pm](https://cloud.githubusercontent.com/assets/3494177/8485605/bd27a0ec-20cc-11e5-8215-2fd9256e4932.png)

**Comment by dcwhite** [comment]
I'll make it configurable.

**Comment by jessdtate** [comment]
can wait
