### ISSUE TITLE
brain stimulator does not show the right potential distribution

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1081]
Loading the SCIRun network BrainStimulator_TDCS.srn5 from the testing lunch from July 2nd.

When executing the network as provided (after correcting the path to the inputs) the result looks good.
i.e. I see two electrodes active (in red and blue) and the rest of the head is green.

However, if I change the input potentials in SetupTDCS, I suddenly have a smooth distribution that does not correspond to the expected one.

Here's a screenshot of the results
![screen shot 2015-07-02 at 4 18 01 pm](https://cloud.githubusercontent.com/assets/3494177/8486881/09e6e682-20d6-11e5-9e49-625907447306.png)

**Comment by moritzdannhauer** [comment]
I found the problem and have a bug fix. pull request asap.

**Comment by dcwhite** [comment]
Closed with #1082.
