### ISSUE TITLE
memory increase when objects turned off in ViewScene

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1083]
When objects are turned off in the view scene, the memory increases, depending on the size of the geometry.

**Comment by jessdtate** [comment]
quite important

**Comment by dcwhite** [comment]
@jessdtate IBBM. Based on the labels, I'd say this one is pretty high priority.

**Comment by dcwhite** [comment]
Status: waiting on SRInterface refactoring
