### ISSUE TITLE
big geoms not visible.

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1084]
This is shown in the network Display_PhiE_data.srn5 in the ExampleNets/IBBM2015 folder.  When a geometry has a very large size, the viewscene will not show it, even if there are no other objects to render.  there seems to be an arbitrary cut off for visualizing objects.

**Comment by jessdtate** [comment]
can wait

**Comment by dcwhite** [comment]
@jessdtate IBBM
@jessdtate IBBM
@jessdtate IBBM
@jessdtate IBBM

**Comment by jessdtate** [comment]
#1888

**Comment by dcwhite** [comment]
I'll reopen and test this one after #1888's bugs are fixed.

**Comment by dcwhite** [comment]
I'll test this today.

**Comment by dcwhite** [comment]
![fixed2](https://user-images.githubusercontent.com/1399383/57889390-f1db1000-77f1-11e9-82ae-40b8addb8c2f.png)
