### ISSUE TITLE
Upgrade to newer Travis-CI infrastructure

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1096]
Might improve our clang-crash build failures.

http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by dcwhite** [comment]
@aylakhan Is this one done?

**Comment by aylakhan** [comment]
Timing out is still an issue, as is caching.

**Comment by dcwhite** [comment]
This is complete--we don't use `sudo` anymore.
