### ISSUE TITLE
colorbar numbers appear streched

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1099]
Opened the torso-tank-bem network.

After setting the appropriate path seems to be working fine with a simple execution.

The problem appears when viewing the scence. In it the reference numbers in the colorbar are streched out (look at screenshot for reference).

when clicked view in viewScene, the window appeared very flat and had to strech it up. Could be that?

![screen shot 2015-07-09 at 2 19 48 pm](https://cloud.githubusercontent.com/assets/3494177/8603420/f2c32310-2645-11e5-9608-4b84af387e6b.png)

**Comment by dcwhite** [comment]
ShowColorMap fonts have many issues; consider them definitely not delivered. I'll keep this one open for reference. See
https://github.com/SCIInstitute/SCIRun/issues/1086
https://github.com/SCIInstitute/SCIRun/issues/1063
