### ISSUE TITLE
misleading default shift/resolution settings for createstandardcolormap module on TDCS_TOY_EXAMPLE.

### ISSUE THREAD

**Issue by SeyhmusGuler** [SCIInstitute/SCIRun#1101]
The default shift and resolution for the createstandardcolormap module part of tDCS toy example is misleading. I needed to set the shift from -1 to 0 and resolution from 2 to 256 to see that results are meaningful. 

![screen shot 2015-07-09 at 14 30 25](https://cloud.githubusercontent.com/assets/3486150/8603585/2b305a78-2647-11e5-805c-92cb2bb62e79.png)

**Comment by dcwhite** [comment]
This is only an issue with older saved network files, since the module parameters' names changed. We should just update the network with better values.

**Comment by moritzdannhauer** [comment]
Sorry, I have not updated those in a while. Could you do that or do you me to do it?

**Comment by dcwhite** [comment]
If you could handle it that would be great. Not sure what the best settings are.

**Comment by dcwhite** [comment]
@moritzdannhauer Any updates on this one?

**Comment by dcwhite** [comment]
Can this get done by 3/25?

**Comment by dcwhite** [comment]
This appears to be done. The CSCM modules have their default values.
