### ISSUE TITLE
Once a toolkit is downloaded, the options are not accessible in drop down menu

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1103]
When I download a toolkit, the networks aren't available in the "toolkits" drop down menu. There also isn't a progress bar for when the toolkit is downloading, or a confirmation. Either one would work.

**Comment by dcwhite** [comment]
Agreed this menu could use some more functionality and better explanation in the GUI.

**Comment by dcwhite** [comment]
- [ ] Add a SCIRun environment variable for toolkit directory
- [ ] Once user sets it, download zips there
- [ ] On SCIRun load, add networks from toolkit directory to menu like in v4, but dynamically

**Comment by dcwhite** [comment]
See #1100

**Comment by dcwhite** [comment]
#1578 will make this easier to implement.
