### ISSUE TITLE
Investigate checkboxes on Yosemite

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1105]
Chris clicked away and the checkbox lost its check. See if this is a newer Mac issue.

**Comment by dcwhite** [comment]
Happened with ShowField.

**Comment by aylakhan** [comment]
Haven't been able to reproduce this on my Yosemite laptop. The radio buttons and checkboxes gray out when I click away from the module GUI, but retain their selection state.

**Comment by dcwhite** [comment]
That mimics what I see on 10.8. I'll have to see it again to make this a proper issue. Thanks for testing, I'll push this one for later.

**Comment by dcwhite** [comment]
We haven't seen this one in a while, closing.
