### ISSUE TITLE
Tikhonov module is not giving output

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1106]
Tried running the tikhonov-inverse network from Toolkits.zip during testing lunch.

The problem seems to lie within the inverse tikhonov module which is not providing any output.
When trying to use reportMatrixInfo on the first port, this module complains that there is no input.
At the same time, when using the first port to set the potentials on a field, the module does not complain, but the resulting field has 0 as potential

**Comment by dcwhite** [comment]
@jcollfont The problem was the new size check to satisfy your unit tests. It ends up breaking the toolkit example. So either the requirements are wrong, or the toolkit data is messed up, or I didn't code it correctly.
https://github.com/SCIInstitute/SCIRun/commit/57ef8ef7700af532f2d45c484bf18b0aeda4a609

**Comment by jcollfont** [comment]
Do you remember which test was failing?

**Comment by dcwhite** [comment]
If you run master branch unit tests, you can see the failure. The network is back to "normal"

**Comment by jcollfont** [comment]
I think I found where it breaks.
The commented part in line 202 from SolveInverseProblemWithTikhonovImpl.cc 
measuredData_->nrows() must always be equal to M   (forwardMatrix_->nrows()).
This is not dependant on the number of columns of the forwardMatrix. 

The two tests that fail are supposed to check if the number that for a non-square forward matrix. In one case they should go since measuredData_->nrows()==M, and in the other fail.

What I think should be changed is:
- remove the commented out part from lines 203 to 208
- remove "M < N &&" in line 198.  The number of columns in the forward matrix can be greater or smaller than its rows (and that will be underdetermined or overdetermined).

A separate question, how do you enable or disable the tests?

**Comment by dcwhite** [comment]
Pushing this one until after #1025 is done.
