### ISSUE TITLE
there is no documentation for SolveInverseProblemWithTikhonov in SCIRun5

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1107]
The help link in the SolveInverseProblemWithTikhonov module needs to be updated.

It currently points at an empty page:
http://scirundocwiki.sci.utah.edu/SCIRunDocs/index.php/CIBC:Documentation:SCIRun:Reference:SCIRun:SolveInverseProblemWithTikhonov

The old version is:
http://scirundocwiki.sci.utah.edu/SCIRunDocs/index.php/CIBC:Documentation:SCIRun:Reference:BioPSE:SolveInverseProblemWithTikhonov

**Comment by jcollfont** [comment]
I can try editing the page

**Comment by dcwhite** [comment]
It's from moving the module's package. We have to update the links in code.

**Comment by dcwhite** [comment]
I'll make a larger issue for checking all the module doc links.

**Comment by aylakhan** [comment]
I'll put in a temporary link on the new wiki module page.

**Comment by jcollfont** [comment]
I am trying to update the Tikhonov documentation but every time I try to change an equation (with a very simple change of name of a matrix) the preview returns an error where the equation should be:
Failed to parse (Missing <code>texvc</code> executable. Please see math/README to configure.):

Any idea what is it?
