### ISSUE TITLE
Move multiple error messages

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1112]
I would like to move multiple error messages at once. Currently you can only move one at a time right now.

**Comment by dcwhite** [comment]
Aha: if you switch to "Select Mode," one can select and move groups of messages. Is this sufficient?
<img width="254" alt="screenshot 2015-07-20 14 57 57" src="https://cloud.githubusercontent.com/assets/1399383/8787168/d55d4d52-2eef-11e5-92e1-0e1be0b165b7.png">
