### ISSUE TITLE
Move IBBM networks that don't work out of the IBBM2015 folder

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1113]
- [ ] greensite
- [ ] wbp
- [ ] tensor_view

**Comment by jessdtate** [comment]
You can just remove the entire IBBM2015 nets directory.   I have copied them and will put the relevant ones in the SCIRun-Exchange.

**Comment by dcwhite** [comment]
OK I'll wait for a PR there.
