### ISSUE TITLE
Windows 8.1 GetMatrixSlice Module does not have play button

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1115]
Cannot loop through matrix without play button in the module gui.

**Comment by dcwhite** [comment]
![playmode](https://cloud.githubusercontent.com/assets/1399383/8605757/9897daa8-2644-11e5-962c-73f3c655aa5c.png)

**Comment by dcwhite** [comment]
Oh maybe it's the module UI size issue again--I'll close this as a duplicate.

**Comment by dcwhite** [comment]
Couldn't replicate on Windows 8.1 test machine. What's your screen resolution?
