### ISSUE TITLE
Make a "New User" Qt Wizard for initial setup

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1128]
Include setting data path and connection style, and explain other settings and hotkeys.

http://doc.qt.io/qt-4.8/qwizard.html

**Comment by dcwhite** [comment]
@jessdtate Let's do this for this year's IBBM. Who is doing the initial SCIRun training?

**Comment by jessdtate** [comment]
@kgillette  is doing the first scirun lab.

**Comment by dcwhite** [comment]
@kgillette Check out this issue. It will be easy to code up such a wizard. Let me know what all you want in there, to ease the initial SCIRun walkthrough.

**Comment by kgillette** [comment]
Page 1: 

Introduction

This wizard will help you setup and configure SCIRun for initial install and use. These preferences can be changed later within SCIRun Preferences. 

Page 2: 

Configuring Paths

SCIRun data folder:
Specify the location of SCIRun’s data folder.  This path is referenced in certain modules. 
This data folder can be downloaded from sci.utah.edu/scirun.html.

Insert widget for selecting SCIRun data folder path

User networks and data
Specify the primary directories for loading of SCIRun networks and data. If no path is set for user data, the default is the SCIRun data folder path (IS THIS POSSIBLE?)

Insert widget for selecting user networks path
Insert widget for selecting user data path

*These directories can also be altered within SCIRun preferences (NEED TO UPDATE THIS TOO?).

Page 3: 

Display Options

Data flow pipelines between modules can be adjusted based on user preference. 

Insert widget to select data flow pipeline.
Pictures of the different connections that change when you press the button? 

*Display options can be later altered within SCIRun preferences.

Page 4: 

For more information on SCIRun 5 functionality, documentation can be found at: 

INSERT LINK HERE

**Comment by kgillette** [comment]
Page 1:

Introduction

This wizard will help you setup and configure SCIRun for initial install and use. These preferences can be changed later within SCIRun Preferences.

Page 2:

Configuring Paths

SCIRun data folder:
Specify the location of SCIRun’s data folder. This path is referenced in certain modules. 
This data folder can be downloaded from sci.utah.edu/scirun.html.

Insert widget for selecting SCIRun data folder path

User networks and data
Specify the primary directories for loading of SCIRun networks and data. If no path is set for user data, the default is the SCIRun data folder path (IS THIS POSSIBLE?)

Insert widget for selecting user networks path
Insert widget for selecting user data path

Page 3:

Display Options

Data flow pipelines between modules can be adjusted based on user preference.

Insert widget to select data flow pipeline.
Pictures of the different connections that change when you press the button?

Page 4:

For more information on SCIRun 5 functionality, documentation can be found at:

INSERT LINK HERE

**Comment by dcwhite** [comment]
Thanks!

**Comment by dcwhite** [comment]
Another page idea: show hovering over module widget displays buttons.

**Comment by dcwhite** [comment]
And another setting to check: save before execute.

**Comment by jessdtate** [comment]
Is it possible to have a link or reference to the preference window?  it may be good to allude there so they can check the other options.

**Comment by dcwhite** [comment]
I'll add a button to pop it up. Should be easy.
