### ISSUE TITLE
Crash when adding ViewScene module through right click Windows 8.1

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1129]
After running a showField attempt to right click and add viewScene to the output port through the dropdown menu that appears. SCIRun crashes. This does not occur if the showField has not been run yet.

Crash Report:
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: SCIRun.exe
  Application Version:  0.0.0.0
  Application Timestamp:    559ff44d
  Fault Module Name:    Interface_Modules_Render.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   559ff42c
  Exception Code:   c0000005
  Exception Offset: 000000000004a3d1
  OS Version:   6.3.9600.2.0.0.768.101
  Locale ID:    1033
  Additional Information 1: 9dd9
  Additional Information 2: 9dd929accfc4e014f4fb53651faf49cb
  Additional Information 3: bd09
  Additional Information 4: bd09b3649b3c605db6b0d3f2e0941aaa

**Comment by dcwhite** [comment]
@cbrightsci Ran through debugger. Definitely crashing in handleGeomObject, on a spire object call--probably this is "too early" to be calling into spire. So this one will be fixed too once proper initialization-locking-waiting logic is implemented.

**Comment by dcwhite** [comment]
Appears to be a memory problem in the tetrahedralize()/dummyinit() functions. More debugging required.

**Comment by dcwhite** [comment]
@jessdtate @ajanson IBBM

**Comment by dcwhite** [comment]
@ajanson Is this still an issue on Win7 or 10?

**Comment by ajanson** [comment]
Just tested this on Windows 7 and it crashed.

**Comment by dcwhite** [comment]
Crashes on Mac too--ShowField needs to be executed already. I just need to have VS wait like normal. Let me try to fix.
