### ISSUE TITLE
colormap text behind object in Viewscene

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1130]
This is not consistently the case, but sometimes the transparent object obscure the text a little.  I think it is when the objects are recalculated.

**Comment by aylakhan** [comment]
See also #1063.

**Comment by jessdtate** [comment]
I still see this problem in the testing today.  It happens when most often when I change a parameter of the colormap text, such as the scaling.  It also happens more often with high number of digits, possible because there is more chance of overlap.  It only happens with transparent objects. There is a test network that will often show the bug upon executing the network and opening the viewscene.  if the text is correct, then it usually appears by changing the scaling or the number of decimal places.  


![viewscene_2016 02 22 145248 109_1](https://cloud.githubusercontent.com/assets/3484631/13234084/2c440154-d974-11e5-8843-85e6d6205565.png)

**Comment by dcwhite** [comment]
@cbrightsci Still not fixed.
