### ISSUE TITLE
Modules not added to SCIRun5: GetMeshQualityField

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1136]
I have made a network for make a lead field matrix and there are three modules that I needed to use that are not in SCIRun5 yet.

- [x] GetMeshQualityField:
I used this to clip out flat tets from my mesh generated in Cleaver2.

- [x] GetColumnOrRowFromMatrix:
I used this to loop through my sources to create the lead field matrix.

- [ ] ShowAndEditDipoles:
This makes it so I can visualize my dipoles.
See Issue #991.

**Comment by dcwhite** [comment]
Thanks.
For GCORFM, try GetMatrixSlice. I tried to simplify the name.
Other two are coming soon.

**Comment by dcwhite** [comment]
See module conversion tutorial for help getting started on this one.

**Comment by allywarner** [comment]
GetMeshQualityField is converted. There should be testing code added.
