### ISSUE TITLE
renaming old modules

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1146]
In the fwd/Inv toolkits, the potential based fem forward network, there is an old version of MFDOElements. The module name was changed and not completely updated properly, so that the gui doesn't load (it is a default gui).

**Comment by dcwhite** [comment]
The fix in the network file is to rename all instances of MapFieldDataOntoElems to MapFieldDataOntoElements. I will use this example to shore up the error checking in the network file loading code.

**Comment by dcwhite** [comment]
@jessdtate How is this message?

<img width="463" alt="screenshot 2015-07-21 14 54 36" src="https://cloud.githubusercontent.com/assets/1399383/8812280/7ad9065e-2fb8-11e5-84b8-3a85d3ffb87b.png">

**Comment by jessdtate** [comment]
this message is good.  Is this a temporary measure or the final solution?

**Comment by dcwhite** [comment]
Temporary, just a part of solution.

**Comment by dcwhite** [comment]
We'll close this for now, since it will only affect a small number of users.
