### ISSUE TITLE
error mapping colors on edges

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1147]
This bug is only noticeable with really coarse data and large color changes in along the edges.  

As seen in these examples, the edges are rendered with the colors interpolating color values to the half way point, instead of along the entire edge.  It repeats the first segment (appears to be identical).  The faces seem to interpolate the color correctly.

![viewscene_2015 07 21 141720 746_1](https://cloud.githubusercontent.com/assets/3484631/8811441/4ac4573e-2fb3-11e5-95a2-e57b39e624f3.png)

![viewscene_2015 07 20 155559 192_1](https://cloud.githubusercontent.com/assets/3484631/8811191/8ab75b4a-2fb1-11e5-8148-f54e3f600080.png)

**Comment by cbrightsci** [comment]
@jessdtate could you attach a network where this is occurring for me to use?
