### ISSUE TITLE
InterfaceWithTetGen crashes on Windows 8

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1149]
Does not work at all. Current version of SCIRun v5.0-alpha.X.1

**Comment by dcwhite** [comment]
Any more details?

**Comment by dcwhite** [comment]
This needs @cbrightsci's suggested description.

**Comment by cbrightsci** [comment]
I verified that the network crashes with this module on windows 7 as well.

**Comment by dcwhite** [comment]
I tried src/ExampleNets/regression/tetgenTorsoHeart.srn5 and it works fine. Need a network...

**Comment by ajanson** [comment]
src/ExampleNets/regression/tetgenTorsoHeart.srn5 crashes on me

**Comment by dcwhite** [comment]
This seems to be Windows 8 only.

**Comment by dcwhite** [comment]
This is a general problem with tetgen's memory management. The code uses `unsigned long` for pointer arithmetic, and on machines with lots of memory, this datatype can be too small to hold the entire address space, which will lead to crashes when large addresses are used. The necessary fix (change to `size_t`) will affect a lot of tetgen code.

**Comment by dcwhite** [comment]
After perusing the code, looks like an attempt was made to adapt to 64-bit memory space, but some places were missed. I'll just fix those places and commit that to see if that fixes the problem.

**Comment by dcwhite** [comment]
Fix is good. Large memory machines should not crash anymore. This same problem would probably affect SCIRun 4, I imagine.

**Comment by aylakhan** [comment]
Yes, it would. Want to patch SCIRun 4 also?

**Comment by dcwhite** [comment]
Sure
