### ISSUE TITLE
Update SCIRun 4 "Basic Tutorial" in v5

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1155]
We have virtually all the modules now to reimplement it.

http://sci.utah.edu/devbuilds/scirun_docs/BasicTutorial.pdf

**Comment by dcwhite** [comment]
@jessdtate Would you have time to work on this one, similar to your module porting guide? It would be mostly LaTeX copy/paste (mainly changing the screenshots). The Viz stuff that's not implemented can then be turned into high-priority issues.

**Comment by jessdtate** [comment]
I could probably do this, but this is a simple enough task that we could get one of the newer students to work on it.  It would even help them use SCIRun better.  Someone like Karli, Wilson, or Ally.  Maybe a joint effort.  I don't mind taking the lead, being the advisor, checking the work, or something like that.

**Comment by dcwhite** [comment]
Awesome idea! Do you think it's worth organizing a meeting, or can it just be a hallway chat?

**Comment by jessdtate** [comment]
Can we bring it up in the programming lunch, just for a couple minutes?  I think if I can get an idea of who can do it, we can work out the details without doing a meeting.

**Comment by dcwhite** [comment]
Sounds good. I'll assign to you as a reminder to bring it up. :smile:

**Comment by dcwhite** [comment]
@jessdtate will coordinate efforts by @wgood and @kgillette (who I just invited to SCIInstitute's github org).

**Comment by aylakhan** [comment]
@kgillette - do we have a LaTeX doc for this?

**Comment by jessdtate** [comment]
@kgillette has started working on  this document, but she ran into some snags as some of the modules and functionality hasn't been ported yet. I think she made issues for them.

**Comment by kgillette** [comment]
There were a few modules that had not yet been implemented like showmeshboundingbox. I am pretty sure I filed an issue report. I think the latex document is located on my computer. Would you like me to start updating it again? I can do it this weekend.

**Comment by dcwhite** [comment]
Just replace ShowMeshBoundingBox with EditMeshBoundingBox in the tutorial. Yes, please get any latex work pushed to github, so it can be collaborated on.
