### ISSUE TITLE
Tensors

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1157]

**Comment by dcwhite** [comment]
@cbrightsci @aylakhan @jessdtate

**Comment by aylakhan** [comment]
@moritzdannhauer @zaracay @ajanson @jessdtate - do we have content for this issue?

**Comment by dcwhite** [comment]
It was conceived of as an umbrella issue. We could turn this issue into its own project.

**Comment by aylakhan** [comment]
Do we have related issues to link to? If so, turning this into a project would make sense.

**Comment by dcwhite** [comment]
https://github.com/SCIInstitute/SCIRun/search?q=Tensor&state=open&type=Issues&utf8=%E2%9C%93

**Comment by aylakhan** [comment]
Moved to project, closing this issue.
