### ISSUE TITLE
click_module_GUI_button_executes_network

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1166]
I need to be able to execute the entire scirun5 network by a button press of the module GUI (ElectrodeCoilSetup).

**Comment by dcwhite** [comment]
Verified the existing implementation works for push buttons (as well as checkboxes and radio buttons, the signature takes a `QAbstractButton`). Just add a line like this to the constructor of your dialog class:
```
connectButtonToExecuteSignal(yourGuiButtonObject_);
```
