### ISSUE TITLE
Missing Modules From SCIRun 4 Needed

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1167]
Real time DBS network needs...
- [x] InsertVoltageSource (#1259)
- [x] InsertCurrentSource (#1288)
- [x] ApplyFEMVoltageSource (#1260)
- [x] ChooseMatrix (#206)
- [ ] GenerateElectrode (#1289)
- [x] ClipFieldByMesh (#1176)
- [ ] ClipFieldToFieldOrByWidget (#1290)
- [x] ReportFieldGeometryMeasures (#1291)
- [x] CalculateCurrentDensity (#1292)
- [x] CreateGeometricTransform (#1293)
- [x] ScaleFieldMeshAndData
- [x] SetSubMatrix (#1294)

**Comment by dcwhite** [comment]
Thanks!

**Comment by moritzdannhauer** [comment]
Some of the code of those modules is interesting for me (e.g. splines in Generate Electrode) and the BrainStimulator development. It would be great if the conversion of the algorithmic code makes it 
possible for me to call those functions.

**Comment by dcwhite** [comment]
@SCIInstitute/butson-lab Here's the list Andrew gave me for requested modules. I'll add a link to his network soon.

**Comment by dcwhite** [comment]
I added a few more modules to the list above based on Andrew's production network, linked here: https://uofu.box.com/s/dlc1f0eyxy8c58q96h83szngaoqjqp6l

**Comment by dcwhite** [comment]
Closing this since there are issues for the last two, assigned to @cbrightsci.
