### ISSUE TITLE
Module Selector dissapears when SCIRun is minimized

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1168]
This occurs on both Windows 7 and 8 and also if the module selector is docked or undocked. This also occurs for the Log and Provenance windows as well.

Have module selector window open and docked.
Minimize SCIRun.
Click on SCIRun in the bottom toolbar to reopen.
Module selector is now gone. You have to go back into the window menu and reopen it.

**Comment by dcwhite** [comment]
#229 fixed this for Module UIs. I confirmed it still exists for main window dockable widgets. The same fix should work there too.
