### ISSUE TITLE
VTK Reader Support

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1169]
SCIRun 4 had a vtk to trisurf reader in read field. I would like for this to be supported along with support for a few more fields such as curvefields (lines) and also support for non-scalar data.

**Comment by dcwhite** [comment]
I can port the v4 code easily. Additional issues should be made for new field/data types.

**Comment by dcwhite** [comment]
@aylakhan Ported the code for this. It works on Windows but not Mac with the exact same vtk file. Have you seen this before?
The file is here (it's an output from SCIRun 4's VTK WriteField--which may be buggy I guess): https://www.dropbox.com/s/i7v5dwk8vbgx23w/cubeVtk.vtk?dl=0

**Comment by aylakhan** [comment]
I remember Chris Butson having some problems with this too, but on Windows. I'll test.
