### ISSUE TITLE
CollectMatrix module conversion.

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1183]
This is needed for CinC.  Part of the forward/inverse toolkit.

**Comment by jessdtate** [comment]
example in the fwd/Inv toolkit: Make_Lead_field_Matrix.srn (in potential_based_FEM).

**Comment by dcwhite** [comment]
@jessdtate Could you port over that network into v5, with a space for CollectMatrix? Just commit to src/ExampleNets/developer for now. Thanks!
