### ISSUE TITLE
string/script inputs and outputs in the DataIO modules

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1185]
this is needed for command line use(#1184), scripting, and headless use.  The Read* modules need filename inputs and outputs and filename inputs for the Write* modules.  The Read* modules need a script input option, where the environment variable containing the filename can be typed.  

Part of this is a better way to select the file type.  currently, the filetype resets every time the file dialogue window comes up.

**Comment by dcwhite** [comment]
Read/Write have string filename input/output ports already. Strings coming in there will override the dialog selection. I can make that clearer in the GUI.

This issue then will be for implementing the script input option.
