### ISSUE TITLE
string manipulation modules

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1186]
these modules need to be ported to assist in scripting (#1184):
 - [x] GetStringFromBundle
 - [x] SplitFilename
 - [x] PrintStringIntoString
 - [x] ReportStringInfo
 - [x] GetNetworkFilename
 - [x] JoinStrings
 - [x] PrintMatrixIntoString (#1194)

These seem like good modules to help teach students how to port modules.

**Comment by dcwhite** [comment]
Good idea re: tutorial conversion modules. When we get closer to that event, I will set some of these up on a branch so we can convert them live while also having a "finished product" to look at.
