### ISSUE TITLE
list of most important features needed for defib and metronic projects

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1187]
- [x] command line scripting (passing file inputs) #1184
- [x] string manipulation (filename input & output ports in Read\* and Write\* modules #1185.  string modules #1186)
- [ ] widgets 
- [x] interfacewithMatlab/Python
  Modules used often:
- [ ] Bundle modules (WriteBundle, Insert/GetMatrixFromBundle, Insert/GetStringsFromBundle)
- [x] ReportMatrixRow/ColumnMeasure

**Comment by dcwhite** [comment]
Remaining stuff in separate issues.
