### ISSUE TITLE
Fix travis build script (and general new-workspace build steps) to incorporate generated factory code

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1210]
The workaround now is to run cmake twice. What we need is a script that will make the externals first, not including SCIRun, then make the generated code before configuring SCIRun proper, then make all. Right now the make all will configure SCIRun right after externals are made, so you can't inject another configure step there (unless we further customize the superbuild setup). 

The current travis build script does this (the double cmake), and it can build everything fine, but the build is marked as failed since the first cmake step returns non-zero (see this build, which worked but marked as failed https://travis-ci.org/SCIInstitute/SCIRun/builds/83590504). There's no way around that on the travis side.

**Comment by dcwhite** [comment]
@aylakhan According to you, this can be closed now--I'll let you do the honors.

**Comment by aylakhan** [comment]
CMake code seems to be working now. Closing bug.
