### ISSUE TITLE
Networks path cleanup

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1215]
Looks like we still have some networks with hardcoded paths, splitFieldByDomain.srn5 for example.

**Comment by dcwhite** [comment]
Only the ones in the "regression" folder are guaranteed to work universally. That one is in the "developer" folder.

**Comment by aylakhan** [comment]
If it's in the repo, paths need to be correct for the sake of other developers. Not a high priority though.

**Comment by dcwhite** [comment]
This can be unit-tested. Run a grep for file state variables that don't start with %SCIRUNDATADIR%.
