### ISSUE TITLE
Fallback for data importers

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/SCIRun#1216]
For file formats with the same file extension (SCIRun matrix vs. Matlab matrix for example), have a mechanism in place to try another compatible importer if the first choice or default fails.

**Comment by dcwhite** [comment]
This was discussed today at length in the FwdInvToolkit meeting. Let's reopen.

**Comment by dcwhite** [comment]
@jab0707 here’s one of two issues for the “smart reader” idea
