### ISSUE TITLE
-E flag caught on save check

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1231]
-E flag from the command line is supposed to close scirun after executing the network.  The quit command is initiated, but the save network check dialogue still pops up, preventing the software from closing.  It seems to ask everything, even if the network is unchanged.  Ideally the -E flag would close regardless of any changes that may occur in the execution.   This functionality is needed in bash scripting.

**Comment by dcwhite** [comment]
I think it works as intended if "--regression" is also used, or if developer mode is on. I'll look into why this case doesn't work.
