### ISSUE TITLE
Upgrade TetGen to version 1.5 in SCIRun 4 and 5

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1240]
The code has been completely rewritten and is much improved. Upgrading my own build has solved almost every problem I have had with running tetgen.

**Comment by aylakhan** [comment]
Are there any interface changes needed to run Tetgen 1.5?

**Comment by ajanson** [comment]
No interface changes. Just replace the the 3 tetgen source code files.

**Comment by aylakhan** [comment]
Depends on issue #1241.

**Comment by aylakhan** [comment]
Basic upgrade is done for both. Will see if it's reasonable to turn libtet into a shared object library through external project patch.

**Comment by aylakhan** [comment]
Shared object library build attempt in issue #1271.

**Comment by dcwhite** [comment]
@ajanson needed the unreleased 1.5.1 beta version.

**Comment by aylakhan** [comment]
@ajanson has been tasked with updating the build.

**Comment by dcwhite** [comment]
Um, I just did it.

**Comment by aylakhan** [comment]
In SCIRun 4 too?

**Comment by dcwhite** [comment]
He told me if 5 is working, 4 does not need to be updated.

**Comment by aylakhan** [comment]
Sure, that's fine.
