### ISSUE TITLE
State variable not accessible when loading python script through GUI

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#1246]
[test.txt](https://github.com/SCIInstitute/SCIRun/files/43289/test.txt)

**Comment by dcwhite** [comment]
I suspect it's a race condition with the module constructor, but we'll see.

**Comment by dcwhite** [comment]
I'm fixing the case above, which turned out to be a module problem in Read/WriteField. If it comes up again, open another issue.
