### ISSUE TITLE
Work on true Headless Build (sans QT)

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#1247]
look at #295

**Comment by dcwhite** [comment]
I'll start it but it will need plenty of ViewScene work as well.

**Comment by aylakhan** [comment]
Fixed in 1f9de8470113d5cd331cfd2492e3fd5e45509409.

**Comment by dcwhite** [comment]
I'll start a special branch with headless turned on so Travis can build it regularly (a la build_testing branches)
