### ISSUE TITLE
Tetgen external as shared library

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1271]
Attempt to patch tetgen external build to generate a shared library. The [git apply](https://git-scm.com/docs/git-apply) command should work universally, assuming it can be made to work outside a Git controlled working tree.

**Comment by dcwhite** [comment]
@aylakhan Please kill 💣

**Comment by aylakhan** [comment]
The effort involved is not equal to the benefit. Killing.
