### ISSUE TITLE
Basic tutoral: module pop-up menu overlap and not allowing module selection

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1272]
The pop-up menu for connecting ports overlaps and it won't let me navigate past the level of NewField, Misc, DataIO, etc.
![screen shot 2015-12-29 at 3 57 40 pm](https://cloud.githubusercontent.com/assets/12956701/12043732/e8c6ffd0-ae44-11e5-8cbc-7315485e4429.png)

**Comment by kgillette** [comment]
I am using Version v5.0-alpha.Y.

**Comment by dcwhite** [comment]
That menu has always been problematic, on every platform. I am open to suggestions for improvement (I'd rather not have the giant, single flat list of SCIRun 4, however).

**Comment by kgillette** [comment]
It may be fine even if it overlaps, but I can't seem to actually select a module which might be a larger issue for creating an image for the basic tutorial. Instead of having the big long flat list, you might be able to do zooming and scrolling so you only effectively see like 5 modules?

**Comment by dcwhite** [comment]
Good idea, I'll look into a scrollable menu.
