### ISSUE TITLE
ShowMeshBoundingBox not yet converted from SCIRun 4

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1275]
The ShowMeshBoundingBox has not yet been converted from SCIRun 4, which is required for the Basic Tutorial. I am using Version v5.0-alpha.Y.

**Comment by dcwhite** [comment]
For right now, you can use EditMeshBoundingBox, to at least show a box. Then once SMBB is converted (the module, not the building), the screenshots can be updated to show the nicer colored box.

**Comment by dcwhite** [comment]
@jessdtate this one seems like an easy one for the interns. Should we schedule it for the summer too?

**Comment by jessdtate** [comment]
Yeah, that should be easy

**Comment by dcwhite** [comment]
@jessdtate Interns need to do this one. Fun test of aesthetics.

**Comment by dcwhite** [comment]
Will discuss at next week's meeting

**Comment by RubioJr9** [comment]
I'm going to start working on this.
