### ISSUE TITLE
Building SCIRun: Bundle problem 

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1276]
I get an error due to bundling (see below) while building SCIRun. It will build if I only run make SCIRun_test and not the whole SCIRun. 

Cmake Version: 2.8.12.2
OS X version: 10.11.2

I get the following build error when I run just make: 

Linking CXX executable ../SCIRun.app/Contents/MacOS/SCIRun
CMake Error: cmake version 2.8.12.2
Usage: /Applications/CMake 2.8-12.app/Contents/bin/cmake -E [command] [arguments ...]
Available commands: 
  chdir dir cmd [args]...   - run command in a given directory
  compare_files file1 file2 - check if file1 is same as file2
  copy file destination     - copy file to destination (either file or directory)
  copy_directory source destination   - copy directory 'source' content to directory 'destination'
  copy_if_different in-file out-file  - copy file if input has changed
  echo [string]...          - displays arguments as text
  echo_append [string]...   - displays arguments as text but no new line
  environment               - display the current environment
  make_directory dir        - create a directory
  md5sum file1 [...]        - compute md5sum of files
  remove [-f] file1 file2 ... - remove the file(s), use -f to force it
  remove_directory dir      - remove a directory and its contents
  rename oldname newname    - rename a file or directory (on one volume)
  tar [cxt][vfz][cvfj] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args] ...   - run command and return elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
Available on UNIX only:
  create_symlink old new    - create a symbolic link new -> old

make[3]: **\* [SCIRun.app/Contents/MacOS/SCIRun] Error 1
make[2]: **\* [Main/CMakeFiles/SCIRun.dir/all] Error 2
make[1]: **\* [Main/CMakeFiles/SCIRun.dir/rule] Error 2
make: **\* [SCIRun] Error 2

**Comment by aylakhan** [comment]
Can you print out your terminal environment? Also, look in your src/Main/CMakeLists.txt file for the custom CMake commands that assemble the Mac OS X bundle - try echoing the copy and copy_directory commands to narrow down specifically which one is failing?

**Comment by kgillette** [comment]
Here is my env: 

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/jt/_5849_1x6xj1cr9nfshzgz2w0000gp/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.KgN2czjQUI/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=760926A2-459A-42F5-97C6-A19D053EDB32
USER=karligillette
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.cFeGhrXO74/Listeners
__CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
PATH=/opt/local/libexec/qt4/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/MATLAB_R2011a_Student.app/bin/:/Applications/CMake 2.8-12.app/Contents/bin
PWD=/Applications/CMake 2.8-12.app/Contents/bin
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.YuK2vk4Av6/unix_domain_listener
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/karligillette
LOGNAME=karligillette
DISPLAY=/private/tmp/com.apple.launchd.2Xk0npUM2T/org.macosforge.xquartz:0
SECURITYSESSIONID=186a7
_=/usr/bin/env

The following is what I get when I run the copy or copy_directory commands that are under the Apple and Build if statement from CmakeLists.txt document. Looks like it isn't setting up my env variables. 

echo ${CMAKE_COMMAND} ARGS -E copy ${SCIRun_SOURCE_DIR}/CMake/qt.conf ${APPLICATION_NAME}.app/Contents/Resources
ARGS -E copy /CMake/qt.conf .app/Contents/Resources

echo  ${CMAKE_COMMAND} ARGS -E copy_directory ${SCIRun_BINARY_DIR}/Shaders ${APP_PATH}/MacOS/Shaders
ARGS -E copy_directory /Shaders /MacOS/Shaders

echo ${CMAKE_COMMAND} ARGS -E copy_directory ${SCIRun_BINARY_DIR}/Assets ${APP_PATH}/MacOS/Assets
ARGS -E copy_directory /Assets /MacOS/Assets

echo ${CMAKE_COMMAND} ARGS -E copy_directory ${SCIRUN_LIB_DIR} ${APP_PATH}/Frameworks
ARGS -E copy_directory /Frameworks

**Comment by aylakhan** [comment]
Change the custom cmake command to look like: ${CMAKE_COMMAND} ARGS -E echo "${SCIRun_BINARY_DIR}/Shaders ${APP_PATH}/MacOS/Shaders
ARGS -E copy_directory /Shaders /MacOS/Shaders", and then run the build

**Comment by dcwhite** [comment]
@allywarner has the same problem on 10.11.

**Comment by kgillette** [comment]
I changed my CmakeLists.txt and it appears to have compiled without any problems.

**Comment by aylakhan** [comment]
Can you submit your change as a pull request? I'll have a look.

**Comment by kgillette** [comment]
I tried to compile it again, but now I am getting the same error as before so I may have only compiled the SCIRun test before.

**Comment by dcwhite** [comment]
Defunct
