### ISSUE TITLE
Update Module/Demo Spreadsheet for EAB 2016

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1283]
Link: https://docs.google.com/spreadsheets/d/1Ba6CUOMzTD2rR4ebY0KGvaP6JXGA8HHeyE1uqZIFPu8/edit

**Comment by dcwhite** [comment]
I think we're mostly up to date. Anything else major to edit on the sheet? @cbrightsci @aylakhan @moritzdannhauer @lizutah

**Comment by aylakhan** [comment]
I'm done with it.

**Comment by moritzdannhauer** [comment]
Two new modules that I put in the spreadsheet disappeared and I cannot edit it anymore!?

**Comment by dcwhite** [comment]
@moritzdannhauer That's the wrong link above. Sorry. Here's the new spreadsheet to check (also fixed above): https://docs.google.com/spreadsheets/d/1Ba6CUOMzTD2rR4ebY0KGvaP6JXGA8HHeyE1uqZIFPu8/edit

**Comment by moritzdannhauer** [comment]
Thanks!
