### ISSUE TITLE
Python data values, part 3 continued: invert code in order to pass values back from Python to a module--Fields

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1300]
Continued from #1282

**Comment by dcwhite** [comment]
@jessdtate Can you come up with a quick set of field cases for me to test? There are a zillion field types, so there are a ton of branches in this matlabfieldconverter code, but just give me the most common cases (i.e. the ones you really want to use now)--one for each type.

**Comment by jessdtate** [comment]
It surprises me that there are so many cases for loading the data, as the importer has always been a bit picky.  The most common ones are trisurf, tetvol, latvol/nrrd.  Less common but still important are quadsurfs and hexvols.  I will get some examples.

**Comment by dcwhite** [comment]
The [cyclotomic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of `MatlabToFieldAlgo::mlanalyze` is off the charts.

**Comment by dcwhite** [comment]
Not to mention being 2400 lines long :sob:
