### ISSUE TITLE
Icons in 10.11 are large and not to scale with the module

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1305]
Image sent to Dan White via Slack.

![scirun_icon](https://cloud.githubusercontent.com/assets/1399383/12682478/f0de5ac6-c670-11e5-98a0-69c3f7aafb5e.jpg)

**Comment by dcwhite** [comment]
I'll wait to investigate this until after the Qt 5 upgrade.

**Comment by dcwhite** [comment]
I see the same thing on Windows 10 with retina display.

**Comment by dcwhite** [comment]
Need to test new Qt5 installer on 10.12+
