### ISSUE TITLE
V5.0-alpha.AA not loading old networks

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1306]
I fetched the latest source today and compiled. I tried to load networks I built on three different releases over the past year, and none of them loaded. I get the error:

[ERROR] File load failed(/home/sci/gduffley/Projects/VTAGenerationImprovement/NewStuff/runSims.srn5): exception in load_xml, input stream error

I am running suse 13.2 with NVIDIA graphics

**Comment by dcwhite** [comment]
@jessdtate had the same problem. What system did you create the networks on? Can you send me one of the networks? Jess, what was the fix you applied for the point cloud test network?

**Comment by jessdtate** [comment]
I remade the network and saved it out. Not of much use if you have a big network.

**Comment by gduffley** [comment]
@dcwhite @jessdtate Yeah, my network is pretty big. I wanted to integrate it with some Python stuff into it. I tested multiple networks, one that I created on my suse station this morning, and another that I made on OSX 10.10 this summer. Ill add the network I made this morning as /home/sci/gduffley/Public/danSRN.srn5

**Comment by dcwhite** [comment]
Fixed with 0d10021a7b8bcad4ad16fca2ec8f02d679e4dc41
