### ISSUE TITLE
saving networks in the scirundir path

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1312]
I'm having trouble saving a network that has the SCIRunDir path in it.  SCIRun will automatically detect it when I try to save and add SCIRunDir% to the the path, but the network will not actually save.

**Comment by dcwhite** [comment]
Can you provide an example and exact replication steps?

**Comment by jessdtate** [comment]
steps to recreate:

1.  create network
2.  save network in child directory of the directory set as %SCIRUNDATADIR%.
3.  message stating %SCIRUNDATADIR%/[rest of path] shows in the bottom left corner
4.  File is not existent in the specified directory.  
5.  Change %SCIRUNDATADIR% path.  
6.  Save network to same directory
7.  network now in specific directory.
