### ISSUE TITLE
Python API functions in InterfaceWithPython

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1321]
When running InterfaceWithPython, some of the SCIRun Python API functions behave badly.  There is not much practical purposes for most of the API functions, but this is more for user stability.  Commands that have problems are mostly expected:

scirun_add/remove_module - crashes SCIRun
scirun_execute_all - hangs scirun (infinite loop)
scirun_load_network - crashes SCIRun 
scirun_force_quit - crashes SCIRun instead of quitting

**Comment by dcwhite** [comment]
The only one I've seen is quit not behaving well. Are the rest consistent? If so, provide test networks/scripts.

**Comment by jessdtate** [comment]
scirun_load_network is consistent.  In a new network, add an InterfaceWithPython module.  add the command to module code with any network and it will crash with a segmentation fault.

**Comment by jessdtate** [comment]
similar for scirun_execute_all.  a new network with just InterfaceWithPython and only the line: scirun_execute_all()  will never start/finish executing.  I guess hanging is not the best description, but it prevents most functions in the GUI.

**Comment by jessdtate** [comment]
The add/remove module crash has to do with the module connections.  
The scirun_add_module function only crashes when there is an output set to the InterfaceWithPython module.  
The scirun_remove_module crashes when the module is connected to another module (only with the input though).  This seems to crash in the python console too.  

there is an example in my directory on the server: /home/sci/jess/SCIRun_5_nets/API_test_add_module.srn5.

**Comment by dcwhite** [comment]
Thanks a lot. I might decide to just restrict the available api functions within IWP to those that actually work.

**Comment by jessdtate** [comment]
That's fine.  There isn't any real utility for most of the API in the IWP.
