### ISSUE TITLE
cleanup regression network tikhonovTest.srn5

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1326]
In src/ExampleNets/regression/tikhonovTest.srn5, ReadMatrix:2 uses FwdInvToolkit/Data/tikhonov_inv/for_mat_128.mat as input, while the other matrices come from SCIRunTestData/Matrices/tikhonov. Input sources should consistent, and output should be rechecked.

**Comment by jcollfont** [comment]
Done. Now all the data matrices and the field come from %SCIRUNDATADIR%/ToolKits/FwdInvToolbox/tikhonov_inv/

Also included an output to the inverse regularization matrix, a plot on the heart geometry and added noise to the input

**Comment by dcwhite** [comment]
Looks good, thanks.
