### ISSUE TITLE
clipping plane using absolute space

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1329]
Clipping plane function should clip based on the bounding box of all the objects, which allows for the clipping of all objects in the scene based on the center.  

Currently, the clipping seems to be absolute, meaning that the planes will be centered around the origin.  An object which is off the origin by more than one, it will not be within the range of the clipping plane parameters.

**Comment by dcwhite** [comment]
As per https://github.com/SCIInstitute/SCIRun/pull/1332#issuecomment-201068834
