### ISSUE TITLE
No interface from Python to IO modules file type drop down

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1331]
This makes it impossible to tell SCIRun to do IO of a specific file type. ReadField remembers last selected option, so you can manually set it and call your network. WriteField has no memory of the drop down, so if you call a network from python, it will always save it as a binary .fld

**Comment by dcwhite** [comment]
This is a bit unwieldy. There's a state string that's settable, but it should be easier to use.

**Comment by gduffley** [comment]
If the state string became a "StateVariableName" accessible from python, the problem would be solved
