### ISSUE TITLE
clipping plane problem with some tet meshes

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1343]
Some tetmeshes are not clipping the faces, though the edges are clipping.  Here is an example screen shot.  not all types of tetmeshes have this problem, but it seems pretty consistent with those generated from tetgen.  There is an example network on the sci server: /home/sci/jess/SCIRun_5_nets/clippingtets.srn5 (and clippingtets_2.srn5)

![viewscene_2016 02 29 173422 475_1](https://cloud.githubusercontent.com/assets/3484631/13413858/08d0f820-df0b-11e5-9452-d7892f6de566.png)

**Comment by dcwhite** [comment]
@jessdtate will test this one again.

**Comment by jessdtate** [comment]
This seems to be working for me now.  Thanks.
