### ISSUE TITLE
interfacewithpython ports

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1345]
the ports on iwp have problems when ports are deleted and reattached.  The port names are changed, and therefore the input variables are changed.  sometimes it messes up (deletes and doesn't reassign names) the inputs that do not get deleted and reattached.

**Comment by dcwhite** [comment]
Such is the nature of the (simplistic) dynamic port implementation. But clearly this is annoying with respect to variable naming. I'll need to think about this one.

**Comment by dcwhite** [comment]
Actually, this is also a bug in the PyPorts class. It doesn't keep in sync with dynamic port adding/removing. Fix forthcoming.
