### ISSUE TITLE
CreateStandardColorMap improvements, part 1: Add all remaining v4 ColorMaps

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1348]
See #898. List of v4 colormaps:
- [x] Gray
- [x] Old Rainbow
- [x] Lighthue
- [x] Don
- [ ] Dark Gray
- [x] Orange Tint
- [x] Green Tint
- [x] Blue Tint
- [ ] Pink,White,Blue
- [ ] Mixed Rainbow
- [ ] Gray2
- [x] Rainbow
- [x] Darkhue
- [x] Blackbody
- [x] BP Seismic
- [x] Red Tint
- [x] Yellow Tint
- [x] Cyan Tint
- [x] Purple Tint
- [x] Orange,Black,Lime
- [ ] Mixed GrayScale
- [ ] Gray3

**Comment by dcwhite** [comment]
Start by reading the source files src/Core/Datatypes/ColorMap.h and cc. Then read up on the `Strategy` and `Factory` design patterns.

**Comment by aylakhan** [comment]
@jessdtate, @kgillette, @gduffley, @ajanson - any colormaps needed for IBBM?

**Comment by jessdtate** [comment]
I don't think there are any more that we specifically need.

**Comment by dcwhite** [comment]
@jessdtate @Haydelj @RubioJr9 Let's have a race between the two interns to see who can code up more colormap functions in the next week. We can discuss tomorrow.

**Comment by dcwhite** [comment]
@Haydelj will do the orange ones.

**Comment by dcwhite** [comment]
@dcwhite needs to check out the old code and help with conversion process.
