### ISSUE TITLE
Insert*IntoBundle does not save input names in ui

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1352]
When using any of the insert*intoBundle, once the inputs are hooked up and the names assigned, if the network is saved back out and reloaded, the names of the input fields/strings/matrices are missing from the UI.  It appears that the names are ignored anyway, even if the are showing in the UI at the time of execute.

**Comment by jessdtate** [comment]
There is an example net: /home/sci/jess/SCIRun_5_nets/test_bundle_input.srn5.  Not that the names will be saved.

**Comment by dcwhite** [comment]
These modules were converted a bit too hastily. I'll work on this today (need a break from python/matlab/field madness...).
