### ISSUE TITLE
bash scripting crashes

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1353]
When trying to run a bash script, SCIRun crashes.  and example shows this in the SCIRun-Exchange/Defibrillation_Evaluation/.  the network defib_simulation_evaluation.srn5  crashes when run by Run_Defib_Sim_sr5.sh, but when the -E flag is removed, there is no crash when I hit execute all manually.

Also, when SCIRun is called by setting the PATH env variable, the shader folder is not found, as it looks in the current directory instead of the scirun bin.  there are loads of these types of errors:
Failed to open file /Users/jess/software/SCIRun-Exchange/Defibrillation_Evaluation/Shaders/ColorMap.vs
The visualization will not work when this happens.

**Comment by dcwhite** [comment]
@wgood Is this the same crash you're getting?

**Comment by dcwhite** [comment]
@cbrightsci Looks like the "standard" renderer crash.

**Comment by jessdtate** [comment]
Yeah that solves it.  Now I remember.  I made that issue before.

**Comment by dcwhite** [comment]
@jessdtate Can you test this with the latest, for like the umpteenth time? thanks

**Comment by jessdtate** [comment]
This particular crash appears to be resolved on Mac
