### ISSUE TITLE
Test #1300 for pertinent field/mesh types

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1357]
We definitely need more complete testing of #1300. I have unit tests for LatVol, TetVol, and TriSurf, with various bases.

**Comment by jessdtate** [comment]
In addition to the three mentioned above.  We also use pointcloud, Quadsurf and hexvol meshes quite a bit.  Some less frequently used, but still important meshes are image meshes, curvemeshes (stream lines).  I sometimes use prismvol meshes.  The rest (structquadsurfmesh, scanlinemesh, structurecurvemesh) i don't know if I've ever used.

**Comment by jessdtate** [comment]
What I have seen working so far:  trisurf, tetvol, latvol.  
I will test more this week.

**Comment by dcwhite** [comment]
@jessdtate Let's try to close this one by tomorrow.

**Comment by jessdtate** [comment]
ok.  I'll test out some more today and tomorrow.

**Comment by jessdtate** [comment]
quadsurf and hexvol are working.

**Comment by dcwhite** [comment]
Can this be closed then?

**Comment by jessdtate** [comment]
A couple more test:
curvemesh works with data on the node, but not with data on the edges.
imagemeshes works with data on the faces and not on the nodes.  

The rest of the mesh types are much more rare.

**Comment by jessdtate** [comment]
here are some test meshes for the last two:
[test_curve_elem.mat.zip](https://github.com/SCIInstitute/SCIRun/files/269232/test_curve_elem.mat.zip)
[test_imageMesh.mat.zip](https://github.com/SCIInstitute/SCIRun/files/269233/test_imageMesh.mat.zip)

**Comment by dcwhite** [comment]
Thanks. Can you attach a couple .fld files for me to debug with?

**Comment by dcwhite** [comment]
Boom! Great minds think alike...

**Comment by dcwhite** [comment]
Can you send me .FLD versions of these two buggy meshes?

**Comment by jessdtate** [comment]
[test_image_node.fld.zip](https://github.com/SCIInstitute/SCIRun/files/275406/test_image_node.fld.zip)
[test_curve_elem.fld.zip](https://github.com/SCIInstitute/SCIRun/files/275407/test_curve_elem.fld.zip)
