### ISSUE TITLE
new ViewScene features & clipping plane performance

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1368]
Scale Bar
- [x] I was wondering if you change Length, Height and Num Ticks, should it change the scaling of the visualization or is it supposed to be independent of it 
- [x] GUI items: Unit, Multiplier and Line Width not functioning

Clipping
- [ ] pulling the UI sliders (X: ,Y: ,Z:, D:) is really slow and my machine is paging since SCIRun is taking up 30GB of RAM visualizing a 18 MB mesh

**Comment by moritzdannhauer** [comment]
The issue of using a clipping plane (huge memory allocation) is not resolved and unfortunately requested while I was demo'ing SCIRun5. Is it possible to give this a higher priority of being fixed?

**Comment by dcwhite** [comment]
It will probably be next year, if we get more graphics developer time.

**Comment by dcwhite** [comment]
@jessdtate @Haydelj I'll start this by trying to fix the bugs showing up in Debug mode related to clipping planes. That will point me to the memory usage. But it will also be waiting on the SRInterface refactoring.

**Comment by dcwhite** [comment]
After #.... is merged, I'll debug this again.
