### ISSUE TITLE
Add complex number support to BuildFEMatrix 

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1374]
Inputs will be the same. A new complex matrix output port is needed. If the input field has complex values, a complex matrix will be output; otherwise, a real matrix is output like before. 

To do list:
- [x] Add port to module.
- [x] In algorithm classes, figure out where non-generic code ends and generic code begins. The latter then needs to be templatized on the numeric type. 
- [x] Depending on link dependencies, we might not need to put all the template implementation in the header file, which would be nice. Needs a test.
- [x] Results should be same in the real case. We'll need some complex test cases.

Requires #1370 and #1371.

**Comment by dcwhite** [comment]
@moritzdannhauer Do you have a complex input field (in the form of field file + real matrix data + imaginary matrix data) I could use as an initial test case? Not too big please...

**Comment by moritzdannhauer** [comment]
I need to do a literature search to give you something meaningful. 
Can you do start with an artificial example?

**Comment by dcwhite** [comment]
OK. I have no problem coming up with the most artificial examples.

**Comment by dcwhite** [comment]
Basic real results look the same (tested with one of the unit test tetvols). I'll concoct a complex example, and make sure it doesn't crash.

**Comment by dcwhite** [comment]
@jessdtate @moritzdannhauer Can both of you guys check out branch complexFE and give this a test? You can start with https://github.com/SCIInstitute/SCIRun/blob/complexFE/src/ExampleNets/regression/complexFE1.srn5 as a basis.
