### ISSUE TITLE
adding script inputs from the command line.  

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1375]
SCIRun 4 allowed the script inputs (environment variables) to be set in the SCIRun call, like this:
scirun network.srn -E +VARNAME=filename

This would set the environment variable VARNAME to filename for the scirun session.

**Comment by jessdtate** [comment]
this is a lower priority because there are other ways to achieve this.

**Comment by dcwhite** [comment]
@jessdtate Can you just use bash itself to do this, like 
`VARNAME=filename scirun network.srn -E`
?

**Comment by jessdtate** [comment]
You can use bash to do this.  It is just setting the environment variables to the string for the filename.  This works in scirun5 and 4:
    export VARNAME=filename
    scirun -E network.srn5 


It would be that we decide that this is good enough, since we now have the python console too.

**Comment by dcwhite** [comment]
Closed by @jessdtate
