### ISSUE TITLE
Investigate Tetgen license issues

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1386]
:heart: GPL...

**Comment by dcwhite** [comment]
@lizutah Any official updates? I heard an unofficial one from @aylakhan.

**Comment by aylakhan** [comment]
@lizutah - updates?

**Comment by dcwhite** [comment]
@aylakhan provided an update last week. :moneybag: :confused: :boom:

**Comment by dcwhite** [comment]
We seem to have a stable, if unwieldy, solution for this.
