### ISSUE TITLE
Prefered_Input/Output_FileFormats

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1390]
Problem: 
I never use SCIRun format *.mat which coincidently has the same *.mat extension (many SCIRun users may use the Matlab format) in readfield/readmatrix. The default is the SCIRun format though and I always have to change the right extension. I would save about 50 annoying clicks per day if that would not be the case.

Request:
It would be very elegant if the IO reader can figure out what file format (if there are ambiguous extensions) a file is in. If there there is no ambiguity it should be pretty clear on how to read it in.
When you open a *.mat file in SCIRun4 it tells you what (Fields, Matrices) are inside and if a file is not Matlab it throws an error. Could not such a mechanism be used to test out which format a file is in?
If you tell me where to look for I can give it a shot.

If that it too complicated, a Preferences option is needed.

**Comment by dcwhite** [comment]
The file type list code is already pretty generic, and the first item is always the default format. For legacy reasons, we should not change the default format to Matlab. I also don't want to implement any pre-reading code to figure out the right format, that will get expensive and messy.

I just thought of a cool solution: be able to specify certain script actions and have those saved to preferences. In your case, it would be the following python/pseudocode:
```
POST_MODULE_ADD
if (module_id contains "ReadMatrix")
  set_module_state("FileType", "Matlab Matrix")
```
while would run every time right after you add the module to the network. Thus when you click the GUI, the file type option is already changed, and no underlying code is affected. This is general way for a user to customize his/her default values for a module! And it should not be hard to implement, but will take longer. I can still try to get it into this milestone.

**Comment by moritzdannhauer** [comment]
That would be fantastic!!! That would be controllable by the Preferences-GUI as well no just via Python?

**Comment by dcwhite** [comment]
Yes, I would make a GUI for these.

**Comment by dcwhite** [comment]
This will do the trick now:
```
scirun_set_module_state(scirun_module_ids()[-1], 'FileTypeName', 'Matlab Matrix (*.mat)') if scirun_module_ids()[-1].startswith('ReadMatrix') else 'not ReadMatrix'
```

**Comment by dcwhite** [comment]
https://www.dropbox.com/s/obx0qwijrseel6i/Screenshot%202016-04-15%2010.20.21.png?dl=0
