### ISSUE TITLE
viewscene hanging on re-execution

### ISSUE THREAD

**Issue by lizutah** [SCIInstitute/SCIRun#1391]
Daria has a network that demonstrates this...  on reexecution, stalls on the viewscene.  Runs again after exiting and restarting.

**Comment by dcwhite** [comment]
Which build does this happen on (specifically, does ViewScene have its matrix output ports enabled)? Can the network be uploaded here?

**Comment by dcwhite** [comment]
Still an issue?

**Comment by dcwhite** [comment]
Duplicate
