### ISSUE TITLE
RegisterWithCorrespondences crashes with volumetric data

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1394]
Module only works with trisurfs, crashes with volume data. The module should output a transform matrix for linear registrations as well.

**Comment by dcwhite** [comment]
Please provide a test network and data to replicate the crash.

**Comment by dcwhite** [comment]
Is the second sentence a new feature, or a missing part of the original module?

**Comment by aylakhan** [comment]
@gduffley: reminder that we need a test network and data

**Comment by dcwhite** [comment]
@gduffley Any updates on this one?

**Comment by gduffley** [comment]
@dcwhite It still crashes and it doesn't output a matrix. This is not a module I use for research, but they ability to use volume data and output a matrix seems like obvious features the module should be able to handle

**Comment by jessdtate** [comment]
@gduffley is the volume data that you are testing a structured mesh?  any example data.

**Comment by gduffley** [comment]
iirc it was any latvol. I'm not sure about other volumetric meshes

**Comment by jessdtate** [comment]
because of the potential to morph the mesh, structured meshes, such as latvol, have been precluded from the module.  The way that it is implemented, it wouldn't allow implementing structured data for the linear transformations without a major rewrite.  I have added an error check that is hopefully more helpful.  The workaround is to use ConvertMeshToUnstructuredMesh.

**Comment by jessdtate** [comment]
As alternative to using ConvertMeshToUnstructuredMesh, the new matrix port with the transform will also help.  The transform can be applied to a latvol if another mesh is used as the input.

**Comment by jessdtate** [comment]
It may be possible to refactor the module code to be more similar to TransformMeshWithTransform for the linear transform options.  Perhaps a new issue for that?

**Comment by gduffley** [comment]
The module could do the conversion automatically and output an unstructured mesh. I think any of these solutions are reasonable, and now that there is an error mesh it's fine. I reported it because you get a crash when there is no a priori reason to think the module wouldn't be compatible
