### ISSUE TITLE
ViewScene scale bar should be visible even if scene is empty

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1399]
And checkbox is enabled, of course. v4 has this behavior.

**Comment by dcwhite** [comment]
I also got a crash with this message but couldn't replicate it:
`Unhandled exception: Differing attributes`

**Comment by basisunus** [comment]
Fixed it on my branch add_viewscene. Pull request?

**Comment by dcwhite** [comment]
Go for it

**Comment by dcwhite** [comment]
Closed by https://github.com/SCIInstitute/SCIRun/pull/1405#issuecomment-213593975
