### ISSUE TITLE
Linux can't read .fld generated on Windows

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1401]
Reproduction steps:

1. Save a .fld from Windows
2. Load .fld on Linux

**Comment by aylakhan** [comment]
Is the field file binary or ascii?

**Comment by dcwhite** [comment]
He said it ASCII, which leads me to believe it's a line-ending issue.

**Comment by gduffley** [comment]
I have tried ASCII. Don't know if it happens with Binary

**Comment by aylakhan** [comment]
Binary worked for me, so it is probably a line-ending issue.

**Comment by aylakhan** [comment]
Needs regression and unit test.

**Comment by aylakhan** [comment]
Requires re-write of SCIRun field header processing.
