### ISSUE TITLE
Upgrade cleaver external library to Cleaver 2

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#1407]
Pending on Cleaver 2 bug fixes.

**Comment by moritzdannhauer** [comment]
I think we should discuss run-time / memory consumption of cleaver 1 and 2, especially since the
plan appears to be to replace cleaver 1 by cleaver 2 in SCIRun5.

**Comment by aylakhan** [comment]
Any Cleaver 2 testing needs to wait until bug fixes are in place.

**Comment by dcwhite** [comment]
@jonbronson @jessdtate Here's another one.

**Comment by dcwhite** [comment]
I'll make a new module for InterfaceWithCleaver2

**Comment by dcwhite** [comment]
Remaining tasks:
- [ ] Add sizing field port
- [ ] Add background field port
- [ ] Fix re-execution problem (applies to Cleaver1 too)
- [ ] Expose mesh type choice
