### ISSUE TITLE
add verbose levels to limit console output in headless mode

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#1410]
example: SCIRun -s script or SCIRun -s script --verbose 0
no output
example: SCIRun -s script --verbose 1-3
differing levels of output
 (just examples, can be implemented differently)

**Comment by dcwhite** [comment]
If `--verbose` is not passed in, I just shut off all module logging in headless mode. If there is still too much global/network logging (there shouldn't be much left), make a new issue with the specific "kill this log message" request.
