### ISSUE TITLE
deleting/renaming subnets

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1411]
The renaming subnetworks function requires a double click in os x.  This of course adds the subnetwork.  which makes it hard to notice that the name is editable.  

we also need a function to delete subnetworks once they have been created.

**Comment by dcwhite** [comment]
Note: on OSX 10.8, this feature has this bug: http://www.qtcentre.org/archive/index.php/t-53881.html. 10.9+ does not have this problem.
