### ISSUE TITLE
colormap interpolation on faces

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1415]
### Description

This issue isn't as noticeable unless you have course meshes with high variation of data, so it isn't urgent.

The problem is that the interpolation of the color along the edges and faces of a mesh is blends the color on the nodes instead of interpolating with the color map, as shown with the included comparisons between scirun4 and scirun5.  It should look like it does in scirun4.  The main problem is that when the extreme colors of the colormap blend, they often create a new color that isn't in the colormap, or is the wrong place in the colormap.  Also, it can make the color visualization of a linear distribution look vastly different depending on the resolution of mesh.  

**Expected behavior:**
scirun4:
![sr4_colormap_mapping](https://cloud.githubusercontent.com/assets/3484631/15082100/2a67c5e8-1383-11e6-8b5a-734a3f0c3b92.png)

**Actual behavior:**
scirun5:
![sr5_colormap_mapping](https://cloud.githubusercontent.com/assets/3484631/15082101/2a7b3d62-1383-11e6-8b73-10f5ec9d1514.png)
### Steps to Reproduce

Have a field with data on the nodes with data on adjacent nodes on the opposite ends of the colormap.  
Visualize the data with a colormap set appropriately.  The effect is the same for most colormaps.  

Here is an example network:

[colormap_mapping.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/252990/colormap_mapping.srn5.zip)
### Versions

v5.0-alpha.AD-72-gb66adfa 
OS X 10.10

**Comment by dcwhite** [comment]
:+1: for well-crafted issue!

**Comment by jessdtate** [comment]
A related problem is the reduction in resolution of the the colormap.  In SCIRun 4 this creates bands of color with clear boundaries.  Currently in 5, the values are still linearly interpolated over the surface, so there are never clean lines, even with high resolution.

**Comment by Haydelj** [comment]
This was fixed as part of the showField(Glyphs) refactor

**Comment by dcwhite** [comment]
@jessdtate Need some example networks for closing this one

**Comment by dcwhite** [comment]
Forgot to run the original network at the top. Here is what the output looks like now:
![colorGradient](https://user-images.githubusercontent.com/1399383/70274374-4aabcf00-1769-11ea-977b-ee7a3aceb831.png)

@jessdtate Close?
