### ISSUE TITLE
BuildMappingMatrix output is wrong

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1416]
### Description

The BuildMappingMatrix produces bad results. it seems only the interpolated data setting is the only one that gives bad results.  The data is jumbled, as if the nodes of one of the fields is getting mixed up.  

sample networks:

[Build_mapping_bug.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/252995/Build_mapping_bug.srn5.zip)
[build_mapping_sandbox.srn.zip](https://github.com/SCIInstitute/SCIRun/files/252994/build_mapping_sandbox.srn.zip)
[Build_mapping_bug_II.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/253028/Build_mapping_bug_II.srn5.zip)
[build_mapping_sandbox_II.srn.zip](https://github.com/SCIInstitute/SCIRun/files/253029/build_mapping_sandbox_II.srn.zip)

### Steps to Reproduce

This bug is more apparent when the source data is more sparse than the destination data.  The prodived example creates a coarse source compared to the destination of an impulse function.  Build_mapping_bug_II.srn5 allows for adjusting the size of the source by changing the size of the first CreateLatVol module.  

Using the example networks, the different settings can be tested.  The output of the BuildMappingMatrix should be the same as the SCIRun4 version.  The Applied mapping should also be Identical to MapFieldDataFromSourceToDestination.  In the network, there is a calculateFieldData that finds the difference between the fields, which should be 0.  

**Expected behavior:** [What you expected to happen]
![viewscene_2016 05 05 162836 553_2](https://cloud.githubusercontent.com/assets/3484631/15085378/2dacd612-1397-11e6-8508-49b25bb0749c.png)
![viewscene_2016 05 05 170148 406_2](https://cloud.githubusercontent.com/assets/3484631/15085385/3ef17752-1397-11e6-81e6-a5c8030c2ae8.png)
![sr5_mapfromsourcetodest](https://cloud.githubusercontent.com/assets/3484631/15085400/54630e3e-1397-11e6-93f8-43a53d8102c4.png)

**Actual behavior:** [What actually happened]
![viewscene_2016 05 05 162829 488_1](https://cloud.githubusercontent.com/assets/3484631/15085379/31aeff24-1397-11e6-95be-c790d55bae4c.png)
![viewscene_2016 05 05 170140 907_1](https://cloud.githubusercontent.com/assets/3484631/15085389/462c4150-1397-11e6-942e-9cb748eced07.png)
![sr5_build_mapping_matrix](https://cloud.githubusercontent.com/assets/3484631/15085410/63bf75e8-1397-11e6-8af9-1d5d205f8a6a.png)

### Versions
v5.0-alpha.AD-72-gb66adfa 
OS X 10.10

**Comment by dcwhite** [comment]
@jessdtate I have determined this is a randomly occurring bug, due to the algorithm's multithreaded nature. Can you try running your network a bunch of times and seeing how often it fails? Also, how many cores on the machine you're using?

**Comment by jessdtate** [comment]
I know I get the same result when I run it multiple times. I have never had it work properly in sr5. I ran it on a 2 core machine and an i5 and got the same results.  I can try on gus.

**Comment by jessdtate** [comment]
Here is a network with just the bad results visualized
[Build_mapping_bug_III.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/258288/Build_mapping_bug_III.srn5.zip)

**Comment by dcwhite** [comment]
Can you provide the SCIRun 4 version as well?

**Comment by dcwhite** [comment]
Never mind :8ball:
