### ISSUE TITLE
Insert Module: Dynamic Port Not Connecting

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1420]
When attempting to insert a module between two connected modules via the "Insert Module" option (double click the pipe), the output port of the new module does not connect to the downstream module if the downstream module accepts dynamic ports.

Case 1: Expected Behavior -- Insert Module works properly
ReadField ---> ReportFieldInfo
ReadField ---> GetFieldBoundary ---> ReportFieldInfo
     -- Note: ReportFieldInfo input ports are static

Case 2 Actual Behavior under conditions of downstream dynamic ports-- Insert Module does not work properly
ReadField ---> CalculateFieldData
ReadField ---> GetFieldBoundary --x-- CalculateFieldData
     -- Note: CalculateFieldData input ports are dynamic

v5.0-alpha.AD-69-gf7e44a0

**Comment by dcwhite** [comment]
@zaracay I get a crash when using Insert Module with a module with dynamic ports. Does your build not crash? There are many broken assumptions in the port/connection removal code, so this might be a bit of a lengthy fix.

**Comment by dcwhite** [comment]
OK I'll work on this one soon.
