### ISSUE TITLE
Module GUI size examples/discussion

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1424]
Use this issue to post screenshots of desired module sizing, along with the size adjustment values in the dev console UI.

**Comment by dcwhite** [comment]
@jessdtate @ajanson @gduffley covers all three OSes.

**Comment by gduffley** [comment]
![screen shot 2016-05-13 at 12 24 29 pm](https://cloud.githubusercontent.com/assets/5941547/15259230/3d66c632-190d-11e6-8225-4b7ac536bdde.png)

**Comment by dcwhite** [comment]
Thanks!

**Comment by jessdtate** [comment]
here's mine finally, -30, -70
![module_size](https://cloud.githubusercontent.com/assets/3484631/15725403/f1d443a6-2808-11e6-8bec-4c9da0d78025.png)

**Comment by jessdtate** [comment]
I have a 15 inch, 1440 x 900

**Comment by dcwhite** [comment]
Idea: detect available screen size and adjust module size accordingly.
http://stackoverflow.com/questions/18975734/how-do-i-get-the-screen-size-of-desktop-where-i-am-running-my-qt-application
