### ISSUE TITLE
SCIRun 4 network import, part 3: List of modules that don't port properly

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1429]
### Description

The following are modules that have been ported into SCIRun 5 (or their equivalent) that do convert when importing 4.x SCIRun network.  New findings or a description of a different location of these modules can be listed in the comments below.  The bold text is the name of the SCIRun 4 module(s), the text below contains the associated name of the SCIRun 5 module(s)

**ReportFieldInfo:**
Input linking is correct but output ports do not match (see issue #1421)

**EvaluateLinAlgBinary
EvaluateLinAlgUnary 
EvaluateLinAlgGeneral**
Do not load - 
Should map to their respective pairing (EvaluateLinearAlgebraBinary, EvaluateLinearAlgebraBinary, EvaluateLinearAlgebraBinary)

**GetSubMatrix**
SCIRun 4 has both GetSubMatrix and SelectSubMatrix.  Both are essentially the same.  Both have options to set sub matrix selection based on input ports or GUI interface.  The GetSubMatrix input port (which requires a matrix) would be complicated to convert to the SelectSubMatrix input ports that are direct row and column indices, but the GUI interface mapping is very similar and could be mapped.

**ReportMatrixColumnMeasure
ReportMatrixRowMeasure**
SCIRun5 has ReportMatrixSliceMeasure which can handle both columns and rows.  The Column or Row measure modules in SCIRun 4 should be able to be used to set the default flags within the slice measure module.

**CalculateFieldData2
CalculateFieldData3
CalculateFieldData4
CalculateFieldData5**
CalculateFieldData in SCIRun5 has dynamic ports that don't map properly to the multip input port SCIRun4 modules

**Comment by dcwhite** [comment]
Needs updating. I added a few of these module rename mappings, but need to check which work.

**Comment by dcwhite** [comment]
Ditto

**Comment by jessdtate** [comment]
The ones I have problems with in my networks are the CalculateFieldData* and ReportMatrix*Measure.

**Comment by jessdtate** [comment]
[connection_tester.srn.zip](https://github.com/SCIInstitute/SCIRun/files/6093064/connection_tester.srn.zip)

A test network with all the modules mentioned.

**Comment by dcwhite** [comment]
These mappings are all working now except for EvalLinAlgGeneral, which is unconverted (#940). I'm going to close this one.
