### ISSUE TITLE
Can not change the name of saved subnetworks via clipboard on windows

### ISSUE THREAD

**Issue by SeyhmusGuler** [SCIInstitute/SCIRun#1430]
On windows, I can't change the name of the subnetworks i saved by giving a 'star' in the clipboard history. Also, when I drag the mouse on top of these saved subnetworks, a window with a lot of details about the modules in that subnetwork pops-up.

**Comment by dcwhite** [comment]
I'm going to change the GUI for those in #1423. Are you trying to rename the starred item under Clipboard history, or the newly-created item under Saved Subnetworks? There is a (not-too-obvious) push button to rename the latter.

**Comment by dcwhite** [comment]
@SeyhmusGuler Please test this again with the latest. There is a new GUI for it.

**Comment by SeyhmusGuler** [comment]
Sounds good. I will try it again.

**Comment by SeyhmusGuler** [comment]
I am now able to rename a saved subnetwork by right click - rename option on windows.
