### ISSUE TITLE
ViewScene needs to display axis

### ISSUE THREAD

**Issue by lizutah** [SCIInstitute/SCIRun#1435]
request by @ajanson.

**Comment by dcwhite** [comment]
@ajanson provide a screenshot of desired behavior.

**Comment by aylakhan** [comment]
@ajanson - update?

**Comment by ajanson** [comment]
Sorry. I never noticed this was assigned back to me. SCIRun 4 has the option to turn on an orientation axis at the origin of the viewscene. I would like this in SCIRun 5 as well.

![image](https://cloud.githubusercontent.com/assets/8622681/16166991/742de6d0-34ad-11e6-8cd4-932f4c2d8f57.png)

**Comment by dcwhite** [comment]
Thanks.

**Comment by dcwhite** [comment]
This one needs to be after "red viewscene" is fixed.
