### ISSUE TITLE
add knowns to linear system

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1438]
### Description

AddknownsToLinearSystem has a check in it for symmetric matrices.  However, this module should be able to be used with BuildSurfaceLaplacianMatrix, which does not generate symmetric matrices.  Therefore, addknownstoLinearSystem should also handle assymetric matrices.  There is a check in the code for symmetry, so the earlier decision include only symmetric matrices needs to be revisited.

### Steps to Reproduce

1. create or load a surface field.
2. use BuildSufaceLaplacianMatrix to build the laplacian matrix.
3. create boundary conditions on the mesh
4 add inputs to addknownstolinearsystem

**Expected behavior:** 

execute the module without throwing errors.

**Actual behavior:** 

gives an error because of a check for symmetry.

### Versions

SCIRun version: v5.0-alpha.AD-151-gb385347
OS X 10.8

**Comment by dcwhite** [comment]
Talk to @moritzdannhauer about this one. Here's the pertinent commit history for the AKTLS algo file: https://github.com/SCIInstitute/SCIRun/commits/master/src/Core/Algorithms/Math/AddKnownsToLinearSystem.cc

**Comment by moritzdannhauer** [comment]
Ok, lets just delete the symmetry check then.

**Comment by jessdtate** [comment]
is it just the check that needs to be removed, or does the code need to be changed to work with assymetry?

**Comment by moritzdannhauer** [comment]
It should not, lets remove it and find out!

**Comment by dcwhite** [comment]
@jessdtate You should make the change, run tests, and make a PR. Let me know if you need code help.

**Comment by jessdtate** [comment]
OK.  I'll do that.

**Comment by aylakhan** [comment]
@jessdtate - needed for IBBM?

**Comment by jessdtate** [comment]
not essential, but I'd like to have it done before then.

**Comment by dcwhite** [comment]
@jessdtate Update?

**Comment by jessdtate** [comment]
Is a PR tonight too late?

**Comment by dcwhite** [comment]
I can extend the deadline to 10 pm tonight.

**Comment by dcwhite** [comment]
Closed by #1502
