### ISSUE TITLE
Network workspace area is showing a highlighted blue box that is preventing me from clicking on pipes

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1441]
### Description
The workspace places a blue highlighted region around all the modules in my network.

### Steps to Reproduce

1. Open network with some modules and pipes
2. Start clicking on modules or pipes in the network
3. Giant blue box appears
4. Sometimes it prevents me from selecting pipes.

**Expected behavior:** Blue box should not be there.

**Actual behavior:** Blue box is there

### Versions

v5.0-alpha.AD-162-g9bd0adf

![image](https://cloud.githubusercontent.com/assets/8622681/15440259/c596e29c-1e91-11e6-8144-69268593334f.png)

**Comment by dcwhite** [comment]
That should have been fixed. I'll need the exact network file for this one. Attach here as a zip file.

**Comment by ajanson** [comment]
So it looks like that network got corrupted somehow. I saved and tried to reload it and I get this error.

![image](https://cloud.githubusercontent.com/assets/8622681/15441053/ee528e8a-1e95-11e6-8ed8-f6fd0b997995.png)

I am able to reproduce it with this network as well (It is not letting me upload a zip so I am slacking it to you.
Upon loading just click and drag a module.

**Comment by dcwhite** [comment]
Hadn't noticed this since I never moved any modules in old saved networks. This is due to the default tag value changing from 0 to -1. 0 is now a normal tag value, and will be drawn when the scene is updated. The immediate workaround is to remove the 0 tag from all your modules and resave, but that is tedious. I will come up with either a faster way to do this, or a backward-compatibility check. But it will have to wait until after my leave (I'm back 6/7).

**Comment by dcwhite** [comment]
Another workaround is to press Alt-Shift-G to remove the box, but then it keeps reappearing with every module move. I'll try to fix the reappearing problem today.

**Comment by dcwhite** [comment]
@ajanson Reply to https://github.com/SCIInstitute/SCIRun/issues/1441#issuecomment-220710682:

This is the hazard of using the absolute latest master, in between releases. We'll be cleaning up the branch system when we move to beta, but network files not being readable is a consequence of ongoing network file format work. Normally, I would keep such changes out of master until they're done, but am rushing a few things before I go.
