### ISSUE TITLE
SolveLinearSystem GUI missing "Use previous solution as initial guess" checkbox

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1442]
### Description

SCIRun 4 module had a checkbox for this, which was by default checked. This is missing in SCIRun 5 and I would like to uncheck it. If SCIRun 5 already has this option turned off by default then it is no problem.

### Steps to Reproduce

1. Open SolveLinearSystem module GUI
2. Attempt to uncheck the checkbox
3. Cannot uncheck because it is not there

**Expected behavior:** Checkbox is there to uncheck and I can uncheck it.

**Actual behavior:** Could not uncheck checkbox because checkbox is missing.

### Versions

v5.0-alpha.AD-162-g9bd0adf

![image](https://cloud.githubusercontent.com/assets/8622681/15440425/98a9ca82-1e92-11e6-844c-340b17384a8a.png)

![image](https://cloud.githubusercontent.com/assets/8622681/15440436/a80592a4-1e92-11e6-9180-03cf42551788.png)

**Comment by dcwhite** [comment]
All the partial solution stuff is not implemented yet. I'm pretty sure v5 is behaving as if it's not checked, but I will make sure.

**Comment by dcwhite** [comment]
Verified v5 solver does not use any previous solutions as guesses, and always uses the zero vector as the initial guess. Closing this issue. If you want other options for initial solver guesses, make a new issue.
