### ISSUE TITLE
incorrect render of cylinder edge glyphs for streamlines

### ISSUE THREAD

**Issue by behollis** [SCIInstitute/SCIRun#1445]
[Pic](http://www.sci.utah.edu/~behollis/scirun5/cylinder-render-scirun5.png) of problem with network.

System:
Ubuntu 15.10
GeForce GTX Titan X

**Comment by cbrightsci** [comment]
@behollis Please attach a link to the network and any data needed by the networks.

**Comment by cbrightsci** [comment]
@behollis If you could give me an actual network that manifests this bug that would be wonderful. That way I can work with the network and debug through it. If any other files are needed for the network please provide those as well.

**Comment by behollis** [comment]
here are the needed files (modified from distribution) to reproduce:

1. [network](http://www.sci.utah.edu/~behollis/scirun5/streamline.srn5)
2. [bdl](http://www.sci.utah.edu/~behollis/scirun5/Defib_simulation_results.bdl)

**Comment by behollis** [comment]
Has this problem been verified yet?

**Comment by dcwhite** [comment]
@jessdtate is investigating

**Comment by dcwhite** [comment]
Duplicate of #1815 
Close this one when PR is merged
