### ISSUE TITLE
Cannot use multiple SinglePointProbe Widgets in ViewScene. Moving one, moves the other.

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1448]
### Description

Adding a second GenerateSinglePointProbeFromField widget does not behave correctly. Moving one moves the other as well, and vice versa. 

### Steps to Reproduce

1. Add 2 GenerateSinglePointProbeFromField widgets to the ViewScene
2. Shift+Click/Drag one and the other moves as well.

**Expected behavior:** Each point probe moves independently

**Actual behavior:** They move together

### Versions

v5.0-alpha.AE

**Comment by dcwhite** [comment]
I've got a fix coming for this. The module didn't check whether it was its own widget that had moved, so the move transform was applied to any instance.
