### ISSUE TITLE
No TetVolField importer

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1451]
There is no TetVolField importer in the ReadField module that can be used to import meshes in the form of .elem or .pts.

**Comment by dcwhite** [comment]
@kgillette Please attach a zip file of your tetvol input files so I can test the converted importer.

**Comment by kgillette** [comment]
Here you are. Let me know if you have any trouble downloading it. 

[meshwbath_e.elem.zip](https://github.com/SCIInstitute/SCIRun/files/314391/meshwbath_e.elem.zip)

**Comment by dcwhite** [comment]
Is there a .pts file to go with that?

**Comment by kgillette** [comment]
I think this is the entire mesh. The .pts file is in the new zip file. 

[meshwbath.zip](https://github.com/SCIInstitute/SCIRun/files/314524/meshwbath.zip)

**Comment by dcwhite** [comment]
Thanks. The importer can handle it now, and the field matches v4. However, the mesh is so large it's not all visible in v5 ViewScene. You'll need to make a new issue for @cbrightsci to increase the maximum size of the view space, again.
![viewscene_2016 06 14 112311 890_2](https://cloud.githubusercontent.com/assets/1399383/16052667/725677ce-3222-11e6-956c-a685b63221b4.png)

**Comment by kgillette** [comment]
Have you already pushed it?

**Comment by dcwhite** [comment]
Nope, still on work branch. Wait until issue is closed ☺️
