### ISSUE TITLE
Crash error with ViewScene

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1452]
The ViewScene module crashes after I press Autoview in the following network (see image below). I tried the same network in SCIRun 4 and it works. 

![screen shot 2016-06-13 at 12 47 23 pm](https://cloud.githubusercontent.com/assets/12956701/16022522/7c590a1e-3175-11e6-8e6c-77c98746f4eb.png)

**Comment by dcwhite** [comment]
Don't use the red ViewScenes. They "bug out" 5-10% of the time. Known bug.

Are all your ViewScenes always going red? That is a new issue.

**Comment by kgillette** [comment]
It isn't red until I hit the AutoView. A lot of my view scenes have been messing up, but I thought it was just my data until I checked in in SCIRun 4.

**Comment by dcwhite** [comment]
Are the coordinate axes showing in the ViewScene dialog? If not, it doesn't matter what you're pressing, the VS just fails.

**Comment by kgillette** [comment]
They aren't showing. Is that apart of another known error?

**Comment by dcwhite** [comment]
Nope, same error. The question is does this happen with every ViewScene, every time, or is it random?

**Comment by kgillette** [comment]
I am not sure, but it seems to happen to me a lot. I'll start recording every time that it happens.
