### ISSUE TITLE
Increase maximum space of the ViewScene 

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1454]
@cbrightsci 

Need to increase the maximum space of the ViewScene module. 

![](https://cloud.githubusercontent.com/assets/1399383/16052667/725677ce-3222-11e6-956c-a685b63221b4.png)

**Comment by dcwhite** [comment]
Code to load the mesh is coming to master soon :)

**Comment by cbrightsci** [comment]
Look forward to it.

**Comment by kgillette** [comment]
NEED FOR IBBM 2016

**Comment by jessdtate** [comment]
fixed in #1888

**Comment by dcwhite** [comment]
I'll reopen and test this one after #1888's bugs are fixed.

**Comment by dcwhite** [comment]
![works](https://user-images.githubusercontent.com/1399383/57888539-af183880-77ef-11e9-821f-a0498c3fa567.png)
