### ISSUE TITLE
Isosurface Single tab does not work immediately and forgets tab when network reloaded

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1458]
### Description

When first using ExtractSimpleIsosurfacce the default tab is Single and the module does not create an isosurface until you run a different tab successfully and then switch back. The module does not remember the current tab and switches back to Single when the network is saved and reloaded (not sure this always happens). 

### Steps to Reproduce

1. Load new ExtractSimpleIsosurface
2. Execute module on appropriate data
3. Switch to Quantity tab and set it to some number greater than 1.
4. Execute and it should create appropriate isosurfaces
5. Switch back to SIngle tab and set an appropriate isosurface value.
6. It should create an appropriate isosurface.

**Expected behavior:** It should work right.

**Actual behavior:** It does not work right.

### Versions

Not at desktop right now but this has existed in all versions including latest build

**Comment by dcwhite** [comment]
Thought I fixed this, I'll verify.
