### ISSUE TITLE
Make stub pages for modules with missing wiki pages

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1461]
### Brand new modules
- [x] InterfaceWithPython
- [x] ConvertMatrixToScalar
- [x] ConvertRealToComplexMatrix
- [x] ConvertScalarToMatrix
- [x] ComputePCA
- [x] CreateComplexMatrix
- [x] ReportComplexMatrixInfo
- [x] CalculateNodeLocationFrequency
- [x] InterfaceWithCleaver
- [x] PythonObjectForwarder
- [x] NetworkNotes
- [x] PrintDatatype

### Should point to Brain Stim help page
- [x] SetupTDCS
- [x] GenerateROIStat
- [x] SetConductivitiesToMesh
- [x] RefineTetMeshLocally
- [x] ElectrodeCoilSetup

### Modules needing package/name redirect
- [x] MapFieldDataOntoElements
- [x] ChooseInput
- [x] ApplyFEWCurrentSOurce
- [x] ApplyFEMVoltageSource
- [x] EvaluateLInearAlgebraBinary
- [x] EvaluateLinearAlgebraUnary
- [x] GetMatrixSlice
- [x] ReportMatrixSliceMeasure
- [x] CreateStandrdColorMaps
- [x] ExportFieldsToMatlab
- [x] ImportFieldsFromMatlab
- [x] ExtractSimpleIsosurface

### Modules needing doc upgrade--different issue needed
- [ ] BuildSurfaceLaplacianMatrix

### Need to check status
- [x] ConvertMatrixToString

**Comment by wgood** [comment]
Here is the Missing Module Help List

-ElectrodeCoilSetup-
——No Help
-GenerateROIStat
——No Help
-SetConductivitiesToMesh
——No help
-SetupTDCS
——No Help 
-MapFieldDataOntoElements
——No Help 
-RefineTetMeshLocally
——No help 
-ConvertMatixToScalar
——No Help
ConvertMatrixToString
——No Help
-ConvertRealToCompleMatrix
—— No Help 
-ConvertScalarToMatrix
———No Help 
-ApplyFEWCurrentSOurce
——— No Help 
ApplyFEMVoltageSource
——— No Help 
ChooseInput 
—No Help 
BuildSurfaceLaplacianMatrix
—— Shitty Help — Doesn’t Count 
ComputePCA
——— No Help 
ComputeSVD
——— No Help 
CreateComplexMatrix
—— No Help 
EvaluateLInearAlgebraBinary
—— No Help 
EvaluateLinearAlgebraUnary
—— No Help 
GetMatrixSlice
——— No Help 
-ReportComplexMatrixInfo
—— No help 
ReportMatrixSliceMeasure
—— No help 
ExportFieldsToMAtlab
——— No Help 
ImportFieldsFromMatlab
—— No Help 
CalcualateNodeLcoationFrequncu
—— no Help
-ExtractSimpleIsosurface
——— No Help 
-InterfaceWithCleaver
—— no Help 
InterfaceWithPython
—— No Help 
PythonObjectForwarder
——— No Help 
NetworkNotes
—— No Help 
-PrintDatatype
———— No Help
-CreateStandrdColorMaps
——— No Help

**Comment by dcwhite** [comment]
Thanks!

**Comment by dcwhite** [comment]
I updated all the renamed modules' help urls, checked off above. I'll need a volunteer to create the new module stub pages.

**Comment by dcwhite** [comment]
@wgood To make new module help pages (top section above), fork https://github.com/SCIInstitute/scirun.pages, make a new branch, and start generating markdown pages. Talk to @aylakhan for assisntance.

**Comment by dcwhite** [comment]
Simplify this example, just with name and description section: http://scirundocwiki.sci.utah.edu/SCIRunDocs/index.php/CIBC:Documentation:SCIRun:Reference:SCIRun:ConvertMeshToUnstructuredMesh

**Comment by dcwhite** [comment]
http://sciinstitute.github.io/scirun.pages/

**Comment by dcwhite** [comment]
@wgood Any progress on this one?

**Comment by aylakhan** [comment]
See https://github.com/andycorb/scirun.pages. Andy should be making a pull request soon.

**Comment by dcwhite** [comment]
OK

**Comment by dcwhite** [comment]
<img width="969" alt="screenshot 2016-08-12 11 50 21" src="https://cloud.githubusercontent.com/assets/1399383/17631859/009bb7e0-6083-11e6-8a35-b05de9ca9c21.png">

**Comment by dcwhite** [comment]
@aylakhan Update on this issue? @andycorb's fork doesn't quite look done.

**Comment by aylakhan** [comment]
Stubs are done, list is updated. Documentation needs to be filled in for stubs, and updated with new port names, UI descriptions etc. for modules ported from SCIRun 4.

**Comment by dcwhite** [comment]
Could we update the html so it doesn't look so 1997?
