### ISSUE TITLE
ViewScene "AutoView" issues with GeneratePointProbe widget or single node rendered as sphere

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1463]
### Description

Clicking autoview with a single GenerateSinglePointProbeFrom field widget or a single node passed into showfield rendered as a sphere zooms in really far and seems to lock the viewscene until a different object is added and autoview is pressed again.
### Steps to Reproduce
1. Connect first port of GenerateSinglePointProbeFromField to viewscene
2. Click autoview in the viewscene
3. It zooms in really far and another object needs to be added to get back.

**Expected behavior:** It should zoom in only until the whole sphere is visible in the window

**Actual behavior:** Zooms in way too far
### Versions

v5.0-alpha.AF-1-g483d529

**Comment by dcwhite** [comment]
@ajanson This is still an issue, but could you attach a network that show the problem? I might be able to work on this one.

**Comment by ajanson** [comment]
[pointProbe_ViewScene.zip](https://github.com/SCIInstitute/SCIRun/files/1411243/pointProbe_ViewScene.zip)

**Comment by dcwhite** [comment]
I'll make a build with #1888 in it for @ajanson to test.
