### ISSUE TITLE
Highlight/Select all modules in network window added from Snippets, clipboard, and saved subnets

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1465]
### Description

If I double-click, or drag and drop a saved subnetwork it often adds these modules on top of other modules in the network window and I have to manually select all of those modules in order to move them to a new area. This would be much easier if they were all selected to begin with (also all pipes selected).

### Steps to Reproduce

1. Double-click to add saved subnetwork
2. Attempt to click and drag subnetwork somewhere else
3. Cannot because none of the modules are selected

**Expected behavior:** All added modules and pipes should be highlighted/selected

**Actual behavior:** Nothing is highlighted or selected

### Versions

v5.0-alpha.AF-1-g483d529

**Comment by dcwhite** [comment]
Good suggestion.
