### ISSUE TITLE
box widgets moving other widgets while hidden

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1466]
### Description

This may be related to #1373.  When multiple box widgets are used in the viewscene and one is hidden, moving the hidden widget will move the last clicked widget that is not hidden.  This happens even when the hidden widget is a point probe, but only when the last moved visible widget is a box widget.  see the included example networks.  

[multiple_box_wdgets.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/326238/multiple_box_wdgets.srn5.zip)
[multiple_box_wdgets_II.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/326237/multiple_box_wdgets_II.srn5.zip)

### Steps to Reproduce

1. create a network with multiple box widget (use example net)
2. hide (disable) one with the viewscene configure window
3. move one of the box widgets.
4. shift click and drag where the hidden widget should be.

**Expected behavior:** 
no widget should be moved

**Actual behavior:** 
last moved visible widget 

### Versions

scirun v5.0-alpha.AF-6-g8816a3f
OS X 10.8 and 10.10

**Comment by dcwhite** [comment]
I can fix this one--fix will be similar to #1448

**Comment by dcwhite** [comment]
Ignore previous comment. This is a bug with the selection algorithm (`SRInterface::select`). If you shift-click right on a visible box, you can still move it and it turns red, but then if you shift-click on a hidden widget, it will end up selecting the most recently-moved one like Jess described.
