### ISSUE TITLE
diagonal glyphs not visualizing properly

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1468]
### Description

when vectors align on the diagonal (1,1,1), (-1,-1,-1), or a scaled version of one of the two the vectors do not display properly.  the lines glyph is the only glyph that will display properly, the others will mostly not display, but may show part of the glyph, for instance the shaft of the arrow, depending on location of the origin of the vector.  vectors display fine if the values are changed slightly, ie, (1,1,.99).  This error is likely do to some numerical error.

[point_vectors.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/326624/point_vectors.srn5.zip)
### Steps to Reproduce
1. create a vector with direction +/- (1,1,1)
2. visualize with showFieldGlyphs.
3. try different glyphs.

**Expected behavior:**
The all glyphs should be displayed.

**Actual behavior:** 
Glyphs do not appear, or partially appear depending on vector location.  
### Versions

scirun v5.0-alpha.AF-6-g8816a3f
os x 10.8 and 10.10

**Comment by dcwhite** [comment]
@SCIInstitute/cibc-users From now until IBBM, please mark your new issues with "NEEDED FOR IBBM 2016" if it is that high priority. Otherwise, we will push the issue until after IBBM.

**Comment by jessdtate** [comment]
This one is needed for IBBM, so:

NEEDED FOR IBBM 2016
