### ISSUE TITLE
adding extractsimpleisosurface-module causes fatal error

### ISSUE THREAD

**Issue by johaenns** [SCIInstitute/SCIRun#1471]
SCIRun version v5.0-alpha.AF, Mac OS X 10.11.5

Start SCIRun and adding extractsimpleisosurface module to your net, gives an error-popup

"Unhandled exception: Module has no state value with name IsovalueChoice
Exiting now."

and leads to a SCIRun crash.

**Comment by dcwhite** [comment]
That's fixed on the master branch already.
