### ISSUE TITLE
viewscene: get lights to move correctly from GUI input

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#1474]
The lights controlled from the lights tab in the config menu of the viewscene need to be fixed so the movement occurs with the movement of the dot.

**Comment by dcwhite** [comment]
The angle sliders work. Still need to figure out those circle/dot widgets--do we keep them?

**Comment by dcwhite** [comment]
@jessdtate Beta or post-beta?

**Comment by jessdtate** [comment]
we implemented some sliders to do the same thing, but the dot widget still moves around. it is a bit confusing.  I'm fine going to the sliders only, but it is unfinished in its current state.
