### ISSUE TITLE
Decide on beta branching model

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1477]
Articles to read:
http://nvie.com/posts/a-successful-git-branching-model/
https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/
http://www.creativebloq.com/web-design/choose-right-git-branching-strategy-121518344

**Comment by dcwhite** [comment]
http://scottchacon.com/2011/08/31/github-flow.html

**Comment by dcwhite** [comment]
I vote for "Github Flow" described in the previous link. It's essentially what we're doing now, except I'll start making PRs for all my branches too :grinning: The only direct-to-master commits should be documentation typo fixes and the like.

**Comment by dcwhite** [comment]
Any other opinions?

**Comment by aylakhan** [comment]
I also vote for GitHub Flow. We're more likely to successfully follow a relatively simple model that's close to what we're already doing.

**Comment by dcwhite** [comment]
We decided on `github flow`. I'll make a new issue to update the contributing documentation with some guidelines.
