### ISSUE TITLE
The preferences tab cannot be opened.

### ISSUE THREAD

**Issue by DemonSouls** [SCIInstitute/SCIRun#1482]
### Prerequisites
- [x] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
- [x] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
- [x] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide. These links point to another project, but most of the advice holds in general.
### Description

Click on the 'SCIRun' tab and go to Preferences.  When it is click on, the drop down menu closes and the Preferences window doesn't open.

For Mac crash bugs, please _DO NOT_ paste an entire MacOS crash report here. Edit it down to just the stack trace of the thread that crashed, along with the general system info on the top.

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**
### Steps to Reproduce
1. Select the 'SCIRun' tab.
2. Click on 'Preferences'.

**Expected behavior:** When 'Preferences' is selected from the drop down 'SCIRun' menu, a preference window should open.

**Actual behavior:** When 'Preferences' is selected, no window opens and the 'SCIRun' menu closes.
### Versions

You can get this information from executing `SCIRun v5.0-alpha.AA-95-g0bdf068` at the command line, or clicking on the version button in the bottom right corner of the GUI (which copies the version to the clipboard). Run on Windows 7.

**Comment by dcwhite** [comment]
@DemonSouls Is this consistently reproducible? If so, attach some screenshots or video describing more detail. Was a network loaded or running, for instance?

**Comment by dcwhite** [comment]
Might be related to #1650. I'll change the underlying widget type.
