### ISSUE TITLE
An incremental change of theta drastically changes node position

### ISSUE THREAD

**Issue by 9595015** [SCIInstitute/SCIRun#1484]
### Prerequisites

* [ yes] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
[//]: # (* [ ] TODO: Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?)
[//]: # (* [ ] TODO: Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?)
* [ yes] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
* [ yes] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

### Description

In the rotation tab in the CreateGeometricTransform module, and incremental change in the theta rotation value will drastically change the position of the module and completely remove it from its original spot.

### Steps to Reproduce

1. create a simple network that has CreateGeometricTransform module that moves position of a node.
2. Upload a matlab file as the file being read.
3. change the value of the Theta rotation from zero to one degree, view the scene, and the node being moved will move drastically

**Expected behavior:** the node should just rotate around its axis, but should keep the same overall postion.
![screen shot 2016-06-29 at 12 41 26 pm](https://cloud.githubusercontent.com/assets/9469664/16499424/ad453a94-3ebd-11e6-913e-8fac8843d978.png)

This image shows the node in the brain with a theta value of zero

**Actual behavior:** the node moved from one spot to another

![screen shot 2016-06-29 at 12 41 55 pm](https://cloud.githubusercontent.com/assets/9469664/16499442/c16e9696-3ebd-11e6-92a3-7e69a9fa7c1a.png)

This image shows the node completely outside the brain with a theta value of one

### Versions
v5.0-Alpha.AD

**Comment by dcwhite** [comment]
@cbrightsci Not sure what kind of investigation this requires, or the priority.

**Comment by aylakhan** [comment]
Edited original bug report by removing template cruft, for clarity.

**Comment by johaenns** [comment]
I am not sure this is a bug. Since the used brain surface is in MRI voxel space (which is of course not visible), my first guess is that it's consequence of a relatively large distance between the observed node and the rotation axis.

**Comment by dcwhite** [comment]
Sounds like a reasonable PEBKAC. I'm in favor of closing.

**Comment by aylakhan** [comment]
Agreed, let's close.
