### ISSUE TITLE
SCI Run froze as I pulled up a screenshot of the network I was working on

### ISSUE THREAD

**Issue by harris30** [SCIInstitute/SCIRun#1485]
### Prerequisites
- [ yes] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
- [yes ] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
- [yes ] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide. These links point to another project, but most of the advice holds in general.
### Description

I took a screenshot of the network I was working on, then I pulled up that same network. Now SCI Run is perma-frozen

For Mac crash bugs, please _DO NOT_ paste an entire MacOS crash report here. Edit it down to just the stack trace of the thread that crashed, along with the general system info on the top.

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**
### Steps to Reproduce
1. Open up SCI Run
2. Pull up a network
3. Take a screenshot of the same network
   4.Pull up the screenshot and then pull up the network
   ![screen shot 2016-06-30 at 12 25 20 pm](https://cloud.githubusercontent.com/assets/20230314/16499636/8ceb6e3e-3ebe-11e6-94f3-401c8ea9d316.png)

5.Perma-frozen
**Expected behavior:**SCI Run to run normally

**Actual behavior:** SCI Run was perma-frozen
### Versions

SCI Run is frozen so I can't get the version, so I'm typing it by hand. Version v5.0-alpha.AD

**Comment by dcwhite** [comment]
Can't do anything with this one.
