### ISSUE TITLE
Showfield Faces Tab Nonresponsive Options Issue

### ISSUE THREAD

**Issue by MissionMan77** [SCIInstitute/SCIRun#1486]
### Prerequisites

* [x] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
[//]: # (* [ ] TODO: Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?)
[//]: # (* [ ] TODO: Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?)
* [x] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
* [x] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

### Description

On showfield's faces tab. Several buttons do not work: Everything in facecoloring, use face normals, and render images as a texture.

For Mac crash bugs, please *DO NOT* paste an entire MacOS crash report here. Edit it down to just the stack trace of the thread that crashed, along with the general system info on the top.

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**

### Steps to Reproduce

1. Bring up showfield module in any circuit.
2. Try clicking any of buttons mentioned above.
3. Nothing happens.

**Expected behavior:** I expected it to click.

**Actual behavior:** Nothing

### Versions
v5.0-alpha.AD-10-ga14d694
You can get this information from executing `SCIRun --version` at the command line, or clicking on the version button in the bottom right corner of the GUI (which copies the version to the clipboard). Also, please include the OS and what version of the OS you're running.

**Comment by dcwhite** [comment]
Those options are not available yet. We should hide them in the GUI @cbrightsci
