### ISSUE TITLE
Python script crash with execute

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1490]
[IBBM_python_lab.py.zip](https://github.com/SCIInstitute/SCIRun/files/346871/IBBM_python_lab.py.zip)

This script causes SCIRun to crash when launching it from the command line using the -s flag. The script does not cause SCIRun to crash if you comment out the execute, the script doesn't crash, and then you can execute the network and it doesn't crash. If you comment out the modules that involve creating and rescaling the colormap, the network loads and executes perfectly. That version of the script is below

[IBBM_python_lab_no_colormap.py.zip](https://github.com/SCIInstitute/SCIRun/files/346874/IBBM_python_lab_no_colormap.py.zip)

### Prerequisites

* [x] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
[//]: # (* [ ] TODO: Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?)
[//]: # (* [ ] TODO: Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?)
* [x] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
* [x] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide. These links point to another project, but most of the advice holds in general.

### Description

[Description of the bug or feature]

For Mac crash bugs, please *DO NOT* paste an entire MacOS crash report here. Edit it down to just the stack trace of the thread that crashed, along with the general system info on the top.

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `SCIRun --version` at the command line, or clicking on the version button in the bottom right corner of the GUI (which copies the version to the clipboard). Also, please include the OS and what version of the OS you're running.

**Comment by dcwhite** [comment]
@gduffley I can't replicate on my Macbook (10.9). What system are you on?

**Comment by gduffley** [comment]
![screen shot 2016-07-04 at 10 16 40 pm](https://cloud.githubusercontent.com/assets/5941547/16573785/16c75bd0-4235-11e6-909a-edf20292ccbf.png)

I am on the build from last lunch.

**Comment by gduffley** [comment]
And there actually is an error message too.:
2016-07-04 22:19:27.646  [NOTICE] Invalid Connection request: input port is full, or ports are different datatype or same i/o type, or on the same module.
Module added: ViewScene:0
Waiting for rendering system initialization....
Done waiting.
Segmentation fault: 11

It doesn't make sense though, because all of the connections seem fine as long as you don't execute.

**Comment by johaenns** [comment]
I am not sure if this is helpful, but under OS X 10.10.5 both scripts fail with the above error, under opensuse they execute fine.

**Comment by dcwhite** [comment]
OK looks like this is very OS-dependent then. I will test Windows and we can survey other machines at the lunch today.

**Comment by gduffley** [comment]
I just made @ajanson test it. On Windows 7, and the network loads and executes, but the ViewScene has an error. If he deletes the ViewScene and adds a new one, it then executes without error

**Comment by dcwhite** [comment]
That's the independent ViewScene error, different problem. It works on my Win10 machine too. Do you always get the "Invalid Connection request" with it too?

**Comment by gduffley** [comment]
I just tested again and didn't get it, but I have in the past. The error definitely seems to be ViewScene dependent. I am going to be playing with the python stuff most of the day today, so I'll see if I can try to narrow down the error. My hunch is that it doesn't have to directly do with the colormap, but more with general complexity of the inputs to ViewScene.

**Comment by dcwhite** [comment]
Just got it to crash via the "wand" script-execute in gui option. I will investigate further.

Also, on the 17th try of `.\SCIRun.exe -s .\IBBM_python_lab.py --no_splash -E`, it crashed. So it might actually be the same problem--ViewScene is dying randomly, and the `execute_all()` is trying to run the broken ViewScene, resulting in a crash. Let me try adding code that can detect if VS is broken, then prevent `execute_all()` from running.

**Comment by gduffley** [comment]
Great, thanks @dcwhite

**Comment by dcwhite** [comment]
One workaround you can try is moving the `view_scene = scirun_add_module("ViewScene")` line to the beginning of the script, and then adding a python sleep call. I have a built-in delay before executing, but it's probably not long enough for python purposes.

**Comment by gduffley** [comment]
The easier solution is to just not include the ViewScene. The only time you really need an execute at launch is when scripting something, and if you're scripting something, you won't be looking at the ViewScene.

**Comment by dcwhite** [comment]
Hehe, until of course we implement headless frame buffer/rendering, in year 2025.

**Comment by johaenns** [comment]
For IBBM not including the automatic execution might also be a workaround. Manually executing the net created by the script works fine for me.

**Comment by gduffley** [comment]
That is the tentative plan. My lab is still far from done

**Comment by dcwhite** [comment]
Related: #881

**Comment by gduffley** [comment]
Just wanted to clarify that it works 0% of the time on my OSx machine

**Comment by dcwhite** [comment]
Right. I think @kgillette was getting 100% ViewScene failure on her Mac too, and she might be on 10.10.

**Comment by gduffley** [comment]
The ViewScene that is created via the script works 100% of the time, as long as I manually execute after the script as competed. That can be done via the Python Console or the GUI

**Comment by dcwhite** [comment]
We decided to force-disable connections to ViewScene when executing from python. I will update this issue when that is testable in master.

**Comment by dcwhite** [comment]
@gduffley @johaenns Could you guys test the latest master? I have a fix in. Just re-enable the connections to ViewScene manually after execution to trigger rendering.

**Comment by gduffley** [comment]
@dcwhite I don't have the src compiled on my laptop. I am trying to build now, but I could easily run into issues.

**Comment by johaenns** [comment]
@dcwhite Me neither, since there is no dmg of qt 4.x for OS X 10.10.5 and the downloadable ones won't install...

**Comment by gduffley** [comment]
I have qt4 built from source, so I think I should be able to get it to compile. No errors thus far, but there might be issues still

**Comment by dcwhite** [comment]
Message @aylakhan about making a new installer. I can't on my Mac unfortunately.

**Comment by gduffley** [comment]
I'm getting compiler errors I don't have time to hunt down. I'll message her on slack

**Comment by johaenns** [comment]
Works fine for me. Though I like my save and reload fix better :-D

**Comment by dcwhite** [comment]
@gduffley has confirmed this fix works. I'll open a new issue to tackle the general problem later.
