### ISSUE TITLE
Fix EditMeshBoundingBox transform logic and GUI updating

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1496]
Various weird issues with it.

@johaenns has been testing it thoroughly, he can make comments with specific examples.

**Comment by johaenns** [comment]
[tut_simple.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/348444/tut_simple.srn5.zip)

This was my test net, basically the start of the heart-defib tutorial. All done on OS X 10.10.5.

Errors were:

- boundingbox and object not aligned after moving - object doesn't move to the position where the boundingbox was placed.

- object does not only get translated, but also rotated or sheared

- when only shift-clicking on an boundingbox edge (without actually moving the box), both boundingbox and object get translated. It seems like this translation always occurs in x-direction.
