### ISSUE TITLE
Module_icons_disappeared

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1508]
I just finished building the latest master and module icons are gone.
![module_icons_gone](https://cloud.githubusercontent.com/assets/2054570/16660718/961d700e-443d-11e6-9dd3-121d3a25d36e.png)

I have not seen that before is this a new feature or just happening on my MacOS 10.7.5?

**Comment by dcwhite** [comment]
You haven't used or built SCIRun in a while. The buttons appear when you hover over the modules now. It's been that way about a month.
