### ISSUE TITLE
Convert BasicTutorial manual from LaTeX to Markdown format

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1513]
This will enable online rendering and easier editing. Suggested by @lizutah.

**Comment by dcwhite** [comment]
@kgillette Do you still have time to work on this one?

**Comment by kgillette** [comment]
I don't have time for about another week or two. I tried using a markdown converter over the weekend though.

**Comment by dcwhite** [comment]
Any luck with the converter?

**Comment by collint8** [comment]
Here is a link to a raw conversion from latex to markdown from the converter https://github.com/collint8/SCIRun/blob/master/src/Documentation/Manuals/BasicTutorial/BasicTutorial.md 
It renders the images but it has problems with referencing images and it also lacks the captions for them. 
It also doesn't work with the scope feature

**Comment by dcwhite** [comment]
Calling all @SCIInstitute/scirun-users, please check out the markdown version of the basic tutorial pdf above, and make comments about it here.

**Comment by jessdtate** [comment]
The markdown version looks pretty good. A couple notes.
It looks like the pandoc converter didn't convert the figure captions or figure references correctly.  If we move it to pure markdown there are ways around this.
As general feedback on the tutorial, it probably needs an update to the introduction, ie, and explanation of some of the preferences and features that are available.  Maybe it can walk through the startup wizard.  This might be better suited in a 'Getting Started' doc though.

**Comment by collint8** [comment]
There are 25 images in this manual. I could incorporate a mouse-over title really easily. I'm going to work on the physical titles but it will take longer.

**Comment by collint8** [comment]
Physical titles are up.

**Comment by gduffley** [comment]
It looks good to me. How come it isn't linked from http://sciinstitute.github.io/scirun.pages/ ?

**Comment by dcwhite** [comment]
We're just trying things out, both with the tutorials and the github.io content. All works in progress

**Comment by aylakhan** [comment]
The chapter and section headings are very large. Also, the link in section 1.1.1 should point to GitHub.

**Comment by aylakhan** [comment]
Equation formatting needs work:

<img width="317" alt="eqn" src="https://cloud.githubusercontent.com/assets/1399377/18882020/cd6f138a-849a-11e6-9309-0766b2784084.png">

**Comment by aylakhan** [comment]
Text is also missing section cross-references.

**Comment by aylakhan** [comment]
Use the [figure](http://www.w3schools.com/tags/tag_figure.asp) and [figcaption](http://www.w3schools.com/tags/tag_figcaption.asp) tags for figure layout.

**Comment by aylakhan** [comment]
It looks like the lines starting with "Scope:" got mangled in the conversion.

**Comment by dcwhite** [comment]
@collint8: try to implement @aylakhan's suggestions by next Monday.

**Comment by collint8** [comment]
I'm on it. Here's the progress so far https://collint8.github.io/scirun.pages/BasicTutorial.html

**Comment by zaracay** [comment]
I agree with @jessdtate comments from earlier.  There needs to be some sort of installation instructions and an introduction that explains why you show the examples that you chose.  Also, the heading to 2.1, 2.1.2, 3.3 are the same (Slice Field).  Top level titles (2.x and 3.x) should be more descriptive of the overall goal of the section and should not be repeated.

3.4 text problem similar to what @aylakhan pointed out:
DAT**A1 > 1&&X < 0

**Comment by dcwhite** [comment]
This issue is for formatting concerns. I'll open a new one for suggestions on new tutorials and manuals, and copy your comments there.

**Comment by dcwhite** [comment]
Good work on scope and links. If you get equations looking nice by Monday at 2pm, we can show it to Rob.

**Comment by dcwhite** [comment]
@jessdtate @collint8 Could one of you update this issue with details about equation handling tools that you found? Thanks

**Comment by dcwhite** [comment]
@jessdtate @collint8 Looking for any update on this one...and pushing to next milestone.

**Comment by jessdtate** [comment]
it looks like mathjax will be able to do all the equation stuff that we need.  @collint8  is testing it so he will give an update on that when he is finished.

**Comment by jessdtate** [comment]
@collint8 Is there anything major left on this document?  if not, We should make a pull request, make a new issue of the things that are left and close this one.

**Comment by dcwhite** [comment]
Completed with https://github.com/SCIInstitute/scirun.pages/pull/3
