### ISSUE TITLE
Module documentation wiki page conversion: Use new github pages system

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1514]
@aylakhan can fill in the details on the new format. @lizutah suggests using Markdown for these.

**Comment by aylakhan** [comment]
Andy Corbato has started this.

**Comment by dcwhite** [comment]
Need to check progress.

**Comment by dcwhite** [comment]
@jessdtate This is done, right? It needs updating, but the site is functional.

**Comment by jessdtate** [comment]
Yeah, you're right. You can do the honors
