### ISSUE TITLE
Standard expression in ClipFieldByFunction is erroneous

### ISSUE THREAD

**Issue by johaenns** [SCIInstitute/SCIRun#1523]
When creating a new ClipFieldByFunction-module the standard expression is "DATA1 < 0", which is leading to an error, since a port DATA1 doesn't exist. I assume this should be "DATA < 0" instead.

Version: 5.0-beta.B-30

**Comment by dcwhite** [comment]
Could you provide a test network? I could not replicate. The code checks for both "DATA" and "DATA1" for the first field's data.

**Comment by johaenns** [comment]
My bad, had an old version running to check this. Sorry bout that. The error is gone. There only remains a discrepance between expression parser documentation and the standard expression, since DATA1 is not mentioned anywhere in the documentation, but always DATA is used. But I guess this has low priority to be fixed.

**Comment by dcwhite** [comment]
That's due to the generalization of the module to take arbitrary fields and data (two dynamic ports). I'll update the doc.
