### ISSUE TITLE
Sphere option: make scalable as percentage of bounding box

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1524]

**Comment by jessdtate** [comment]
I agree

**Comment by dcwhite** [comment]
Will discuss at next week's meeting

**Comment by jessdtate** [comment]
For modules:  GenerateSinglePointProbe, GenerateSeedsFromField, GenerateElectrode.

**Comment by jessdtate** [comment]
Standardize some of the features: color selection,  projection to input field.

**Comment by RubioJr9** [comment]
PR #2267 implements this for GenerateSinglePointProbeFromField and GeneratePointSamplesFromField, but converting GenerateElectrode(#1289) precedes the percentage scaling for that module.
