### ISSUE TITLE
Issue with full screen mode on newer OSX

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1526]
Main window goes into a weird state that is hard to get out of. Time to upgrade my Mac....

**Comment by dcwhite** [comment]
I saw this again last week on a 10.12 desktop. We'll need to get the various screen/view hotkeys working properly, and documented.

**Comment by dcwhite** [comment]
Copy hotkeys from a common app.

**Comment by dcwhite** [comment]
@jessdtate @RubioJr9 @Haydelj Needs testing on various newer MacOSes! Please add feedback.

**Comment by jessdtate** [comment]
Aside from the fact that I dislike full screen mode, seems to work fine for me. 
os x 10.14
qt 5.13

**Comment by dcwhite** [comment]
@jessdtate We can probably close this one, should it wait for the testing lunch feedback cycle?

**Comment by jessdtate** [comment]
I think this it is ok to close
