### ISSUE TITLE
Add website contents to code repo (this)

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1547]
A simpler documentation model:
https://github.com/blog/2228-simpler-github-pages-publishing

This will simplify issues related to documentation, as well as enable documentation checks as part of CI and build scripts.

**Comment by dcwhite** [comment]
@jessdtate Another good intern one, but it will need some guidance since it will involve lots of files.

**Comment by jessdtate** [comment]
yeah, this is one of my plans for @nids2001.

**Comment by dcwhite** [comment]
Move everything to docs folder on master; ignore gh-pages for now.
