### ISSUE TITLE
quit when can't run script in headless mode.

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1558]
### Description

When attempting to run a script in headless mode, if the script does not have a valid quit function, there is no way to regain control of scirun.  This happens if the script file doesn't exist, is not a valid script file, if there is no quit function, or if there is an error in the execution of the script (doesn't get to the quit function).  In these cases, SCIRun does not return to the command line to allow more inputs, but either hangs with a blank line or prints out:
[SCIRun] Running Python script.
[SCIRun] Running Python script.
every few seconds.

I tried this on a few machines with the only difference being the blank line or the repeated line.  

### Steps to Reproduce

1. run script in headless mode  with random string as script name:
./SCIRun_test -x -s somestring
with headless build:
./SCIRun -s somestring
3. run the same with any script that doesn't have a quit function

**Expected behavior:** 

SCIRun should probably quit 

**Actual behavior:** 

provides some messages.  in this example:
Could not load python file: somestring

Then stays on a blank line or prints:
[SCIRun] Running Python script.
over and over

### Versions

orion10 headless build
scirun version: v5.0-beta.E-6-g75108bd

iMac Qt build running headless mode
os x 10.10
scirun version: v5.0-beta.E-23-g4809d5e

**Comment by dcwhite** [comment]
Error cases were fixed.

New/changed command line options to handle other cases:
`-S <script.py>`: interpret script and quit after first execution pass is done
`-s <script.py>`: interpret script and drop into internal python console.
These options mirror the `-e/-E` pair for the GUI.
