### ISSUE TITLE
Syntax for passing arguments with python scripts

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1565]
Like you would call `python example.py arg1 arg2` you should be able to call `SCIRun -s example.py arg1 arg2`

**Comment by dcwhite** [comment]
I passed the entire command line to the python interpreter, so now you have full access to sys.argv inside scripts and the console. Thus you can extract args out that way, just pass them in like you have above--SCIRun will ignore ones it doesn't recognize.

**Comment by gduffley** [comment]
I tested this today for the first time and it's not working. I am getting an error: "[ERROR] File load failed(FIRST_PASSED_ARG): exception in load_xml, unrecognized XML syntax"

**Comment by dcwhite** [comment]
Could you open a new bug issue with complete steps for reproduction? Thanks
