### ISSUE TITLE
InterfaceWithPython gui variable names not scrolling

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1573]
### Description

in the InterfaceWIthPython module UI, the variable names do not scroll with the port names and types.  When this happens the names and the ports do not match (in the UI only).  It also makes it hard to the change the variable names at the bottom of the list.  However, if the you scroll down, then change tabs and then go back to the tab, it will be stuck in the new position.  This allows the user to view the names at the bottom of the list.   This is the same on the input and output tabs.  There may be the same issue with other modules with tables, but I haven't found another one that requires scrolling.  This is not a problem with my os x 10.10 machine, only my os x 10.8 machine.

![iwp_gui_stuck_1](https://cloud.githubusercontent.com/assets/3484631/20808986/e2a25eb0-b7c1-11e6-9932-932458bd8cc7.png)
![iwp_gui_stuck_2](https://cloud.githubusercontent.com/assets/3484631/20808987/e2a78912-b7c1-11e6-9bbd-c7058ce65ed8.png)

### Steps to Reproduce

1. open a IWP module gui
2. in the output tab, scroll down to the bottom of the list

**Expected behavior:** 
 
whole table should scroll

**Actual behavior:** 

only the port names and types scroll, variable names do not  

### Versions
os x 10.8
scirun v5.0-beta.E-96-g17438de

**Comment by dcwhite** [comment]
This might be another Qt/10.8 bug with tables, similar to the buttons in the treeview not scrolling correctly. I will test it out on other platforms and see.

**Comment by dcwhite** [comment]
10.8 support will be dropped soon, qt 5 will eliminate this anyway, so let's close.
