### ISSUE TITLE
toolkit menu improvements

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1588]
The recently added toolkit menu needs a few improvements.  

- Is it possible that when the user tries to load a toolkit with the same name, the prompt asks to confirm overwrite instead of rejecting it outright?  This will allow users to more easily replace a toolkit with an updated version.  
- There needs to be an option to remove a toolkit from the menu, otherwise the list may become too long.  This could be combined with the import in a dialogue that allows users to add or remove toolkits.  
- It would probably be nice to have a warning in the menu or something that reminds the users to set the SCIRUNDATADIR to the correct version of the toolkit data.  I'm not sure how this would work, but I wouldn't want it too intrusive.  We should have it as a note on all the networks in the toolkits.  Could we have a link to the data preference tab in the menu, something like 'set the SCIRunData dir'?

**Comment by jessdtate** [comment]
if the user replaces the same toolkit file with an updated version and keeps the name, will the list of networks update?  Based on my tests, it seems like it would, but only when SCIRun is restarted.  If this is the case than it is sufficient.  Otherwise, there can be an update toolkit button, where it reloads the toolkit files.

**Comment by dcwhite** [comment]
- [ ] Confirm overwrite instead of reject: yes
- [ ] Remove toolkit from menu action: yes
- [ ] Link with data dir menu: yes
- [ ] Update toolkit: I will test and make sure behavior makes sense
