### ISSUE TITLE
module ui window bar inconsistency. 

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1595]
### Description

In the new toolbar in the module UIs, there the window bar sometimes shows up, and sometimes doesn't.  When the module pops up at first, there is no window bar and looks the same as it does when it is docked.  After docking and undocking, the window bar then appears.  I'll try to get images later. Upload isn't working right now.

![window_predocked](https://cloud.githubusercontent.com/assets/3484631/23440951/817bd1f0-fddc-11e6-9e2a-9e74ff90f31d.jpg)
![window_docked](https://cloud.githubusercontent.com/assets/3484631/23440955/84c17e50-fddc-11e6-9987-9300c57c1999.jpg)
![window_undocked](https://cloud.githubusercontent.com/assets/3484631/23440961/9497f0c0-fddc-11e6-8295-9d20341e1a67.jpg)

### Steps to Reproduce

1.  set preferences to disable module docking.  
2.  open a module ui.  module ui appears without window bar
3.  dock module ui
4.  undock module ui.   module ui appears with window bar

### Versions

scirun v5.0-beta.G-43-g3283f26
OS X 10.10 and 10.12

**Comment by dcwhite** [comment]
@jessdtate Can you try uploading screenshots now? AWS is back apparently.

**Comment by dcwhite** [comment]
I didn't test it with "Enable Module Dock" turned off. I will fix this soon.
