### ISSUE TITLE
bundle_toolkit tool needs help function

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1596]
### Description

The bundle toolkit used to package the toolkit networks could use some help documentation in it if it is to be called by users.  ie, running ./bundle_toolkit --help and getting directions.  

### Steps to Reproduce

1. navigate to bin/SCIRun 
2. ./bundle_toolkit --help

**Expected behavior:** 

Should explain the syntax of the function

**Actual behavior:** 

Creates a file --help.toolkit, which is kind of hard to get rid of.  

### Versions

scirun v5.0-beta.G-54-g28894ce
os x 10.12

**Comment by dcwhite** [comment]
If you run with no arguments, the help is printed. Matches most built in tools.

**Comment by dcwhite** [comment]
I'll add a basic help check though.

**Comment by jessdtate** [comment]
It seems like this tool will be used more than most of the others, so it might be helpful.  Maybe an error check for the '-', which is almost always supposed to be a flag.

**Comment by dcwhite** [comment]
Any other parameters to check?
```
[~/Desktop/Dev/SCIRun/bin/SCIRun] $ ./bundle_toolkit
Usage: bundle_toolkit OUTPUT_FILE [DIRECTORY_TO_SCAN]
If no directory specified, current directory is scanned.
Thu Mar 02 11:38:48
[~/Desktop/Dev/SCIRun/bin/SCIRun] $ ./bundle_toolkit --help
Usage: bundle_toolkit OUTPUT_FILE [DIRECTORY_TO_SCAN]
If no directory specified, current directory is scanned.
Thu Mar 02 11:38:51
[~/Desktop/Dev/SCIRun/bin/SCIRun] $ ./bundle_toolkit -h
Usage: bundle_toolkit OUTPUT_FILE [DIRECTORY_TO_SCAN]
If no directory specified, current directory is scanned.
Thu Mar 02 11:38:55
[~/Desktop/Dev/SCIRun/bin/SCIRun] $ ./bundle_toolkit -a
Usage: bundle_toolkit OUTPUT_FILE [DIRECTORY_TO_SCAN]
If no directory specified, current directory is scanned.
```

**Comment by jessdtate** [comment]
That solution works
