### ISSUE TITLE
ShowString: Textbox anchor point control

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#1615]
### Description

Text is anchored, by default, to the lower left corner of the text box.  As a result, if I place the text along the upper boundary or along the right most boundary of the View Window, the text is no longer visible.  It is out of the view pane.

### Steps to Reproduce

1. CreateString -- write any string
2. ShowString -- change x or y coordinate to 1

I would expect to see the text in the view scene.

Options we discussed: 
- Give the user the ability to select the location of the text box anchor point (left lower, left center, left upper, etc.)
- Dynamically assign anchor point based on coordinate location
   -- if coord location = x=1 y=1 => anchor point assigned to upper right
   -- if coord location = x=0 y=1 => anchor point assigned to upper left
   -- if coord location = x=0 y=0.5 => anchor point assigned to center left
   -- if coord location = x=0.5 y=.5 => anchor point assigned to center center
   -- etc.
- Allow users to drag and drop text within the view window (probably overly hard for as many people that would use it)
- SCIRun 4 solution Is to have a drag and drop location in the module gui

### Versions

v5.0-beta.G-133-g2cf6e21

**Comment by dcwhite** [comment]
I implemented the second of the options above. GUI is identical but the position adapts to proximity to ViewScene border.
