### ISSUE TITLE
scorn crash when creating subnet

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#1631]
### Description

SCIRun crashes when creating a subnet with error:
2017-06-02 14:40:23.981 SCIRun[19346:1589165] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Segmentation fault: 11

### Steps to Reproduce

1. Run SCIRun with the torso-tank-bem.srn5  network
./bin/SCIRun/SCIRun.app/Contents/MacOS/SCIRun ~/Desktop/Toolkits/FwdInvToolkit-1.2.1/Networks/potential-based-bem/torso-tank-bem.srn5 

2. Select area to create subnet:
<img width="1680" alt="screen shot 2017-06-02 at 2 42 58 pm" src="https://cloud.githubusercontent.com/assets/3494177/26739962/d196430a-47a1-11e7-9ec5-54e1f209713b.png">

3. create subnet and name it 'gato'
4. push enter and crash

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `SCIRun --version` at the command line, or clicking on the version button in the bottom right corner of the GUI (which copies the version to the clipboard). Also, please include the OS and what version of the OS you're running.

**Comment by dcwhite** [comment]
Put crash reports in #1609

**Comment by jcollfont** [comment]
only breaks in my local build
