### ISSUE TITLE
'Connect Module ...' is broken

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#1635]
Gui feature 'Connect Module ...' does not seem to work at all. It either crashes (e.g., colormap input port of RescaleColorMap) or does not do anything (e.g., field output port of ClipFieldbyFunction).

### Prerequisites

* [x] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
* [x] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
* [x] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

### Description

Right click on module (as mentioned above) and trying to connect to relevant module is selection
box makes SCIRun5 (master repo/subnet3) crash or does not do anything (at least visually).

### Versions
Version: v5.0-alpha.V-2557-g85250fc 
On MacOS Sierra (10.12)

**Comment by dcwhite** [comment]
I will cover this in the new subnet issue.

**Comment by dcwhite** [comment]
Look here https://sciinstitute.slack.com/archives/C0B58V1CJ/p1497022271316851?thread_ts=1497021862.158848&cid=C0B58V1CJ
