### ISSUE TITLE
Lock ViewScene Rotation, Zoom, Pan controls

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1647]
### Description

I would like to be able to turn off the ability to rotate, zoom, pan, etc. in the ViewScene window (each of these cases individually or any combination thereof). 

For my use case if I get the ViewScene in a certain orientation I want to disallow rotation of the window and only allow zooming and panning. Right now it is very easy to left click and drag the mouse to accidentally rotate the ViewScene, especially when attempting to shift + left click a widget instead.

### Versions

v5.0-beta.J-6-gd5127e0

**Comment by dcwhite** [comment]
I'll make a valiant effort to get this one in before the breakfast tomorrow.
