### ISSUE TITLE
Fix size of network editor space

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1648]
This might help with zooming and new module placement. Try out four vertical pages of iMac screen space.

**Comment by dcwhite** [comment]
Use the function for screen geometry, and default to 2x width and 4x height. Then add an advanced option to increase this.

**Comment by dcwhite** [comment]
@ajanson @jessdtate Can you guys test network editor space in `beta.Q`? Some changes were made that might obviate this one.

**Comment by jessdtate** [comment]
seems to be working ok
