### ISSUE TITLE
Preferences window can't be closed on Linux

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1650]
There is no way to close the window.

I'm running Suse13.2.

**Comment by dcwhite** [comment]
I'll see if I can replicate on my home Ubuntu box. What version are you on now?

**Comment by gduffley** [comment]
I built the branch you wanted us to use yesterday.

**Comment by dcwhite** [comment]
I couldn't replicate on Ubuntu. Can you take a screenshot of the window on your machine?

**Comment by gduffley** [comment]
![screenshot - 07052017 - 04 15 18 pm](https://user-images.githubusercontent.com/5941547/27887439-06fd1576-619e-11e7-9f69-d1b1e3d24b22.png)

**Comment by dcwhite** [comment]
Bizarre. Do any other subwindows have this problem?

**Comment by gduffley** [comment]
I don't know of any. All that I looked at have the same GUI as the python console in this screenshot 
![screenshot - 07052017 - 04 31 45 pm](https://user-images.githubusercontent.com/5941547/27887767-b0d4679c-619f-11e7-8ebd-6b1d7be43cbe.png)

**Comment by dcwhite** [comment]
Does `Esc` close it?
