### ISSUE TITLE
GetMatrixSlice resetting index every time the network executes

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1651]
Disclaimer: I'm using Linux (Suse13.2)

This makes it impossible to execute the network at any value besides 0. It is the case if you use play or specify the slice to a specific value.

This is a problem because Heart_visualization.srn5 for IBBM uses this module

**Comment by jessdtate** [comment]
Are you sure that you are using the first instance of the module, not the downstream one, ie, the one controlling the other?

**Comment by gduffley** [comment]
Yeah, I'm dumb
