### ISSUE TITLE
unable to compile beta-J on Antergos linux

### ISSUE THREAD

**Issue by neuroradiology** [SCIInstitute/SCIRun#1655]
### Prerequisites

* [x] Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
* [x] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
* [x] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?

### Description

When compiling on linux (antergos) the ./build.sh script has errors due to left-shifting on a negative left-hand operand:

$SCRUNROOT/src/Core/Datatypes/Legacy/Field/TetVolMesh.h:2482:43

```
$USER/SCIRun/src/Core/Datatypes/Legacy/Field/TetVolMesh.h: At global scope:
$USER/SCIRun/src/Core/Datatypes/Legacy/Field/TetVolMesh.h:2482:43: error: left operand of shift expression ‘(-1 << 10)’ is negative [-fpermissive]
     static const int up_mask = (~((int)0) << sz_third_int << sz_third_int);
                                 ~~~~~~~~~~^~~~~~~~~~~~~~~

```

Similar error a few lines later:

```

$USER/SCIRun/src/Core/Datatypes/Legacy/Field/TetVolMesh.h:2516:45: error: left operand of shift expression ‘(-1 << 16)’ is negative [-fpermissive]
     static const int up_mask = ((~((int)0)) << sz_half_int);
                                ~~~~~~~~~~~~~^~~~~~~~~~~~~~~

```

currently using origin/master, but also occurs with most recent beta release

### Steps to Reproduce

1. checkout  git master branch
2. cd $SCIRun/bin
3. cmake ../src
4. make -j4

**Expected behavior:** 
compilation of working binary

**Actual behavior:** 
compiler crash due to negative left-operand in shift expression in TetVolMesh.h

### Versions
uname -a:  Linux ant-17.2 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux

The C compiler identification is GNU 6.3.1
"
The CXX compiler identification is GNU 6.3.1

**Comment by dcwhite** [comment]
This is a known issue on very recent Linux releases. Fix will come today.
