### ISSUE TITLE
clipping plane connection to UI bug

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1657]
### Description

Clipping plane 1 will become plane 6 if a second clipping plane is created.  It will disconnect form plane 1, with the appearance of being unable to modify or delete it.  The Plane can be controlled as clipping plane 6.  If another plane is created first (2, 3, etc)  there are no problems.  

### Steps to Reproduce

1. create visualization with latvol snippet
2. create a clipping plane (make visible and create a non-zero normal)
3. create a second clipping plane.
4. go back to plane 1 (no options set, but scene still clipped)
5. go to plane 1 (parameters originally set are here)

**Expected behavior:** 

Plane 1 ui should maintain the parameters 

**Actual behavior:**

switching to plane 6

### Versions
os x 10.12
scirun v5.0-beta.J-117-g45a700f45

**Comment by dcwhite** [comment]
Essential for IBBM?

**Comment by jessdtate** [comment]
not necessarily. Crashes are more important.  The IBBM students will probably run into it though.
