### ISSUE TITLE
new folder crashing in OS x

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1658]
### Description

When pressing the new folder button in the file navigator dialog, SCIRun will crash.  This is true for read/writefield/matrix/bundle and load/save network.  

### Steps to Reproduce

1. choose save network
2. click new folder

**Expected behavior:** 

should create a new folder in the path specified

**Actual behavior:** 

SCIRun Crashes

### Versions

Os x 10.12
scirun v5.0-beta.J-123-g83b568718

**Comment by dcwhite** [comment]
Can't replicate. Can you try some other machines?

**Comment by dcwhite** [comment]
And how about a stack trace?

**Comment by dcwhite** [comment]
Seems to be 10.12 only.

**Comment by jessdtate** [comment]
seems to be fixed in 10.13
