### ISSUE TITLE
Update Python version in SCIRun

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1668]
May fix error associated with 

/home/sci/gduffley/Development/SCIRun/bin/Externals/Install/Python_external/lib64/python3.4/lib-dynload/_ctypes.cpython-34m.so: undefined symbol: _PyTraceback_Add

and

Error while finding spec for ‘pip.__main__’ (<class ‘ImportError’>: /home/sci/gduffley/Development/SCIRun/bin/Externals/Install/Python_external/lib64/python3.4/lib-dynload/pyexpat.cpython-34m.so: undefined symbol: _PyTraceback_Add); ‘pip’ is a package and cannot be directly executed

**Comment by dcwhite** [comment]
This will have to wait until after pybind replaces boost.python.
