### ISSUE TITLE
save scirun preferences when saving network or from the preferences window.

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1673]
### Description

Feature request. The preferences need to be save more frequently than just when scirun is shut down. It would be nice if the general preferences save (or check if needs to be saved) when the network is saved.  Another option would be to save when the preference window is closed or have a save preferences button in the preferences window.  This will allow the preference to save even if SCIRun crashes in that session.

**Comment by dcwhite** [comment]
Done. Settings are saved when the network file is saved, when executed (execute all button), and on closing the prefs window.
