### ISSUE TITLE
ShowField: Enable Transparency affects ViewScene Rendering

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1674]
I am running the most recent git pull of SCIRun 5 (updated 18.07.2017) and the version on my GUI is v5.0-betaN. I am operating on CentOs 7.3.1611 OS. 

The network that crashed is a generic rendering of different tissues in a torso segmentation. 

![torso_view](https://user-images.githubusercontent.com/12956701/28317245-69b73c5a-6bc6-11e7-965f-34a54a76b03c.png)

When I load and run the network, the Viewscene will not render some of the graphics until I delete every pipeline and reconnect them. I think it has something to do with the enable transparency in the faces tab of the showField. The second grouping of getdomainboundary->fairmesh->showfield has an altered transparency value. When I changed the transparency value (say from 0.65 to 0.75), the specific object disappears from the viewscene completely, isn't transparent at all, or sometimes it will actually change to the set transparency. This hasn't been an issue until the most recent update. 

Karli

**Comment by dcwhite** [comment]
Can you upload network and data? And is there an actual crash, or are objects just not appearing when they should be?

**Comment by kgillette** [comment]
My computer is currently being moved so I don't have access to the data or the files. I will be sure to upload them as soon as I am up and running again. There is no actual crash of SCIRun or with the ViewScene module, but the rendering is behaving improperly.

**Comment by dcwhite** [comment]
This needs further testing with all the new renderer changes.
