### ISSUE TITLE
IBBM 2017 ideas

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1675]
- [ ] Make network editor space dynamic sized, with helper widgets to resize
- [ ] Add more note font default settings
- [ ] Move mouse mode toggle buttons out of advanced toolbar (advanced should have everything IBBM users *don't* need)
- [x] Misleading current file name when loading a toolkit network on top of a saved file
- [x] If CreateMatrix checkbox checked, warn when executing
- [x] CreateMatrix hide UI button should save contents
- [x] Red X on module UIs is too glaring, switch to something muter
- [x] Fix close action for info box
- [ ] Rethink module dock widget space for laptops. It's just too cramped right now.
- [ ] Add preference for scroll and movement speed, make it smarter
- [ ] ~~Fade potential connections as a function of distance away from mouse pointer~~

**Comment by jessdtate** [comment]
For the creatematrix.  Maybe closing the ui can auotomatically uncheck the matrix?

**Comment by jessdtate** [comment]
Another possible feature is to have a preference setting for the scroll and movement speed

**Comment by jessdtate** [comment]
bug fix: info box (from the i key) doesn't close with the window x button, even when it is there.

**Comment by dcwhite** [comment]
Thanks for these
