### ISSUE TITLE
module porting reshape matrix

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1683]
### Description

there has been some recent request for this module in SR5, which is in SR4 but not working properly.  It should behave more like the reshape() function in matlab, ie, all the elements of the original matrix should be included in the final reshaped matrix if the size allows.  Padding with zeros or truncating is acceptable with a warning if the number of elements do not match the output size.

Refer to the module Module Generation Document (https://github.com/SCIInstitute/SCIRun/tree/master/src/Documentation/Manuals/SCIRun5ModuleGeneration) and the Module Conversion guide (https://github.com/SCIInstitute/SCIRun/wiki/Module-Conversion-Steps).

**Comment by dcwhite** [comment]
@collint8 @jessdtate Are you guys going to work on this one this month?
