### ISSUE TITLE
New module idea CreateStandardMatrix

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1684]
This is an idea for a new module similar to CreateMatrix.  It would be nice to be able to make some of the standard matrices of any size, ie, a matrix of size nxm of ones, zeros, nans, or an identity matrix.  This could be made to make a 100x100 matrix of ones more easily than using CreateMatrix

Refer to the module Module Generation Document (https://github.com/SCIInstitute/SCIRun/tree/master/src/Documentation/Manuals/SCIRun5ModuleGeneration) and the Module Conversion guide (https://github.com/SCIInstitute/SCIRun/wiki/Module-Conversion-Steps).

**Comment by dcwhite** [comment]
@collint8 @jessdtate Are you guys going to work on this one this month?

**Comment by jessdtate** [comment]
also a series matrix, ie, 1,2,3,4,..., or 2,4,6,..., etc
