### ISSUE TITLE
Upgrade boost and python externals to the latest versions

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1688]
- [x] Boost: 1.67
- [x] Python: 3.6.5

**Comment by jessdtate** [comment]
python 3.4 is not supported in Matlab 2018a

**Comment by dcwhite** [comment]
Boost: Windows build is on 1.67. Mac/Linux needs to wait until I figure out the Python build.
Python: had trouble building 3.6+ on Mac 10.10, and couldn't build a package on 10.12, so I thought we could try an experimental option to choose Python version when building from source.

**Comment by dcwhite** [comment]
Let's try to get Windows Python up to 3.7. We don't want to require VS2013 anymore

**Comment by dcwhite** [comment]
In progress

**Comment by dcwhite** [comment]
Xcode 12/Clang 12 build fails in Boost. Really need this upgrade on Mac.

**Comment by dcwhite** [comment]
https://github.com/Microsoft/vcpkg/issues/4497
