### ISSUE TITLE
new trigger for start scirun

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1693]
We could use a trigger event for the start of scirun.  One key application would be to set the python path variable at the beginning of each session automatically.

**Comment by jessdtate** [comment]
Would it be easier to just have the python path as a preference than to add a new trigger?  it would probably be easier for the user.

**Comment by dcwhite** [comment]
It's similar amount of work so I'll just add both.

**Comment by dcwhite** [comment]
Actually, the user will want to edit the python path carefully, so I'll just implement the triggered script method. Editing the path list in a basic Qt widget will be more error-prone.
