### ISSUE TITLE
ospray improvement ideas

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1695]
- [x]  camera orientation based on center of scene
- [ ] text line for additional parameters like InterfaceWithTetgen (or a string input)
- [x] increase max number of frames 
- [x] expose lighting options
- [x] enable streamline visualization
- [x] allow for multiple instances of module (currently crashing)
- [x] user set location and filename of saved images

**Comment by dcwhite** [comment]
All good. One question: "increase number of frames"--do you mean the default value in the UI, or something else?

Also, I was thinking of
- [ ] Camera position as matrix input from ViewScene (which will need a new matrix output)
- [ ] Dynamic port for multiple trisurf inputs
- [ ] Dynamic port for multiple colormaps
- [ ] Separate dynamic port for streamlines--not sure what format it will be yet

I'm sure I'll think of more.

**Comment by jessdtate** [comment]
For the frames, mostly the max number in the ui.  I still get grainy images with the max value.  I updated the list

**Comment by jessdtate** [comment]
Those suggestions are good.  I was focusing on mostly easy things (hopefully)

**Comment by dcwhite** [comment]
And of course:
- [ ] Improve (nonexistent) documentation

**Comment by moritzdannhauer** [comment]
Some more ...
- Interactive mode: each time you click on a control widget (changing camera location and direction) or some mouse command it runs the renderer and plots the result - like in ViewScene (and with a direct pipeline to the renderer without loading from disc) ... is that feasible?
- maybe there is trick that I do not know about but the rendering of potential distributions has not been very good in SCIRun-ViewScene (i.e., smooth equipotential lines using maybe b-splines) - maybe ospray can do better

**Comment by dcwhite** [comment]
I'll split off a "Part 2" for this one. Right now I have a separate port for streamline meshes, but the ospray code is very similar so I can probably lump those two dynamic ports into one. Thoughts?
