### ISSUE TITLE
complex number support, norm squared

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1699]
### Description

The norm of the complex matrix and a field with complex data seems to be the squared norm.  This is not as obvious with the reportcomplexmatrixinfo because it doesn't show the norm, but the values of the min and max.  

### Steps to Reproduce

1. create a field with createlatvol
2. create complex matrix of a single value with magnitude other than one, ie, (1,1)
3. use reportfieldinfo or rescalecolormap to report field max min.  

**Expected behavior:** 

max min should be the correct norm for the complex number. for (1,1) it should be 1.4142.

**Actual behavior:** [What actually happened]

max min  is the square of the norm. for (1,1) it is 2.

### Versions

scirun v5.0-beta.N-205-g116a9b682
os x 10.12

**Comment by danielcwhite** [comment]
Oops, std::norm returns the squared norm:
http://en.cppreference.com/w/cpp/numeric/complex/norm
