### ISSUE TITLE
ViewScene memory leak

### ISSUE THREAD

**Issue by pip010** [SCIInstitute/SCIRun#1702]
Please follow these instructions for your issue to be worked on:

### Prerequisites

run latest scirun5 from github

### Description

Rendering seems to cause memory leaks. Opening and then Closing the main render window of the ViewScene window with moderate/big triangular surface/volume lead ultimately to running out of RAM.

### Steps to Reproduce

1. Open some moderate to big data set of volumetric tets data (for FEM)
2. Use ShowField using triangles only
3. Open and then close the render windows from ViewScene module (repeat till you run out of memory)

**Expected behavior:** 

Memory to be released after closing of the qt window.

**Actual behavior:** [What actually happened]

Memory is not released and each new opening of the render window causes the same amount of memory to be allocated again.

### Versions
v5.0-beta.N-165-g08040da30

**Comment by dcwhite** [comment]
This is kind of a duplicate but it has a better description than previous versions of this problem. I'll take a look.

**Comment by jessdtate** [comment]
IBBM network: /usr/sci/projects/cibc/IBBM/2017/Scientific_Visualization/nets/Heart_visualization.srn5 should be a good example to test this out.

**Comment by pip010** [comment]
I tried profiling with valgrind, but it kills the app just after dragging the ViewScene module on the workspace. :/

**Comment by dcwhite** [comment]
Closed via #1731
