### ISSUE TITLE
ViewScene Crash when Connecting ShowField Pipeline

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/SCIRun#1715]
### Prerequisites

Did a SCIRun update and build on Friday 13, Oct, 2017. 

### Description

ViewScene causes SCIRun to crash when attempting to connect the pipeline from a ShowField that has already been executed. It does not appear to have an issue if the entire network has not yet been executed. 

Error: line 4:  4487 Bus error               (core dumped) ./SCIRun

### Steps to Reproduce

1. Create a ReadField -> ShowField -> Viewscene 
2. Execute the network.
3. Delete the Pipeline from the ShowField and attempt to reconnect. 
4. SCIRun crashes

**Expected behavior:** It is expected that you can reconnect the pipeline between ShowField and ViewScene modules without crashing. 

**Actual behavior:** Crashed SCIRun

### Versions

v5.0-beta.Q
CentOS 7

**Comment by dcwhite** [comment]
I'll need more info:
- [ ] GPU specs and drivers
- [ ] Screenshot of before/after crash (to show working ViewScene--i.e. not "red ViewScene")
- [ ] More specific CentOS version number
Thanks!

**Comment by kgillette** [comment]
OS: CentOS Linux release 7.4.1708 (Core)

GPU specs and drivers (output from lspci -vnn | grep VGA -A 9):
03:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK110 [GeForce GTX TITAN] [10de:1005] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation GeForce GTX Titan [10de:1035]
	Flags: bus master, fast devsel, latency 0, IRQ 77, NUMA node 0
	Memory at dd000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=128M]
	Memory at d8000000 (64-bit, prefetchable) [size=32M]
	I/O ports at 8000 [size=128]
	[virtual] Expansion ROM at de000000 [disabled] [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
--
0a:00.0 VGA compatible controller [0300]: Matrox Electronics Systems Ltd. G200eR2 [102b:0534] (prog-if 00 [VGA controller])
	Subsystem: Super Micro Computer Inc Device [15d9:0665]
	Flags: medium devsel, IRQ 19, NUMA node 0
	Memory at db000000 (32-bit, prefetchable) [size=16M]
	Memory at df000000 (32-bit, non-prefetchable) [size=16K]
	Memory at de800000 (32-bit, non-prefetchable) [size=8M]
	Capabilities: <access denied>
	Kernel driver in use: mgag200
	Kernel modules: mgag200

Screen Shot before crash:
![before_crash_viewscene](https://user-images.githubusercontent.com/12956701/31713806-c71564a4-b3ff-11e7-9a38-5dc81ce24d2f.png)

**Comment by dcwhite** [comment]
What kind of field is it? Does it crash every time this way? Coming soon is a new "verbose" version of the renderer that you'll probably need to wait for, since I don't have much to go on here (or have CentOS and Titan gpus...)

**Comment by kgillette** [comment]
The field is a point cloud. I haven't tested it with other field types, but will let you know when I do. I didn't start getting this issue until a recent pull and update for SCIRun so maybe it was a recent commit to ShowField or ViewScene? I'm happy to wait until the new verbose version comes. 👍

**Comment by dcwhite** [comment]
@kgillette Is this still happening? Sorry this issue kind of got lost. We did just fix a major ViewScene bug, so you might try building the latest code.
