### ISSUE TITLE
TMScoil combine to one module

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1733]
the TMS coil modules should be combined into one to make it easier to use.  The modules share the same algorithm so it should be a matter of creating a ui that will work for the three cases. 

There shouldn't be units hard coded into the UI either.  This could be a text box with state variables, even though they aren't needed for computation.  My recommendation is to not have them at all and to make sure that the documentation is clear about this.  The documentation approach fits into the rest of scirun.  

Documentation will therefore be needed for these modules. Currently links to brainstimulator, which doesn't currently have documentation about these modules.

**Comment by dcwhite** [comment]
To this I am going to add: 
- [ ] Remove `assert`s in new algorithm code. Use exceptions instead.

**Comment by pip010** [comment]
Indeed the three modules can go into one with a combobox selecting the mode : thing wire or magnetic dipoles. 

Not sure what you mean by hard-coded units in the UI, you mean the defaults ?

Some can de removed, as the current and outer distance etc..

**Comment by dcwhite** [comment]
Closed via https://github.com/SCIInstitute/SCIRun/pull/1740#event-1392546292
