### ISSUE TITLE
Python -s option not accepting arguments

### ISSUE THREAD

**Issue by johaenns** [SCIInstitute/SCIRun#1759]
#1605 is not resolved.

Steps:

Call SCIRun -s anyscript.py arg1

Result:

-normal build
[PYTHON] Python 3.4.3 (default, Mar 20 2018, 14:57:40) 
[GCC 4.8.5] on linux
Please note all args after script file name will be passed to python and not SCIRun!
[2018-03-22 17:08:49.533] [root] [error] File load failed (arg1): null xml returned.

-headless build
Please note all args after script file name will be passed to python and not SCIRun!
[SCIRun] RUNNING PYTHON SCRIPT: "anyscript.py"
[SCIRun] Attempting load of arg1
[SCIRun] File does not exist: arg1

Expected result:
SCIRun runs the script and passes arg1 as an argument.

opensuse leap 42.3, SCIRun v5.0-beta.S.

**Comment by dcwhite** [comment]
Thanks, I will work on this tonight.

**Comment by dcwhite** [comment]
Looks like the problem is Linux-only. I kept "fixing" it on OSX. I'll try to get it fixed tomorrow.

**Comment by dcwhite** [comment]
I couldn't replicate on Win10 Ubuntu--perhaps it's OpenSUSE only. This will have to wait until I'm back next week when I can run my VM.

**Comment by dcwhite** [comment]
@johaenns Still can't replicate this on OpenSUSE. Please try the latest build. I'm building headless too to see if that makes a difference.

**Comment by dcwhite** [comment]
Also works in headless build mode. If it's still broken on your machine, you'll have to send me your script, or I'll need to debug on your machine directly.

**Comment by johaenns** [comment]
I couldn't reproduce it anymore either, I assume it's fixed.

**Comment by dcwhite** [comment]
OK!
