### ISSUE TITLE
ESC clears interface

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#1760]
### Description

When in the UI of any module, if you hit the ESC key the content of the UI panel becomes a blank panel for that module. This persists if the UI is closed and opened again and has been tested across several modules (specifically ShowField, ReadField, ClipFieldByFunction). This also persists if you hit ESC again, either inside or outside of the UI, or if you minimize/doc/or move the UI window. Running the module also does not fix it. If the UI window is already docked then pressing ESC has no effect on it. If you save the network, close, then reopen the problem is resolved as long as you do not hit ESC again when viewing a UI. Other instances of the same module are not affected and the module still functions when run. 

### Steps to Reproduce

1. Create any network.
![image](https://user-images.githubusercontent.com/38257234/38569481-a0698b78-3ca8-11e8-8ae1-b1fdc98eb251.png)

2. Open the UI of any of the modules (ex: the GetDomainBoundary module)
![image](https://user-images.githubusercontent.com/38257234/38569568-d79e82ec-3ca8-11e8-9277-22c74622cdc7.png)

3. Hit the ESC key while in the UI.
![image](https://user-images.githubusercontent.com/38257234/38569614-fa06676e-3ca8-11e8-8396-7db50e84d204.png)

**Expected behavior:** Upon pressing ESC while in a UI panel it was expected that either the panel would close or nothing would happen.

**Actual behavior:** The UI panel is blanked irreversibly and either a new module must be instantiated or the network must be closed and reopened.

### Versions
v5.0-beta.S-4-gb22e1f1
macOS Sierra V. 10.12.6

**Comment by dcwhite** [comment]
I think I know what's going on. It's funny this has not been caught until now. Should be fixed in next release.
