### ISSUE TITLE
"Look Down Axis" not working correctly

### ISSUE THREAD

**Issue by johaenns** [SCIInstitute/SCIRun#1779]
### Description

The "Look Down Axis" feature in ViewScene is not working correctly under linux.

### Steps to Reproduce

1. Visualize some structure for which you can easily identify the orientation.
2. Try to orient it using the "Look Down Axis" feature. For some combinations of "Look Down Axis" and "Up Vector" it will work correctly, while for others it won't.

### Versions

Opensuse Leap 42.3, SCIRun v5.0-beta.S-41

**Comment by dcwhite** [comment]
I replicated this, and it's a general issue. I will clean up the logic and improve the widget.

**Comment by dcwhite** [comment]
This is an issue again! Probably due to camera fixes.

**Comment by dcwhite** [comment]
This should be fixed BEFORE Qt4 tag is made
