### ISSUE TITLE
ReportFieldInfo Scalar Output ports not functional

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1789]
### Prerequisites

Version: v5.0-beta.T-105-gf977b8056

### Description

[Description of the bug or feature]

The scalar output ports of ReportFieldInfo do not output a scalar and cannot be used currently. 

### Steps to Reproduce

1. Create a field with a module (such as CreateLatVol)
2. Pipe the field into "ReportFieldInfo"
3. Pipe one of the scalar output ports into "ConvertScalarToMatrix"

**Expected behavior:** 
A scalar value is output from ReportFieldInfo

**Actual behavior:**
STARTING MODULE: ConvertScalarToMatrix:0
ERROR: Wrong datatype on port Input; expected class SCIRun::Core::Datatypes::Scalar but received class boost::shared_ptr

**Comment by dcwhite** [comment]
I think this is because there are different class types for different scalar types (int, double, etc) and ConvertScalarToMatrix expects a Double but ReportFieldInfo sends out an Int. @jessdtate made an issue about this general problem, which is still open. I will get it working somehow.
