### ISSUE TITLE
RBF -- Port RadialBasisFunction 

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/SCIRun#1790]
Would love the SCIRun4 RBF function to be ported to SCIRun5.

**Comment by dcwhite** [comment]
`MapFieldDataOntoNodesRadialBasis` is the module being requested.

**Comment by dcwhite** [comment]
@wgood I've started this one. Could you please upload a test network for this module in SCIRun 4? There are none provided in the old source. If you use small input meshes, you can zip up those and the .srn file and just attach it here. Thanks!

**Comment by wgood** [comment]
[For_SCIRun5.zip](https://github.com/SCIInstitute/SCIRun/files/2112745/For_SCIRun5.zip)

Zipped SCIRun4 implementation of RBF.

**Comment by dcwhite** [comment]
I got numerical errors in the converted code, so this will take some extra time.
