### ISSUE TITLE
Colormap files format to be compatible with Seg3D

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#1791]
The ability to import colormaps is going to be used in Seg3D and SCIRun5 currently doesn't support reading or writing colormaps. SCIRun4 uses .cmap files. SCIRun5 and Seg3D should have compatible colormap file formats going forward. We could use .cmap or we could use the Paraview .xml format. 

https://www.paraview.org/Wiki/Colormaps

**Comment by dcwhite** [comment]
@jessdtate Include this one in tomorrow's meeting?

**Comment by jessdtate** [comment]
The two formats are pretty different.  I wonder if it would be better to have a converter

**Comment by dcwhite** [comment]
Discussed today w/ @Haydelj

**Comment by RubioJr9** [comment]
What file type does Seg3D use?
Looking at color map tools, xml is the most common. There's also some that export to json, png, and css. I think xml and png would be good ones to support.

Side note: 
There's a really nice [colormap tool](https://sciviscolor.org/ColorMoves/), which exports to xml or png.
[Their site](https://sciviscolor.org/) has some good resources for picking color maps and all of them are in xml. It might be useful to put a link to their webpage in the doc for colormaps.

**Comment by dcwhite** [comment]
- [ ] Add disclaimer about point/color interpolation
- [ ] Add ReportColorMapInfo module along with popup description
