### ISSUE TITLE
missing library error

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1795]
### Description

When there is an optional build for externals, like tetgen and ospray, it would be nice if the modules still exists, but there was an error upon execute.  This would help preserve the user networks and would avoid the need for additional checks on network load.   currently, ospray modules are still added if ospray is not enabled, but there is no error, just no output.  if tetgen is not enabled, the module is missing from a network, requiring a check on module loading.

**Comment by dcwhite** [comment]
I'll figure this one out this week

**Comment by dcwhite** [comment]
Next week, I guess...
