### ISSUE TITLE
InterfacewithPython run in general context

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1817]
### Description

in the InterfaceWithPython module I would like to have a way to execute some python code in a general context, ie, straight to the python console, rather than only in the context of the IWP module.  This would be for mainly for importing some modules that don't work in the IWP context, or maybe for starting a matlab engine once for the whole network.  

I imagine that this could be an additional tab that would allow a few lines of codes, but wouldn't allow passing inputs and outputs.

**Comment by dcwhite** [comment]
I'll investigate this one today
