### ISSUE TITLE
Empty Matrix Crash

### ISSUE THREAD

**Issue by chhabragarima** [SCIInstitute/SCIRun#1824]
For GetFieldNodes module whenever an empty matrix is produced, clicking on the pipe followed by "i" leads to the crashing of SCIRun.
An Empty Matrix could be generated by ReportFieldGeometryMeasures of a cloud point when trying to output the result for "Edges". 
Find an Example network below:
[EmptyMatCrash.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/2250348/EmptyMatCrash.srn5.zip)

**Comment by dcwhite** [comment]
Good catch. I can replicate. I'll fix it today
