### ISSUE TITLE
Transparency Minimum Value not set for Nodes.

### ISSUE THREAD

**Issue by chhabragarima** [SCIInstitute/SCIRun#1832]
In transparency for faces is set to some minimum value while it is not set for Nodes. This leads to the generation of very transparent views which are hardly visible.
One way of generating it would be setting the Field Output Basis Type to Linear in CreateFieldData module.
Attached is a network that illustrates the same.
[Transparency Inconsistency.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/2284820/Transparency.Inconsistency.srn5.zip)

**Comment by dcwhite** [comment]
@Haydelj @RubioJr9 Could one of you see if this is still an issue?

**Comment by dcwhite** [comment]
@Haydelj will investigate. Probably closable.

**Comment by Haydelj** [comment]
@dcwhite I'm not seeing anything like what's described above in the provided network

**Comment by dcwhite** [comment]
I think this is the right picture. I changed face coloring to Default, with the value as is at 0.01. I suppose this is how it's supposed to look, so I don't know what the "fix" would be.
![image](https://user-images.githubusercontent.com/1399383/70262986-999a3a00-1752-11ea-86db-9bec651fd123.png)

**Comment by Haydelj** [comment]
Yeah, that's just the correct behavior of rendering this mesh with low opacity. The fix would be to increase the opacity and/or render only the surface of the mesh
