### ISSUE TITLE
Error building SCIRUN

### ISSUE THREAD

**Issue by vnckppl** [SCIInstitute/SCIRun#1840]
Hi all,

When I build SCIRUN I receive the following error:

> Scanning dependencies of target ospTutorial
> [ 98%] Building C object ospray/CMakeFiles/ospTutorial.dir/__/apps/ospTutorial.c.o
> [ 99%] Linking C executable ../ospTutorial
> ../libospray_common.so.1.6.1: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
> collect2: error: ld returned 1 exit status
> ospray/CMakeFiles/ospTutorial.dir/build.make:98: recipe for target 'ospTutorial' failed
> make[5]: *** [ospTutorial] Error 1
> CMakeFiles/Makefile2:256: recipe for target 'ospray/CMakeFiles/ospTutorial.dir/all' failed
> make[4]: *** [ospray/CMakeFiles/ospTutorial.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make[3]: *** [all] Error 2
> CMakeFiles/Ospray_external.dir/build.make:112: recipe for target 'Externals/Stamp/Ospray_external/Ospray_external-build' failed
> make[2]: *** [Externals/Stamp/Ospray_external/Ospray_external-build] Error 2
> CMakeFiles/Makefile2:734: recipe for target 'CMakeFiles/Ospray_external.dir/all' failed
> make[1]: *** [CMakeFiles/Ospray_external.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> Building SCIRun returned an error
> 
> Either the code failed to build properly or
> 
> the testing programs failed to complete without
> 
> every single test program passing the test.

**Some details:**
Source file: https://github.com/SCIInstitute/SCIRun/archive/v5.0-beta.IBBM2018.tar.gz
Environment: Debian GNU/Linux 9.1 (stretch) (GNU/Linux 4.9.0-3-amd64 x86_64)

How can I fix this?

Thanks!

**Comment by dcwhite** [comment]
Download the latest code zip from the github project home page, as master branch is updated to fix this. Or turn off BUILD_OSPRAY in the cmake settings.
