### ISSUE TITLE
Sumientra issues

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1846]
> I’ve been trying to convert my SCIRun 4 networks to SCIRun 5. Generally it works. Most modules can be easily converted. What’s weird is that none of the module settings are converted, even though the importLog does show an entry for each setting. This is manageable though.

- [x] We're have experimental code written to convert a lot of the module settings. It's waiting on the compiler upgrade that's going on now.

> The main problem is that running anything in 5 is very slow. All modules seem to take much longer than I’m used to. I timed it for a simple network, ran identical nets in 4 and 5, and it was 12 vs 24 seconds. I also get a lot of spinning wheel, just for trying to open a module GUI. 

- [x] Would you be able to share the slow networks and data? That would help with debugging.

> And visualizing a full head mesh (4M elements) is almost impossible; it takes several minutes of spinning wheel for ViewScene to show the mesh, and then the wheel pops back up every time I even touch the ViewScene window (or anything else really). Visualizing a surface or a very small volume mesh does work. Is there anything I can change to improve this? I installed this: SCIRun-5.0.beta.CinC2018-macOS.pkg.

- [x] In general we've seen faster rendering in 5. What is your graphics hardware?

> The Matlab import modules work well. Being able to search for a file through the standard Mac interface is bliss. Only issue is that after opening a file, the module does not show the available fields, so you first have to run the module (causing the entire network to run and crash) in order to see the fields and select which field you want to load on each port. It would be great if this could be fixed.

- [ ] There are workarounds for this, I will check out that module to see if there is a slicker way.

> I have some more questions:
> 
> It seems that many of the ViewScene settings cannot be saved. Location of the window and orientation of the scene, but also some of the settings that can be un/checked in the Settings popup. It all resets when loading the network, and I cannot find any of these settings in the html file. Is this correct?

- [x] That's also a known problem, and I will raise the importance of the corresponding issue.

> Since I need to be able to run SCIRun from command line, I also downloaded the source. It seemed to build OK, though it gives a string of ‘warning: this version of Mac OS X is unsupported’, while I’m on 10.10.5 and the website says it’s tested for 10.8-10.11. 

- [x] We need to update the website doc for supported OS versions, since it's been a while. I might be dropping 10.10 at some point soon, probably after 10.14 comes out.

> The result (/bin/SCIRun/SCIRun_test) does open normally, but I can’t access the menu, so can’t insert any modules. 

- [x] This is known and annoying, only in the `_test` version--(as mentioned in Sim-Est,) just click away from the SCIRun_test window, then click back, and the menus work. 

> I can load a network, but then SCIRun crashes, giving error messages about the data and mesh sizes not matching (there’s nothing wrong with the inputs; the networks I loaded run without issues on the .pkg version). 

- [x] As above, if you can attach zipped networks to this issue (github won't like the srn5 file, but can take a zip of anything), and links to data (if large), I can debug these.

Thanks for testing!

**Comment by Sumientra** [comment]
> Would you be able to share the slow networks and data?  

File was too big, so uploaded to [Google Drive](https://drive.google.com/open?id=1ANeyt0yPtqENvre3f5FDHjVsdzx5-ISr). It contains two network files (identical networks in .srn and .srn5), plus one mesh file (model.mat) and one data file (data.mat) that the nets will load. If I set the ClipField to Y>200, both sr4 and sr5 will run without problems, but sr5 takes ~3x longer. If I set ClipField to Y>50, sr5 will take ~4x longer than sr4, but gets stuck after it finishes executing. 

> What is your graphics hardware?

<img width="337" alt="screen shot 2018-10-30 at 01 21 58" src="https://user-images.githubusercontent.com/20671873/47697618-40bcb180-dbe2-11e8-8950-e0aad0f007da.png">

> There are workarounds for this, I will check out that module to see if there is a slicker way.

The way sr4 does it works well.

> I might be dropping 10.10 at some point soon, probably after 10.14 comes out.

Makes sense. I switched back to Yosemite after having a lot of issues with High Sierra, one of which being that if I'd open multiple instances of sr4 (which I do a lot) one would crash. Apparently it was a known problem with that OS. I'm gonna be forced to upgrade soon. Hoping Mojave is better.

> As above, if you can attach zipped networks to this issue.

The same network in the link above also crashes my source build. Although it seems now that anything crashes it; inserting any module that I tried crashed it. The trick with the menu worked :)

**Comment by dcwhite** [comment]
How much RAM do you have? With `Y>50` v5 is using around 8GB.

**Comment by Sumientra** [comment]
Visualization of a mesh looks different (worse) in SCIRun 5 compared to SCIRun 4. See screenshot. This is the same model in SCIRun 5 (left) and 4 (right).

![screen shot 2018-10-01 at 7 34 29 pm](https://user-images.githubusercontent.com/20671873/48463445-00486080-e7aa-11e8-8fd5-f18883ddcf66.png)

**Comment by Sumientra** [comment]
> How much RAM do you have? With `Y>50` v5 is using around 8GB.

Sorry. Didn't see this. It's 16 GB.

**Comment by dcwhite** [comment]
Are edges turned on in v5?

**Comment by Sumientra** [comment]
> Are edges turned on in v5?

Nope. Same settings. Here's another screenshot of what it looks like with edges on. 
It looks like this on both my (old) MacBook and Mac Pro, and also on Kimia's (new) MacBook.

![screen shot 2018-11-14 at 2 34 26 pm](https://user-images.githubusercontent.com/20671873/48507726-b9468380-e81a-11e8-8fb2-88feb7f5b5f5.png)

**Comment by dcwhite** [comment]
I'll parse through this one and make new issues for follow-up soon.
