### ISSUE TITLE
Toggle background on and off (holiday special)

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/SCIRun#1853]
Please follow these instructions for your issue to be worked on:

---
### If all prerequisites are met, just delete that text as well. If they're not all met, the issue will be closed or assigned back to you.
---
## For features, fill in the description section and delete the rest. Be as descriptive as possible.
---

### Description

I personally love the easter eggs present during the holidays (i.e. the wallpaper changing in the background). Unfortunately, some reviewers do not like the images of skiing Santas or turkeys in their journals in a submission completed over the holidays. Is there a way to turn off the background wallpaper during the holidays? Obviously, the default on startup should always be "on" but in the rare instance I would like to turn it off could a feature be built in to accommodate that (i.e. checkbox in preferences)?

**Comment by dcwhite** [comment]
I decided not to post a sarcastic response about students needing to work on papers over the holidays. Instead, how about I add a menu option for this and get it pushed today.

**Comment by dcwhite** [comment]
Here is the new checkbox for "professional-mode":
![image](https://user-images.githubusercontent.com/1399383/51207737-ebcb3600-18c8-11e9-8a62-33b4ecc2853c.png)

**Comment by bzenger** [comment]
Thanks Dan! 

Best, 
Brian
