### ISSUE TITLE
OS X python installation installs in Applications folder

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1858]
### Description

installing scirun with python installs python in the applications directory in OS X.  This may be related to the conflict seen when there is a previous installation.  Should be able to delete the installation step from make file 

### versions
v5.0-beta.CinC2018-87-g7ad250e
OS X 10.10 , 10.12, 10.14

**Comment by dcwhite** [comment]
My local test of this on Mac 10.10 shows it's fixed. Tomorrow I'll test my other systems.
