### ISSUE TITLE
More than 10 GenerateSinglePointProbeFromField Widgets behaves abnormally

### ISSUE THREAD

**Issue by jansonap** [SCIInstitute/SCIRun#1871]
### Description

Having a singlepointprobe widget with ID: 1 and ID:10+ links the two modules together. Moving the pointprobe widget in the viewscene with ID:10 also moves the widget with ID: 1 when they are both connected to the viewscene.

### Steps to Reproduce

1. Add 11 "GenerateSinglePointProbeFromField" modules in a new scirun network.
2. Connect the pink port of the modules with ID: 1 and ID: 10.
3. Shift+Click and drag the widget corresponding to ID: 10

**Expected behavior:** Only ID: 10 widget should move in space

**Actual behavior:** Both ID: 1 and ID: 10 widget move in the viewscene window

### Versions
v5.0-beta.V.RC1

**Comment by dcwhite** [comment]
Probably a regex matching problem. I will take a look this week.
