### ISSUE TITLE
Streamline Distance from Seed does not compute geodesic accurately

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/SCIRun#1877]
Using Test Network:
-there is a network and an input file. 

'Distance from seed' should sum the inter-node distances along the streamline with the final node having a value equal to the value given for that streamline if the 'Streamline Length' option is selected.  Presumably, streamline length is the total geodesic length, but even if it is euclidean we wouldnt expect that the geodesic would report a value a magnitude higher (85 versus 3500 mm). 

I expect it is summing inter-node distance up to each point and then adding it to the sum of the previous node rather than calculating the inter-node between the previous point and itself and adding that to the previous geodesic. 
[Streamline_Tester.zip](https://github.com/SCIInstitute/SCIRun/files/2891853/Streamline_Tester.zip)

### Versions

Running on Yosemite. 

Version#: v5.0-beta.IBBM2018rc2 (a little outdated but problem is still probably valid)

**Comment by wgood** [comment]
Went in and manually calculated and geodesics per streamline and the values agree with 'Streamline Length', so that value is seemingly correct although the values different slightly (i assume that may be a compounded rounding error)

**Comment by dcwhite** [comment]
Yes, the code is reusing the same variable for the different types of lengths this module computes, and mistakenly added the internode length on top of the precomputed total length. Should be easy fix.

**Comment by dcwhite** [comment]
I found another problem when running with just one seed point. I'll need to track that down too.

**Comment by dcwhite** [comment]
I believe I have fixed the distance-from-seed computation, but the problem with the first seed point going haywire is screwing up the min/max result of distance from seed when comparing the output of ReportFieldInfo. I'll need to debug this more next week.

**Comment by dcwhite** [comment]
[danSL.zip](https://github.com/SCIInstitute/SCIRun/files/2896107/danSL.zip)
