### ISSUE TITLE
getslicefromstructuredfield crashes when slice is out of range

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1880]
### Description

getslicefromstructuredfield will crash with the included network file.  The data file is from the SCIRunData file from scirun 4. the crash is related to tensors and changing the input volume size so that the selected slice is out of bounds.  I haven't been able to reproduce with data generated from a latvol. 

[glyphs_test_III.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/2921456/glyphs_test_III.srn5.zip)

Thread 21 Crashed:
0   libCore_Geometry_Primitives.dylib	0x0000000108d28722 SCIRun::Core::Geometry::Tensor::Tensor(SCIRun::Core::Geometry::Tensor const&) + 82
1   libCore_Datatypes_Legacy_Field.dylib	0x0000000107c21aa9 SCIRun::VFDataT<SCIRun::Array3<SCIRun::Core::Geometry::Tensor>, std::__1::vector<SCIRun::Core::Geometry::Tensor, std::__1::allocator<SCIRun::Core::Geometry::Tensor> >, std::__1::vector<std::__1::vector<SCIRun::Core::Geometry::Tensor, std::__1::allocator<SCIRun::Core::Geometry::Tensor> >, std::__1::allocator<std::__1::vector<SCIRun::Core::Geometry::Tensor, std::__1::allocator<SCIRun::Core::Geometry::Tensor> > > > >::get_value(SCIRun::Core::Geometry::Tensor&, long long) const + 57
2   libModules_Legacy_Fields.dylib	0x0000000104a1878e SCIRun::Modules::Fields::GetSliceFromStructuredFieldByIndices::execute() + 17230
3   libDataflow_Network.dylib     	0x000000010598df7b SCIRun::Dataflow::Networks::Module::executeWithSignals() + 619
4   libInterface_Application.dylib	0x0000000102c2029f non-virtual thunk to SCIRun::Gui::ModuleWidget::executeWithSignals() + 79
5   libEngine_Scheduler.dylib     	0x000000010427a24d SCIRun::Dataflow::Engine::DynamicExecutor::ModuleExecutor::run() + 285
6   libCore_Datatypes_Legacy_Field.dylib	0x0000000107d6b01f boost::(anonymous namespace)::thread_proxy(void*) + 47
7   libsystem_pthread.dylib       	0x00007fff92b0293b _pthread_body + 180
8   libsystem_pthread.dylib       	0x00007fff92b02887 _pthread_start + 286
9   libsystem_pthread.dylib       	0x00007fff92b0208d thread_start + 13

### Steps to Reproduce

1. create a network to with getslicefromstructuredfield with higher resolution nrrd with dti data
2. set slice value to max slice number
3. change input file to lower resolution DTI nrrd

**Expected behavior:** [What you expected to happen]

error, or change slice to max of volume

**Actual behavior:** [What actually happened]

crash

### Versions
os x 10.12
v5.0-beta.V.RC1-19-g4ed754a57

**Comment by dcwhite** [comment]
Next week

**Comment by dcwhite** [comment]
Uhh...next week again
