### ISSUE TITLE
ExportFieldsToMatlab crashes

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#1887]
### Description
SCIRun crashes when a port is connected to ExportFieldsToMatlab. This happens in any network and regardless of whether the output file is defined.

### Steps to Reproduce
1. In a new network file, insert a ReadField module.
2. Insert ExportFieldsToMatlab module.
3. Connect output of RF to input of EFTM.

**Expected behavior:** Port should connect.

**Actual behavior:** SCIRun crashes.

### Versions
v5.0-beta.CinC2018+Qt4

**Comment by dcwhite** [comment]
I replicated this and a fix will be easy. This is a weird one though, in that I introduced some code that would crash on new instances, but the old networks with this module still worked fine. I'll have to think about a better testing routine to catch these sort of things.
