### ISSUE TITLE
Display axis glyph at Cartesian origin

### ISSUE THREAD

**Issue by ajanson** [SCIInstitute/SCIRun#1890]
SCIRun 4 had the option to display the axis glyph at 0,0,0 in world space with arrow glyphs that were one unit in length. I would like this option to exist in v5. What is really missing is any representation of the origin in world space to help with scale and positioning in the ViewScene. 

See a similar issue [#1435](https://github.com/SCIInstitute/SCIRun/issues/1435) that places an axis glyph on the screen but not in the world.

**Comment by jessdtate** [comment]
One of the things that can replicate this functionality is to create a field with six points at the origin with the various unit vectors, then use ShowFieldGlyph.

**Comment by dcwhite** [comment]
A module can be written to create this and output it. "CreateAxisField?"

**Comment by jessdtate** [comment]
Yeah, that's a good way to implement it.

**Comment by dcwhite** [comment]
Will discuss at next week's meeting
