### ISSUE TITLE
re-execution logic executes all modules

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1891]
### Description

rexecution seems to reexecute all modules, regardless of the inputs or parameters changing.  This indicates that the need to execute is not computing properly. Execute downstream only also mostly reexecutes the entire network, both when the button is pressed in the module ui, or when auto execute is on.  This is a bit tricky because it is only noticeable when the module takes longer than a second to execute.  Also, there are times when reexecute downstream only does not execute all the modules.  

[reexecute_branches.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/2989664/reexecute_branches.srn5.zip)
This network shows that reexcute downstream is inconsistently applied.  Reexecuting downstream the left showfield (showfield:1) will reexecute all the showfields.  However, reexecuting the either of the other two showfields (showfield:0, showfield:2) will exclude showfield:1.  

[reexecute_branches_matrices.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/2989796/reexecute_branches_matrices.srn5.zip)
This network further illustrates the reexecution by providing a counter for the number of times the collect matrices is executed.  It highlights that there is something wrong with the backtracking because it backtrack 2 or 3 modules before executing downstream.

**Comment by dcwhite** [comment]
For the first one, that happens even without ViewScene in the network; quite bizarre. But I can make a unit test for it. There's definitely some "holes in the graph" as far as execution dependency. This will be my next issue!

**Comment by dcwhite** [comment]
@jessdtate Can you reupload the second network with some explanatory notes attached, since there is a lot going on there.

**Comment by ajanson** [comment]
Here is an example network that triggers the re-execution of tetgen although only the two modules above tetgen should ever trigger the need to re-execute. Executing (ShowField:0) or (SetFieldDataToConstantValue:0) which are either parallel or downstream of (InterfaceWithTetgen:0) will always trigger a re-excution of tetgen.

[re-execution_problem.zip](https://github.com/SCIInstitute/SCIRun/files/2997919/re-execution_problem.zip)

**Comment by jessdtate** [comment]
[reexecute_branches_matrices_annotated.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/3011494/reexecute_branches_matrices_annotated.srn5.zip)
Here is the annotated version of the network.
