### ISSUE TITLE
Module help documention links to older wiki

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1894]
by default, link goes to old wiki, should default to new one.

**Comment by dcwhite** [comment]
Changing the C++ is easy. I need to update the javascript on the main new module wiki page, so that the block opens up on load. Here's one way to do it: https://stackoverflow.com/questions/16368129/how-to-make-the-page-load-to-an-anchor-tag

**Comment by dcwhite** [comment]
Then there are mistakes like this that need to be cleaned up:
![image](https://user-images.githubusercontent.com/1399383/55112882-3aecce80-50a3-11e9-8963-66b175e51290.png)

Who can we get to test all the links out?

**Comment by jessdtate** [comment]
we can have a documentation lunch, or get another intern, perhaps.

**Comment by dcwhite** [comment]
@jessdtate This is one for @nids2001

**Comment by dcwhite** [comment]
Let's work on this right after the docs merge.

**Comment by dcwhite** [comment]
Closed by #2336
