### ISSUE TITLE
Refactor SRInterface

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1897]
And related subobjects. This will follow closing of current PRs, so there are no bad merges. We'll aim to start at next Friday's meeting (3/29).

**Comment by dcwhite** [comment]
TODO list created via whiteboard picture...needs uploading

**Comment by Haydelj** [comment]
![IMG_6150](https://user-images.githubusercontent.com/28606560/55344608-072af380-546b-11e9-954f-344d153482b3.jpg)
