### ISSUE TITLE
Regular internal build channel

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1900]
Let's formalize the private build process. @SCIInstitute/butson-lab has a private Github repo. I post builds to Slack channels occasionally (which disappear very quickly nowadays). There are also SCI server locations that are web-accessible. What is everyone's favorite out of the above options? Polling these users: @SCIInstitute/cibc-users @SCIInstitute/ceg_team @SCIInstitute/scirun-users

**Comment by dcwhite** [comment]
Related: #1795 will help streamline the release build process.

**Comment by wgood** [comment]
Hey Dan,

I am partial to 'ceg_team'. Thanks for doing this.


Cheers,
Wilson

**Comment by dcwhite** [comment]
Oops, I was just tagging those groups of users to respond, those aren't poll choices listed there. Please indicate where the binaries should be placed (Slack, github, sci server), and how often builds should come (weekly, monthly, etc)

**Comment by bzenger** [comment]
Hi Dan, 

This is awesome and I would greatly appreciate this. 

As for specifics, is there a way to create a private repo under the SCI Institute organization? Then give access to that repo as needed? I would love to stay on Github considering viewing release notes, etc. 

As for timing, I would leave that up to you. I am not an expert in that but would be happy to update as frequently as possible. 

Thanks, 

Brian

**Comment by dcwhite** [comment]
The SCI github org is close to its limit of private repos right now (4 remaining). If I grab one just for binary releases with a certain GPLed meshing library, that might be a bit greedy. I don't control the distribution of those either. Although we did go from 10 to 20 at some point, so perhaps those 4 are just there for the taking.

**Comment by dcwhite** [comment]
@jessdtate informs me we got an educational license, so we have as many private repos as we want. So no greed applicable.

**Comment by bzenger** [comment]
Hi Dan, 

Great! Let’s do that then! Are there any objections from the gallery? 

Brian

**Comment by dcwhite** [comment]
Let's finalize this at tomorrow's sim-est.

**Comment by dcwhite** [comment]
PEOPLE LOVE IT. I will close this issue
