### ISSUE TITLE
Exposing the transformation matrix in register with correspondence module

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/SCIRun#1909]
**Is your feature request related to a problem? Please describe.**
I would like to be able visualize, or export, the transformation matrix that is created when you register the two point sets. This should be a 4 by 4 matrix. 

**Describe the solution you'd like**
There could be multiple solutions. I think the ideal solution is having another port coming out of the module that is a "matrix" type, and exports the 4 by 4 matrix. That way the matrix can be automatically exported. Another option is to expose the matrix calculated in the module and a person can either write it down or copy and paste it. 

**Describe alternatives you've considered**
Currently, I calculate the matrix in matlab and use that calculated matrix in other systems and for other operations. However, this is annoying and I am worried the transformation matrices are not entirely identical. 

**Additional context**
See attached files to use for the module (that actually do things!) I sent them to you on Slack.

**Comment by dcwhite** [comment]
[bzengerPoints.zip](https://github.com/SCIInstitute/SCIRun/files/3040563/bzengerPoints.zip)

**Comment by dcwhite** [comment]
Next week with @jessdtate
