### ISSUE TITLE
Binary Install Fail on Windows

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#1922]
Description:
When using a SCIRun Binary to install a windows machine error messages come up during the install process that prevent successful installation. These issues persist even if run as an administrator or in developer mode.

Screenshot of error:
![image](https://user-images.githubusercontent.com/38257234/56979091-2da98080-6b36-11e9-9445-0ce56b629a01.png)

![image](https://user-images.githubusercontent.com/38257234/56979129-44e86e00-6b36-11e9-8a81-683eb5df0e43.png)

![image](https://user-images.githubusercontent.com/38257234/56979155-516cc680-6b36-11e9-83a8-78640dc57e7d.png)

**Comment by dcwhite** [comment]
This appears to be solved by upgrading NSIS to version 3. I'll keep this open while I try to figure out how to force CPack to check for newer NSIS.

**Comment by dcwhite** [comment]
Somewhat involved to verify NSIS versions. No one had a problem at today's lunch, so I'll close.
