### ISSUE TITLE
ViewScene saved parameters are not applied when network is loaded

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1939]
ViewScene does not use the standard widget managers, so the saved state is inconsistently applied when loading saved networks. For instance, background scene color is loaded, but not fog color. We should move as much code to the standard pulling mechanism as possible.

**Comment by dcwhite** [comment]
This might be mostly fixed now, but the refactoring should still be done

**Comment by dcwhite** [comment]
@Sumientra You mentioned some options that are not being saved [here](https://github.com/SCIInstitute/SCIRun/issues/2100#issuecomment-643553186), are there any others that you know of? This one is getting bumped to next milestone too.

**Comment by Sumientra** [comment]
Here are settings that do get saved:
- zoom and rotation angles
- Render tab: scene color
- View tab: Scale bar settings do get saved, but the result is incorrect (see images below)

Here are settings that do not get saved:
- size of ViewScene window
- Objects tab: object selection
- Clipping tab: all settings
- View tab: Orientation Axes: all settings

Example image:

- What I saved:

![Screen Shot 2020-08-14 at 17 04 20](https://user-images.githubusercontent.com/20671873/90293546-5c925580-de52-11ea-9f70-2d6c9fc27cdf.png)

- What I got:

![ViewScene-0_17 10 29 906](https://user-images.githubusercontent.com/20671873/90293558-61efa000-de52-11ea-81ab-1c01e3b5fb76.png)

**Comment by dcwhite** [comment]
Super, I will get these fixed first thing in the new milestone (after Monday or so).

**Comment by dcwhite** [comment]
See also #2257

**Comment by dcwhite** [comment]
> I think we should merge it.  This is not a big deal, docked windows default to the default size and position, instead of stacking or keeping the height.  The width seems to save correctly, which is the most import parameter with the docked windows.

_Originally posted by @jessdtate in https://github.com/SCIInstitute/SCIRun/issues/2276#issuecomment-841545025_
