### ISSUE TITLE
Qt5 Support

### ISSUE THREAD

**Issue by csverma610** [SCIInstitute/SCIRun#1953]
Hello,

Can I use the software with qt5?

csv

**Comment by dcwhite** [comment]
Yes. Turn on QT5_BUILD in cmake, and then specify the Qt5 path. There are still some bugs and quirks to be fixed in the Qt5 version, see #1774, but that is future of the product. SCIRun works best with the latest Qt5, 5.12 or later.

**Comment by csverma610** [comment]
Thank you very much for the guidance. I have been trying to build the
software but I get the same error:

                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/bin/SCIRun/Interface/Modules/Render/moc_GLWidget.cpp:9:
/home/csverma/Software/System/Qt/Latest/include/QtCore/qcoreevent.h:264:9:
error: expected identifier before numeric constant
         Expose = 206,
         ^~~~~~
/home/csverma/Software/System/Qt/Latest/include/QtCore/qcoreevent.h:264:9:
error: expected ‘}’ before numeric constant
In file included from
/home/csverma/Software/System/Qt/Latest/include/QtCore/qcoreapplication.h:47,
                 from
/home/csverma/Software/System/Qt/Latest/include/QtCore/qcommandlineparser.h:45,
                 from
/home/csverma/Software/System/Qt/Latest/include/QtCore/QtCore:48,
                 from
/home/csverma/Software/System/Qt/Latest/include/QtGui/QtGuiDepends:3,
                 from
/home/csverma/Software/System/Qt/Latest/include/QtGui/QtGui:3,
                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/src/Interface/Modules/Render/ViewScenePlatformCompatibility.h:46,
                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/bin/SCIRun/Interface/Modules/Render/../../../../../src/Interface/Modules/Render/GLWidget.h:43,
                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/bin/SCIRun/Interface/Modules/Render/moc_GLWidget.cpp:9:
/home/csverma/Software/System/Qt/Latest/include/QtCore/qcoreevent.h:56:15:
note: to match this ‘{’
     enum Type {
               ^
In file included from /usr/include/X11/Xlib.h:44,
                 from /usr/include/GL/glx.h:30,
                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/src/Externals/spire/gl-platform/GLPlatform.hpp:71,
                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/bin/SCIRun/Interface/Modules/Render/../../../../../src/Interface/Modules/Render/GLWidget.h:42,
                 from
/home/csverma/SCIRun-5.0-beta.CinC2018/bin/SCIRun/Interface/Modules/Render/moc_GLWidget.cpp:9:
/home/csverma/Software/System/Qt/Latest/include/QtCore/qcoreevent.h:264:9:
error: expected unqualified-id before numeric constant
         Expose = 206,
         ^~~~~~

**Comment by dcwhite** [comment]
That should be fixed in the latest code. Try the latest tag, https://github.com/SCIInstitute/SCIRun/releases/tag/v5.0-beta.W. I need to make an official release so it shows up on the release page better.

**Comment by csverma610** [comment]
Hello Dan,

With the latest code, I got stuck with the following message:


CMake Deprecation Warning at Externals/libxml2/CMakeLists.txt:40
(CMAKE_POLICY):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Configuring spire
-- Configuring Spire Meta-library
-- Configuring Submodules
CMake Error at Externals/submodules/CMakeLists.txt:51 (message):
  The submodules were not downloaded! GIT_SUBMODULE was turned off or
failed.
  Please update submodules and try again.


-- Configuring incomplete, errors occurred!
See also
"/home/csverma/SCIRun-5.0-beta.W/bin/SCIRun/CMakeFiles/CMakeOutput.log".
See also
"/home/csverma/SCIRun-5.0-beta.W/bin/SCIRun/CMakeFiles/CMakeError.log".
CMakeFiles/SCIRun_external.dir/build.make:120: recipe for target
'download/FwdInvToolkit/Stamp/SCIRun_external/SCIRun_external-configure'
failed
make[2]: ***
[download/FwdInvToolkit/Stamp/SCIRun_external/SCIRun_external-configure]
Error 1
CMakeFiles/Makefile2:86: recipe for target
'CMakeFiles/SCIRun_external.dir/all' failed
make[1]: *** [CMakeFiles/SCIRun_external.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dcwhite** [comment]
It looks like this is a general problem with building from the source zip and using submodules, that is not quite solved yet:
https://github.com/dear-github/dear-github/issues/214

The easiest solution is to use git and just clone the repo, and then try to build. If you don't want to do that, you'll need to clone the submodules individually and make sure they're the correct versions. If you want, you can make a new issue to enable building from the zip in an easier way, without having to deal with the submodules.

**Comment by dcwhite** [comment]
This is also related to this issue, which has been around for a while: https://github.com/SCIInstitute/SCIRun/issues/902

**Comment by csverma610** [comment]
Hello Dan,

Thank you very much. You suggested approach worked and I am able to see
some examples running.

Now, I would like to explore how hard it will be extend this framework to
create my own new modules.

Regards and thanks once again.

csv
