### ISSUE TITLE
minor z fighting

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1959]
**Description**

With the autorotate feature, Z fighting can be a little more obvious.  See the video

[autorotate.mov.zip](https://github.com/SCIInstitute/SCIRun/files/3332324/autorotate.mov.zip)

**To Reproduce**
1. make a network to visualize a latvol
2. align latvol to an axis
3. autorotate along axis
4. see z fightting

**Expected behavior**
it would be nice if this was smoother

**Version**
OS X 10.12

**Comment by dcwhite** [comment]
Will discuss at next week's meeting

**Comment by jessdtate** [comment]
Edge z fighting too.  This should be easier to fix.

**Comment by jessdtate** [comment]
[edge_fighting.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/3912994/edge_fighting.srn5.zip)
