### ISSUE TITLE
split VBOs for large mesh visualization

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1968]
There are still some issues with large mesh visualization, likely due to Opengl limitations.  Meshes above 4GB VBOs will either not show in viewscene or crash scirun.  Splitting VBOs above 4GBs may allow for these large meshes to visualize even when they exceed the limit.  

This may be a good one to look at with #1956

**Comment by dcwhite** [comment]
@Haydelj Should we close this now, or wait until edges and nodes are handled the same way?

**Comment by Haydelj** [comment]
@dcwhite Let's wait for the edges and nodes
