### ISSUE TITLE
autoview takes two clicks

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1972]
**Describe the bug**

Autoview doesn't seem to be updating the to the camera position (latest master).  when autoview is selected, then the camera is rotated, the center reverts to the previous position.  

[test_two_box.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/3436984/test_two_box.srn5.zip)

**To Reproduce**

1. Open and run network with two object with different centers visualized in viewscene. (see included network)
2. turn off one object in viewscene
3. press autoview once
4. use mouse to rotate
5. now press autoview again.

**Expected behavior**

center should stay the same. 

**Screenshots**

**Version**

latest master v5.0-beta.W-116-ga3db77a43
OS X 10.12

**Comment by jessdtate** [comment]
This may be only in PR #1966.  Master just autoviews to all the objects, even if some are hidden.

**Comment by Haydelj** [comment]
I believe this one was resolved with the last couple commits to PR #1966
