### ISSUE TITLE
Cones, Arrows, and Comets sometimes do not appear on SCIRun build

### ISSUE THREAD

**Issue by RubioJr9** [SCIInstitute/SCIRun#1975]
Versions:
Mac OS 10.12.6 and 10.13.6
Beta.x

On some networks, cones, arrows, and comets do not render. Lines and needles do not have this issue. This has only been observed on the built version of SCIRun.

**Comment by dcwhite** [comment]
@jab0707 @RubioJr9 Is this a problem in the latest build?

**Comment by RubioJr9** [comment]
Yes I'm still seeing this

**Comment by dcwhite** [comment]
@wgood @jab0707 @RubioJr9 Is this a problem in Tark's latest installer?

**Comment by wgood** [comment]
Hey @dcwhite it looks like it is fixed. Thanks!
