### ISSUE TITLE
Widget selection in ViewScene doesn't work on 10.14

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1996]
@jessdtate has seen it on 10.12. From #1774

**Comment by RubioJr9** [comment]
I'm still not seeing this. 
On my imac running 10.13, I tested on a 2560x1440 and 1920x1200 monitor. 
On my macbook pro(late 2013) running 10.14, it is working and it has a 2560x1600 screen. 
The new macbook pros have the same resolution, except for the 15 inch version. I think high res doesn't have anything to do with the bug unless you both saw this on 15 inch models.

**Comment by jessdtate** [comment]
yeah, they were both 15 in.

**Comment by dcwhite** [comment]
Let's get @allywarner to test it with her 15"

**Comment by Haydelj** [comment]
The window size in relation to the recorded selection locations is chacking out. Could be a bad camera being passed in or a broken library function (either QT or OpenGL) not sure how either of those would be resolution dependant though...

**Comment by Haydelj** [comment]
I wrote some code to output the selection buffer here is what I got
Correct:
![correct](https://user-images.githubusercontent.com/28606560/66708584-d2e49980-ed0f-11e9-80be-2944efd1679b.png)
Incorrect:
![incorrect](https://user-images.githubusercontent.com/28606560/66708583-d2e49980-ed0f-11e9-9261-1ff8f60a9f99.png)

**Comment by dcwhite** [comment]
Ah, no doubt inserted to convince us to give up OpenGL on Mac.

**Comment by Haydelj** [comment]
I found something interesting about scaling. It looks like enabling scaling will actually increase the resolution output to the display. 
![Screen Shot 2019-10-14 at 3 12 36 PM](https://user-images.githubusercontent.com/28606560/66783634-8dea6f80-ee95-11e9-88a5-67bf279b2461.png)
![Screen Shot 2019-10-14 at 3 13 02 PM](https://user-images.githubusercontent.com/28606560/66783644-95117d80-ee95-11e9-856c-d5fa073cb5d2.png)
