### ISSUE TITLE
Code Review: Service/Middle Layer

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#20]
8/17: Library organization and naming.
8/24: Discussed State and came up with GlobalStateManager, ModuleVariable.
8/31: Boost library usage.

**Comment by dcwhite** [comment]
@aylakhan @cbrightsci Really this is a meeting about one class: `NetworkEditorController.` Let's actually have a code review for it once the basic Python interface is working, since they are quite intertwined.

**Comment by aylakhan** [comment]
Let's do this next week. I'll book a conference room.

**Comment by aylakhan** [comment]
Done. @dcwhite has a list of tasks for refactoring both the NetworkEditorController and the python wrapper code.
