### ISSUE TITLE
SCIRun won't open (it crashes on load)

### ISSUE THREAD

**Issue by kedararas** [SCIInstitute/SCIRun#2043]
Please follow these instructions for your issue to be worked on:

---
### If all prerequisites are met, just delete that text as well. If they're not all met, the issue will be closed or assigned back to you.
---
## For features, fill in the description section and delete the rest. Be as descriptive as possible.
---

### Prerequisites

* [Y ] Are you running the [latest version of SCIRun] (https://github.com/SCIInstitute/SCIRun/releases)? CnC2019 version
* [Y] Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)? I hope so
* [Y ] Did you [perform a cursory search](https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported? Cursory, yes.

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide. These links point to another project, but most of the advice holds in general.

### Description

Double click on SCIRun icon to load  the software and it crashes with MacOS crash report. 
[Crash Report.pdf](https://github.com/SCIInstitute/SCIRun/files/4081165/Crash.Report.pdf)

For Mac crash bugs, please *DO NOT* paste an entire MacOS crash report here. Edit it down to just the stack trace of the thread that crashed, along with the general system info on the top.

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `SCIRun --version` at the command line, or clicking on the version button in the bottom right corner of the GUI (which copies the version to the clipboard). Also, please include the OS and what version of the OS you're running.

**Comment by kedararas** [comment]
<img width="545" alt="Screen Shot 2020-01-18 at 12 20 48 PM" src="https://user-images.githubusercontent.com/12752639/72667724-fdb84b00-39ec-11ea-967b-74f992256ff6.png">

**Comment by dcwhite** [comment]
We haven't fully tested 10.15 yet. In general, the software will work on the most recent MacOS that's been out for a year, and the two before that (so 10.12-10.14 in this case). 

That crashed might already be fixed as well (from the Qt5 upgrade). Please try the latest build, which is not official yet but can be downloaded from a special place; if you email @jessdtate we can get you a link.

**Comment by jessdtate** [comment]
I sent @kedararas an installer built on 10.15, which seems to work fine.  @dcwhite is that what we need to do now?

**Comment by dcwhite** [comment]
Building with Qt5, yes. 10.15 is probably not required. We could have him test a 10.12- and 10.14-built one too.
