### ISSUE TITLE
Add "pre-execute" module step on file load

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2044]
From @Sumientra, #1846:

>>    The Matlab import modules work well. Being able to search for a file through the standard Mac interface is bliss. Only issue is that after opening a file, the module does not show the available fields, so you first have to run the module (causing the entire network to run and crash) in order to see the fields and select which field you want to load on each port. It would be great if this could be fixed.

>There are workarounds for this, I will check out that module to see if there is a slicker way.

**Comment by Sumientra** [comment]
In SCIRun4 the import modules show all the fields/matrices that are in the file as soon as the file is selected, which works well.
Also, there is ImportFields, ImportMatrices and ExportFields in SCIRun5 now, but no ExportMatrices.

**Comment by dcwhite** [comment]
I can add that module as part of this issue.

**Comment by dcwhite** [comment]
I also found a bug in the Import module, where the port/object selection did not stay put. I'll fix that too

**Comment by dcwhite** [comment]
And a crash too! No wonder I didn't convert all of those modules, the GUI was woefully undertested. Fixes coming next release, I'm moving this one up to the top...
