### ISSUE TITLE
Higher-resolution spheres develop a gap

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2062]
Testing spheres in ShowField, I found at resolution 15, 16, and 17, a gap in the two halves appears. It goes away at 18. Scale didn't seem to matter.

![image](https://user-images.githubusercontent.com/1399383/74092084-c7ff0300-4a7c-11ea-8e76-d88b9bf15f20.png)

**Comment by RubioJr9** [comment]
This bug happen with resolution 6 and some other low ones. It happened from looping over double values instead of ints. The error in floating point precision caused the loop to end one step early for certain values.
