### ISSUE TITLE
Tetgen Mesh Issue

### ISSUE THREAD

**Issue by BPhilip7** [SCIInstitute/SCIRun#2074]
### Prerequisites

Are you running the [latest version of SCIRun](https://github.com/SCIInstitute/SCIRun/releases)?
Yes
Are you reporting to the [correct repository](https://github.com/SCIInstitute/SCIRun)?
Yes
(https://github.com/SCIInstitute/SCIRun/issues) to see if your bug or enhancement is already reported?
Yes

### Steps to Reproduce
MACOS 10.14
1. Instaniate CreateLatVol, GetFieldBoundary, InterfaceWithTetgen
2. Pipe CreateLatVol to GetFieldBoundary, pipe GetFieldBoundary to InterFaceWithTetGen (slot 1)
3. Run network
4. Receive error: object pointer being freed was not allocated
5. Rerun network while changing all of tetgen's parameters to see if it is parameter dependent - it is not.

**Expected behavior:** [What you expected to happen]
Expected behavior is that tetgen meshes the square box.
**Actual behavior:** [What actually happened]
Crashes SCIRun and gives error object pointer being freed was not allocated.

**Comment by dcwhite** [comment]
Doesn't crash on Windows. I'll try various Mac versions.

**Comment by BPhilip7** [comment]
Thanks!

________________________________

**Comment by dcwhite** [comment]
Also doesn't crash on Mac 10.12. I will try 10.14 tonight

**Comment by dcwhite** [comment]
10.14 also does not crash. Is this a SCIRun 4 bug? If so, it's definitely fixed in SCIRun 5 since the latter uses a newer version of tetgen that fixed many memory problems. Also, this repo is only for v5 issues.

**Comment by BPhilip7** [comment]
This is a SCIRun 5 issue as Daria still can’t run it on her Mac and got this error. I’ll have her send me the error code she gets.

On Feb 28, 2020, at 5:35 PM, Dan White <notifications@github.com> wrote:

﻿

10.14 also does not crash. Is this a SCIRun 4 bug? If so, it's definitely fixed in SCIRun 5 since the latter uses a newer version of tetgen that fixed many memory problems. Also, this repo is only for v5 issues.

**Comment by dcwhite** [comment]
Yes, please attach an error report here as this might not be tetgen related. Make sure to include what SCIRun version too; this can be copied using the button in the lower right corner.

**Comment by dcwhite** [comment]
@BPhilip7 Does this match your crash?
```
SCIRun_test(83298,0x11d2df5c0) malloc: Incorrect checksum for freed object 0x7f803e15ac00: probably modified after being freed.
Corrupt value: 0x400a7462ecb198f0
SCIRun_test(83298,0x11d2df5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

If so, I replicated it--without Tetgen. It looks like it's present in old networks, coming from ViewScene--something amiss in how those are saved perhaps. That's why recreating the network solved it.

**Comment by BPhilip7** [comment]
No. Daria and I figured out the error. Somehow, sending my network from windows to her (she uses the latest mac SCIRun) results in an error. But if she recreates the network from scratch, it works fine.


From,

Brian Philip

________________________________

**Comment by dcwhite** [comment]
OK. If you get these errors consistently going from Windows to Mac, please report it again. The network files are just XML so should be cross-platform compatible.
