### ISSUE TITLE
Module Ideas

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#208]
Ongoing issue for new module ideas. 
- python script runner
- module that encapsulates a Scirun 4 network (I think there's an issue for this already) 
- UVF module for optional out-of-core volume rendering.

**Comment by aylakhan** [comment]
@cbrightsci - is UVF support likely?

**Comment by dcwhite** [comment]
DONE: python script runner
ENABLED with python: module that encapsulates a Scirun 4 network (I think there's an issue for this already)
DROPPED: UVF module for optional out-of-core volume rendering.
