### ISSUE TITLE
ViewScene frame flashes out with shift + click

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#2095]
OSX 10.14.6 on SCIRun v5.0-beta.X-183-gfe7ff5217. 
In any ViewScene, the object flashes out when you are holding shift and click about 6 times. This will happen every 6 clicks. Doesn't change how things are working.

**Comment by dcwhite** [comment]
Good catch. This is probably the same flashing phenomenon as with widget selection, but much easier to replicate. I got it with just a gray latvol. @RubioJr9 is currently investigating the exact function this is calling, and hopefully will be able to streamline the code there with some smart geometry id logic. But this shows it's a deeper issue that does not depend on the module feedback mechanism or widgets being in the scene.

**Comment by RubioJr9** [comment]
It seems this issue is separate from the widget selection flickering. I think that one is being caused by the module feedback whereas this one was from a delay in core execution.

**Comment by jessdtate** [comment]
you don't need widgets to see this flicker, but you do have to shift click.

**Comment by dcwhite** [comment]
Fixed with https://github.com/SCIInstitute/SCIRun/pull/2096
