### ISSUE TITLE
Problem with LinePlotter GUI

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2098]
It's blank. The pdf export still is correct, so it could be a Qwt bug from the upgrade. Reported by @jab0707

**Comment by dcwhite** [comment]
https://www.qtcentre.org/threads/67534-unable-to-set-border-for-canvas-in-qwt

**Comment by dcwhite** [comment]
@jab0707 how important is the background color setting? Right now it seems stuck on "SCIRun dark gray." I can investigate further in a new issue but it might be a Qwt bug.

**Comment by jab0707** [comment]
It does not have to be a background color issue. Just so long as the plotter works to visualize the data I don't have setting the plot background color as a high priority
