### ISSUE TITLE
SCIRun5 python script does not execute correctly

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2099]
OS: 10.14.6
Version: v5.0-beta.X.RC1
Summary: Using python script and -s/-S to load a SCIRun5 network does not always execute network correctly and -S does not close SCIRun after executing.

Description:
0. We have a simple test network and simple test python file:
<img width="1280" alt="0" src="https://user-images.githubusercontent.com/20671873/79515490-bf93ed00-8016-11ea-8314-f42248199897.png">

1a. We load and execute the network using -e -> Network gets loaded and executed, output file is produced -> Correct:
<img width="1280" alt="1-e" src="https://user-images.githubusercontent.com/20671873/79515508-ca4e8200-8016-11ea-98c0-0060e7f3b55f.png">

1b. We load and execute the network using -E -> Network gets loaded and executed, output file is produced, SCIRun closes -> Correct:
<img width="1280" alt="1E" src="https://user-images.githubusercontent.com/20671873/79515551-e6eaba00-8016-11ea-894e-7d96abcf6632.png">

2a. We execute the python file using -s -> Network gets loaded and executed, output file is produced, but part of the network is disabled -> Issue = disabling module:
<img width="1280" alt="2-s" src="https://user-images.githubusercontent.com/20671873/79515571-fec23e00-8016-11ea-8dd9-6dffaea85034.png">

2b. We execute the python file using -S -> Network gets loaded and executed, output file is produced, but part of the network is disabled, and SCIRun does not close -> Issue = disabling module + failing to close:
<img width="1280" alt="2S" src="https://user-images.githubusercontent.com/20671873/79515646-30d3a000-8017-11ea-8e51-a3b6ccd65b9b.png">

3a. We add a close command to the python file and execute it using -s -> Network gets loaded and executed, output file is produced, SCIRun closes (we cannot see whether the module is disabled now) -> Potentially correct:
<img width="1280" alt="3-s" src="https://user-images.githubusercontent.com/20671873/79515670-45b03380-8017-11ea-8678-1b798de44aa8.png">

3b. We add a close command to the python file and execute it using -S -> Network gets loaded and executed, output file is produced, SCIRun closes (we cannot see whether the module is disabled now) -> Potentially correct:
<img width="1280" alt="3S" src="https://user-images.githubusercontent.com/20671873/79515869-c2dba880-8017-11ea-92b8-1eebdfd4d1a8.png">

**Comment by dcwhite** [comment]
The rodent face will ensure this will get worked on quickly

I'll try it out tonight

**Comment by dcwhite** [comment]
Or maybe that's a bunny, either way, most colorful issue ever

**Comment by dcwhite** [comment]
Enabled ViewScenes caused crashes while running scripts, so those were set to disabled automatically a long time ago. However, they might not crash anymore, so I need to experiment with undoing that code.

**Comment by Sumientra** [comment]
You'll get to the see the full image once the issue is fixed ;)

**Comment by dcwhite** [comment]
It seems I only enabled the `-S` functionality in headless mode. It should be an easy fix.

**Comment by dcwhite** [comment]
`-S` works now with the GUI. It also looks like ViewScenes don't need to be disabled during script runs, which is good news for generating screenshots. I will continue working on that in your other issue.

**Comment by Sumientra** [comment]
Just downloaded and built again, but issue is still there.

**Comment by dcwhite** [comment]
Which branch are you on?

**Comment by Sumientra** [comment]
Uhm.. I did this:
git clone https://github.com/SCIInstitute/SCIRun.git
git submodule update --init --recursive

**Comment by Sumientra** [comment]
Fixed! Here's the bunny ;) 

![wallpaperflare com_wallpaper (5)](https://user-images.githubusercontent.com/20671873/80029280-91019080-84b4-11ea-9f6a-ce7a702c600e.jpg)

**Comment by dcwhite** [comment]
🥕
