### ISSUE TITLE
Code Review: Overview of OpenGL Code in SCIRun 4

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#21]
High-level overview with code examples. Include broad categories of what can stay, what should go, what's good and bad, etc.

**Comment by aylakhan** [comment]
Let's to do this beginning of December.

**Comment by dcwhite** [comment]
@cbrightsci Do we still want to do this? It might be more pertinent now, with the clipping plane performance problem.

**Comment by aylakhan** [comment]
Time to take this out behind the barn and put it out of it's misery.
