### ISSUE TITLE
SCIRun5 save image on command line

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2100]
There currently is no possibility to save images when executing and closing a network from command line. SCIRun4 has the -I option for this. This is very useful when running a script with many SCIRun runs for which you need file outputs.

**Comment by dcwhite** [comment]
With the current renderer implementation in Qt 5, along with OpenGL limitations, grabbing framebuffer data (the requirement for taking a ViewScene image) can only be done after the ViewScene window is displayed. So the best automation for this would still have to pop up the network GUI and ViewScene, then close SCIRun. Will that be sufficient? We have the code to do all that, it's just not wired up into a command line option or easily scriptable.

**Comment by Sumientra** [comment]
In SCIRun4 I use -E -I and the network pops up, executes, saves the image and then closes. That works fine. Doing this headless would be amazing of course, but anything that matches that SCIRun4 functionality would make me happy.

**Comment by jessdtate** [comment]
Right now the way to do this is to use the matrix ports from viewscene.  Each matrix is a channel for RGB.  I think we were still working on an image saver, but these can be combined to an image in python, matlab, or others.

**Comment by dcwhite** [comment]
The code to save an image just uses Qt--but opens a dialog to ask for the file name. I had requested 1-button auto-saving but that didn't get implemented. It would be trivial to add a python call to save the image, the window just needs to be viewable.

**Comment by Sumientra** [comment]
> Right now the way to do this is to use the matrix ports from viewscene. Each matrix is a channel for RGB. I think we were still working on an image saver, but these can be combined to an image in python, matlab, or others.

Good to know, but if this is the solution, then I'll just use SCIRun4.

**Comment by dcwhite** [comment]
I have auto-saving screenshots working with a python script. Here are the caveats: I added python script lines to ensure the ViewScene UIs are open, and the SCIRun main window has to be visible, i.e. on the active desktop. I used `-z` since `-i` was taken already.

**Comment by Sumientra** [comment]
It doesn't work for me. I ran a network with -E -z, it opened, executed, ViewScene was visible, closed, no figure.

**Comment by Sumientra** [comment]
With the test build from today, this now works.

**Comment by Sumientra** [comment]
Upon execution of a network, some of the ViewScene settings are reset. Background color and viewing angle are correct, but the window size is the default (tiny) and the orientation axis is visible even though I turned it off before saving the network.

**Comment by dcwhite** [comment]
There’s a separate issue for that, let me find it. I believe it was never fully implemented.
