### ISSUE TITLE
Smart Reader

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2116]
@wgood After recent discussions with @jessdtate and @jab0707, I'm going to try making a new "SmartReader" module from scratch that will have user-defined defaults, or just default to Matlab for everything. I had trouble with modifying the ancient legacy readers, and it would be cool to just have one read module that can handle everything. It will subsume issues #1216, #289, #2110, and the rest of this one.

_Originally posted by @dcwhite in https://github.com/SCIInstitute/SCIRun/issues/2083#issuecomment-628812073_

**Comment by dcwhite** [comment]
@RubioJr9 can work on this soon

**Comment by dcwhite** [comment]
The new module (ReadFile) needs a name change due to a Windows API name conflict. I think we decided on FileReader. Any other alternatives @wgood @jessdtate @jab0707 @bzenger?

**Comment by bzenger** [comment]
What about SmartReadFile or AutoReadFile?

**Comment by jab0707** [comment]
AutoReadFile or something on those lines is nice because it conveys the purpose of the module in the name and makes it clearer when you might want to use it over the traditional file readers.

**Comment by dcwhite** [comment]
Heh that name is good, and used already by a .NET function whose description reads like the SCIRun module documentation: https://docs.microsoft.com/en-us/dotnet/api/microsoft.dataprep.reader.autoreadfile?view=dataprep-dotnetcore

I don't think that will cause a build error, so we should be good with AutoReadFile.
