### ISSUE TITLE
ModelTMSCoil adaptation to include overlapping coils

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2120]
The ModelTMSCoil module has an 'Outer Distance' setting to control the distance between the two coils of a figure-of-eight coil. Many coils exist in which the two coils partially overlap, but 'Outer Distance' does not allow negative values, so it is currently impossible to model overlapping coils with ModelTMSCoil. Therefore, requesting to allow negative values for 'Outer Distance'.

**Comment by dcwhite** [comment]
@Sumientra Look right?
![image](https://user-images.githubusercontent.com/1399383/82384833-fda57780-99ed-11ea-9d5f-a55983a34e04.png)

**Comment by Sumientra** [comment]
Great. Thank you!

**Comment by Sumientra** [comment]
Tested this on two computers. Behaves as expected.
![E_brain_coil_0001](https://user-images.githubusercontent.com/20671873/82983552-4c3ead00-9fbe-11ea-9b7c-0aefa0dbe6e2.png)
