### ISSUE TITLE
SolveBiotSavart getting stuck

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2122]
**Describe the bug**
SolveBiotSavart module takes between 5 and 60 minutes to complete on the same mesh. I've seen it run for 8 hours but I then closed SCIRun, so I don't know if it would have completed (after closing, running the same network+data again, it completes within acceptable time). This extremely long run time seems to happen especially when not using the computer (and it is not sleeping). This is on a laptop with 16 GB RAM without running anything else that requires a lot of memory. My desktop with 64 GB seems to roughly halve the runtime.

**To Reproduce**
1. Open the attached network: [Archive.zip](https://github.com/SCIInstitute/SCIRun/files/4660241/Archive.zip)
2. Load the attached mesh ([HeadModel.mat](https://drive.google.com/open?id=1cUPxRyWRSR2WykVj9JqpMP8jAVzISZGZ) -> ReadField) and transformation matrix (TFM.mat -> ReadMatrix).
3. Run the network.
4. See error.

**Expected behavior**
Expect it to finish in a couple of minutes. 

**Version**
v5.0-beta.X-287-g7897ca051

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.14.6

**Comment by dcwhite** [comment]
Cool, good write up; I look forward to cleaning up that module.

**Comment by dcwhite** [comment]
After doing the easy code cleaning, I'm consistently getting about 430-second run time on my 12-logical-core Macbook. I'm not sure the sloppy memory code was causing the problem, so it might be deeper in the algorithm. How many cores do you have on the laptop?

**Comment by Sumientra** [comment]
4 logical cores. 
Runtime being consistent sounds like improvement. I think when I started using this module it was consistently taking ~9 minutes. Or it got stuck for hours. But nothing in between. Recently it seems to have gone on the rails.

**Comment by dcwhite** [comment]
I’d watch the memory usage on the 4-core machine; it might be paging to disk heavily which will lead to really long execution times. I don’t see it using a ton of memory with more cores, but more cores will spread the memory usage out at least.

**Comment by Sumientra** [comment]
Should I try it now?

**Comment by dcwhite** [comment]
It would be nice to have a comparison with a recent build, and my cleaned-up branch. Should I make you an installer or can you build yourself?

**Comment by Sumientra** [comment]
I can build it. I'm not completely sure what you mean though. To compare to a recent build, and the cleaned up branch. If I pull and build it now, am I not getting the cleaned up branch?

**Comment by Sumientra** [comment]
It's still the same for me. Takes up to hours for a single run, and gets longer the more I use it. I also tried it on my desktop; 50 samples consistently took 6 minutes. Seems like my laptop is the problem, but on my laptop it also started off consistent (9 minutes per sample); it only went crazy when the laptop was not otherwise used, but over time it turned to crazy nonstop. I'll try running more on my desktop to see if that goes crazy over time too, or that the issue is with my laptop.

**Comment by dcwhite** [comment]
How about this idea: I can log a remark at the start of the module run that indicates how many "operations" are going to be done in the algo, to indicate the scale of computation. Then the user could kill SCIRun if they balk at the resolution's computational burden. When the new stoppable functionality is in, this module will be easily stoppable, and that will be more user-friendly.

**Comment by Sumientra** [comment]
If there is no way to speed up this module, I think adding the message would be helpfu. Then once you've done a couple of simulations, you'll get a sense of how '# operations' relates to run time. 

[Here](https://docs.google.com/presentation/d/1zSWRsWuFG4zoKOwF8NbJjEbIVgYUo5LznmCbj4xFEhU/edit?usp=sharing) is a summary of a set of tests for all the different settings of ModelTMSCoil. The timing has been very consistent.

**Comment by dcwhite** [comment]
We discussed some ways to speed it up, but they were pretty involved and will require some deep theory thought or GPU acceleration that will be very hardware-specific. So I’ll add the message and close this one.
