### ISSUE TITLE
RescaleColorMap not working

### ISSUE THREAD

**Issue by JoaoMMR** [SCIInstitute/SCIRun#2133]
There appears to be some problem with the RescaleColorMap module.
I get the error message: **Input data required on port ColorMapObject** even in simple networks like the one described in the tutorial shown below.

**To Reproduce**
1. Create and run any network with the RescaleColorMap module. 
2. See error

![image](https://user-images.githubusercontent.com/12515181/83549265-f3f73600-a4fc-11ea-800d-6eb5c4c826b1.png)

**Version**

Currently using the version built from the bat file in #2092

**Desktop:**
 - OS: Windows 10
 - Version 2004

**Comment by dcwhite** [comment]
You might have to re-execute the whole network, using the execute all button at the top of the window. If you click module execute now, it will execute "downstream only" and not pick up a newly-connected input. That changed recently to be more like version 4.

**Comment by JoaoMMR** [comment]
The "trick" worked. Thanks for the quick reply
