### ISSUE TITLE
Copy content from defunct StackOverflow

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2151]
Our free trial ran out without enough interest to justify paying. There was a small amount of useful content on there, we just need to copy it somewhere else so it can be recreated in Github discussions once that is enabled. It can even just be attached here as a text file. The link is https://stackoverflow.com/c/sciinstitute/questions

**Comment by nids2001** [comment]
[stackoverflow.txt](https://github.com/SCIInstitute/SCIRun/files/4905630/stackoverflow.txt)

**Comment by dcwhite** [comment]
Looks great, thanks!

**Comment by dcwhite** [comment]
Let me keep this one open so I can link it to a "figure out discussion forum" new issue...

**Comment by dcwhite** [comment]
@nids2001 and @RubioJr9, divvy up the questions in the text file above on the new github discussion page [here](https://github.com/SCIInstitute/SCIRun/discussions)

**Comment by RubioJr9** [comment]
All the questions are posted. However, I left out the question about private and public accounts on Stackoverflow.
