### ISSUE TITLE
Network jumps when moving modules

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2153]
**Describe the bug**
When dragging modules to where you want them in a network, if that move changes the surface area of the network covered by modules (either moving a module out of the boundaries of all other modules and thus making the network bigger, or moving a border module inward and thus making the network smaller), the network moves too, making it almost impossible to get the module where you want it. 

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**
[Here](https://drive.google.com/file/d/12uHwJdEbeESCgQMuTfU63hb5SB_sjjE-/view?usp=sharing) is a video of an example.

**To Reproduce**
1. Add a new module into an existing network such that it is placed somewhere on the border of the network.
2. Move the module to the center of the network.

**Expected behavior**
I expect the network to stay put so that I can place the module where I want it. Then if the network is no longer centered due to the size change (which is my guess as to why SCIRun moves it), the user can just re-center it themself. 

**Version**
v5.0-beta.X-372-ga462dff43

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.5 (seen this issue on several prior versions)

**Comment by dcwhite** [comment]
This is essentially fixed now on my fixes branch. I’ll make you a build so you can see if it’s “fixed enough”—there are still some quirks with double click adding, and snippets, and loaded networks.
