### ISSUE TITLE
MapFieldDataFromSourceToDestination does not interpolate

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2154]
**Describe the bug**
When mapping a point could with data onto an empty surface mesh, the 'linear weighted' option does not seem to interpolate, but instead gives the same output as 'nearest source value'.

Additionally, the [help description](https://sciinstitute.github.io/scirun.pages/modules.html#MapFieldDataFromSourceToDestination) says "data values can be stored at the nodes, cells, edges, or faces of the mesh at either the input or output ports", but the module does not provide an option to select to map on cells, edges or faces. 

**To Reproduce**
1. Build a network with MapFieldDataFromSourceToDestination and a source and destination mesh.
2. Set the option to 'linear weighted' and execute.
3. Visualize results.
4. See error.

**Expected behavior**
I expect the data values on the nodes to change linearly between the source nodes. 

**Screenshots**
We want to map a point cloud with data onto a surface mesh:
![Screen Shot 2020-07-11 at 00 50 18](https://user-images.githubusercontent.com/20671873/87216812-1d338f00-c311-11ea-92c2-4724dea99701.png)

Option 'each source maps to one destination' looks correct:
![Screen Shot 2020-07-11 at 00 51 36](https://user-images.githubusercontent.com/20671873/87216830-3e947b00-c311-11ea-9baf-32683257741f.png)

Option 'nearest source value' looks correct:
![Screen Shot 2020-07-11 at 00 51 53](https://user-images.githubusercontent.com/20671873/87216836-481de300-c311-11ea-8bf7-3026f3a2490d.png)

Option 'linear weighted' looks like the previous option:
![Screen Shot 2020-07-11 at 00 52 06](https://user-images.githubusercontent.com/20671873/87216840-4d7b2d80-c311-11ea-8f19-801c034d54f5.png)

**Version**
v5.0-beta.X-372-ga462dff43

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.5

**Comment by jessdtate** [comment]
point clouds do not have a linear basis or connections to describe the linearity of the function, therefore do not have a linear interpolation.  This needs to be reflected in the documentation.  

The work around is to create a tetralization with tetgen, then do the linear mapping. When mapping onto a volume, one can also use the mapfielddatawithradialbasisfunction.  

There are some other algorithms to consider linear mapping with point clouds.  Most involve finding a triangulation.

**Comment by Sumientra** [comment]
The destination field does have connections, so the function can interpolate the values on the destination field. That is what I'd expect it to do.

**Comment by jessdtate** [comment]
I see what you mean. However, the neighborhoods of the destination mesh are not always easy to apply to source function, especially without a priori knowledge.  I think that we might be able to implement something though, perhaps with a linear mapping from the destination to the source, then invert it. In some cases, the matrix would be symmetric, so the inversion wouldn't be problematic for those. The distance truncation complicates this method.  We could prototype this method with the BuildMappingMatrix module, which is very similar to the mapfielddatafromsourcetodestination module.
