### ISSUE TITLE
MapFieldDataOntoNodes errors

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2155]
**Describe the bug**
There are 3 bugs:
1. When mapping a point could with data onto an empty surface mesh, the 'interpolateddata' option does not seem to interpolate, but instead gives the output one would expect for 'closestnodedata'.
2. The 'maximum distance' setting is not taken into account (result is as if it is set to infinite).
3. The other 3 options give errors.

**To Reproduce**
1. Build a network with MapFieldDataOntoNodes and a source and destination mesh.
2. Choose one of four options and execute.
3. Visualize results.
4. See error.

**Expected behavior**
1. For 'interpolateddata', I expect the data values on the nodes to change linearly between the source nodes. 
2. I expect 0 values for all nodes that are farther than 'maximum distance' from the source nodes.
3. I expect no errors.

**Screenshots**
We want to map a point cloud with data onto a surface mesh:
![Screen Shot 2020-07-11 at 01 25 26](https://user-images.githubusercontent.com/20671873/87217282-6c7bbe80-c315-11ea-8b70-32d58fa77766.png)

Option 'interpolateddata' looks like the data is mapped from the closest node without a maximum distance (illustrates errors 1 and 2):
<img width="949" alt="Screen Shot 2020-07-11 at 01 12 15" src="https://user-images.githubusercontent.com/20671873/87217210-d6479880-c314-11ea-909f-6c2601aed040.png">

Option 'interpolateddataonly' gives an error:
<img width="426" alt="Screen Shot 2020-07-11 at 01 12 43" src="https://user-images.githubusercontent.com/20671873/87217225-f70fee00-c314-11ea-9413-574d0256e904.png">

Option 'closestnodedata' gives errors (it says that the source data needs to be on the nodes, which is the case in this network):
<img width="414" alt="Screen Shot 2020-07-11 at 01 13 12" src="https://user-images.githubusercontent.com/20671873/87217237-068f3700-c315-11ea-9785-ce106831b81a.png">

Option 'closestnodedataonly' gives the same error as 'interpolateddataonly':
<img width="421" alt="Screen Shot 2020-07-11 at 01 13 38" src="https://user-images.githubusercontent.com/20671873/87217249-1f97e800-c315-11ea-8c6f-07646b648284.png">

**Version**
v5.0-beta.X-372-ga462dff43

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.5

**Additional information**
Module MapFieldDataOntoElements has the exact same issues as MapFieldDataOntoNodes.
Bug #1 is the same as for MapFieldDataFromSourceToDestination in issue #2154 but I made a new issue because this module has 2 additional bugs.

**Comment by dcwhite** [comment]
You've found a copy-paste bug from the similar module MapFieldDataOntoElements. Those options that "don't work" are either not available for the Node version, or there was a small typo in the UI. Here are the official options for each:
```
OntoElems:
  addOption(InterpolationModel, "interpolateddata","interpolateddataonly|interpolateddata|closestnodedata|closestinterpolateddata");

OntoNodes:
  addOption(InterpolationModel, "interpolateddata", "interpolateddata|closestnodedata|closestinterpolateddata");

```

So there's a more interesting bug for option "closestnodedata." I'll fix the simple UI bug for this one, and then you can make a new issue for that error.

**Comment by dcwhite** [comment]
It seems like all the example networks for this module just uses the default "interpolateddata." So you might be the first person to test those other options.

**Comment by dcwhite** [comment]
I'll need network+data to work on the `closestnodedata` problem.

**Comment by Sumientra** [comment]
[Here](https://drive.google.com/drive/folders/1CWK7rpiTbuCAne06N5ZW80xDop4wyJS8?usp=sharing) is an example network with data.

**Comment by dcwhite** [comment]
Replicated the error message. Same reasoning @jessdtate indicated for #2154. Point clouds, even with data on nodes, count as constant basis, not linear. So in this case the error message is just confusing. The code checks for linear basis explicitly, not actual data location. The message should say "Closest node data mapping only works for source data located at the nodes with linear basis." I say we close this and #2154 and you can open a feature request for interpolating point cloud data (non-trivial). I'll update the error message however.

**Comment by jessdtate** [comment]
it's interpolateddata that should only work with linear basis.  closest node should work with point clouds, but it is checking the  basis.  The result from interpolateddata is actually closest node.  I'm not sure why the distance functionality isn't working.  With tet meshes is just does an inside outside calculation.  I actually prefer this option for a lot of my applications.

**Comment by jessdtate** [comment]
distance constraint seems to only work with the closest node option

**Comment by jessdtate** [comment]
for tet data with constant basis, there is still a linear interpolation from the element centers.  I suppose this make some sense.
