### ISSUE TITLE
Code Review: FFP Code in SCIRun 4

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#22]
Go in depth with some of the current code.

**Comment by dcwhite** [comment]
@cbrightsci You may close this if you don't feel like it's useful to have such a meeting. We haven't done code review in a while though...

**Comment by dcwhite** [comment]
@jessdtate This ancient document can be closed now, I believe. Unless @Haydelj and @RubioJr9 really want a code history lesson.

**Comment by jessdtate** [comment]
agreed
