### ISSUE TITLE
CARP ReadField Scaling Issue

### ISSUE THREAD

**Issue by Lindsay-Cecala-Rupp** [SCIInstitute/SCIRun#2220]
SCIRun Version: v5.0-beta.Y

Description: When reading CARPMesh geometry files using ReadField the geometry is scaled by 1/1000. Below is a screenshot from SCIRun and MATLAB with the geometry information. 

Screenshot from MATLAB:
<img width="285" alt="Screen Shot 2021-01-22 at 2 06 34 PM" src="https://user-images.githubusercontent.com/50336247/105546790-0d7f0500-5cbb-11eb-9e96-4c6402dcf4d5.png">

Screenshot from SCIRun:
<img width="532" alt="Screen Shot 2021-01-22 at 2 04 30 PM" src="https://user-images.githubusercontent.com/50336247/105546692-e6283800-5cba-11eb-86c4-d17717442928.png">

Tried to upload geometry files, but files too large.

**Comment by dcwhite** [comment]
@Lindsay-Cecala-Rupp @kgillette This line in the code scales every input point by 1000. @jessdtate says we can just take out this line since the renderer can handle these big geometries more efficiently now.

https://github.com/SCIInstitute/SCIRun/blob/master/src/Core/IEPlugin/CARPMesh_Plugin.cc#L317

**Comment by jessdtate** [comment]
@Lindsay-Cecala-Rupp can you confirm that scaling back to the original size works with the render and other aspects of SCIRun?

**Comment by jessdtate** [comment]
@ dwhite I think it's in both the reader and writer.

**Comment by dcwhite** [comment]
@Lindsay-Cecala-Rupp If the data isn't too large, you can post a dropbox/google drive link here instead.

**Comment by Lindsay-Cecala-Rupp** [comment]
From what I can tell when scaling by 1000 with ScaleFieldMeshAndData everything else seems to work in SCIRun. The geometry is in here: https://drive.google.com/drive/folders/17AntTtcDd3CUkgV1ANPFPcVFGfRbTet_?usp=sharing

**Comment by dcwhite** [comment]
I tested round-trip read/write after removing the 1000x scaling factor, and the SCIRun field scale now matches your matlab scale (more or less). Plus it's fully viewable in ViewScene too.
