### ISSUE TITLE
CreateImage custom input data are not working correctly

### ISSUE THREAD

**Issue by wilkij1** [SCIInstitute/SCIRun#2236]
**Describe the bug**
The CreateImage UI only allows the Custom Normal components to be set to values above 1. There is no way to get a custom plane that is perpendicular to one of the axes other than using the preset X, Y, Z. Doesn't help if you want the plane's normal to be [1, 1, 0], for example.
The Custom Center doesn't let you set a negative number, either.

**To Reproduce**
1. Place CreateImage in a blank net and wire to a TetVolMesh source.
2. Set Axis to 'Custom' in the UI. 
3. Attempt to change the value in any of the Custom Normal boxes to something less than 1.
4. Navigate to another box and the number reverts to its previous value

**Expected behavior**
The custom normal and custom center input boxes should be able to be set to any value.

**Version**
v5.0-beta.Y

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jessdtate** [comment]
some ideas to piggy back:
- [  ] hide mode (leave as manual)
- [  ] hide index
- [  ] gray out custom inputs when x,y,z is selected
- [  ] gray out position when custom is selected
