### ISSUE TITLE
Set State for Viewscene Camera Behaving Weirdly

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2254]
When using python commands to set state for the view scene camera I have encountered an issue:

Starting with the following view scene window:
![image](https://user-images.githubusercontent.com/38257234/113187955-b2b3dd80-9216-11eb-9b4a-9875a45a0869.png)

I then open the python consol and run the following commands:

```
look = scirun_get_module_state('ViewScene:1','CameraLookAt')    
rot = scirun_get_module_state('ViewScene:1','CameraRotation')
dist = scirun_get_module_state('ViewScene:1','CameraDistance')
```

I then move the viewscene to look like this:
![image](https://user-images.githubusercontent.com/38257234/113188184-f4448880-9216-11eb-8674-236c6f80a7df.png)

I then want to recover the original view in the viewscene from the first image. So I run the following code:
```
scirun_set_module_state('ViewScene:1','CameraRotation',rot)
scirun_set_module_state('ViewScene:1','CameraLookAt',look)
scirun_set_module_state('ViewScene:1','CameraDistance',dist)
```

Instead of getting the original view I get: 
![image](https://user-images.githubusercontent.com/38257234/113188561-6fa63a00-9217-11eb-8b37-6cdeb3415bba.png)

It seems like the rotations is being applied to the image rather than being set. So instead of getting the intended rotation I get some compound of the current rotation and what I pass into the set field. I can check this by checking the value of CameraRotation from the beginning and the end:
```
rot
output: [0.7355649471282959, 0.3985646367073059, -0.16810239851474762, -0.5213748216629028]
```

but when I set that as the rotation I get the following from get module state:

```
scirun_get_module_state('ViewScene:1','CameraRotation')
output: [0.39856472611427307, -0.1681024432182312, -0.5213749408721924, 0.7355651259422302]
```

**Comment by dcwhite** [comment]
@RubioJr9

**Comment by jab0707** [comment]
Forgot to add version number: v5.0-beta.Z

**Comment by RubioJr9** [comment]
So I think I found the culprit. glm::quat's constructor is in order quat(w,x,y,z), but the array access is [0]=x,[1]=y,[2]=z,[3]=w. This is because glm changed the ordering of data, but left the ordering of the contructor alone. There is a flag to change the ordering back to the old behaviour, but I'll just change it so we don't rely on the array accesses.
