### ISSUE TITLE
View scene not saving state when restarting

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2257]
The view scene window size, camera angle, distance, rotation etc. used to save in between reopening SCIRun. This was very important in order to make sure you could take screenshots of visualization at the same size/angle in case SCIRun crashed or you wanted to change the data. Now on each restart, the view scene seems to reset to a small window and some default rotation/camera angle etc. If this is going to be the case then the ability to set the camera state variables needs to be fixed so that the original view can be restored. Otherwise, SCIRun becomes 100% harder to use for visualizations in publications as there is no consistency.

Version: v5.0-beta.Z
OS: 
![image](https://user-images.githubusercontent.com/38257234/113514763-c3719580-952d-11eb-9afe-d560ada970d6.png)

**Comment by dcwhite** [comment]
Working on this together with #1939. These got broken at some point (maybe with newer Qt version) and aren't part of any test script.
