### ISSUE TITLE
Boost error when running the software after compilation on Linux

### ISSUE THREAD

**Issue by max1c** [SCIInstitute/SCIRun#2273]
**Describe the bug**

After compilation seeing boost error when trying to run the application.

$ ./SCIRun
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Function not implemented: "./src"
Aborted

**To Reproduce**
1. Go to /opt/SCIRun-5.0-beta.Z/bin/SCIRun
2. ./SCIRun

**Version**

The release v5.0-beta.Z version: https://github.com/SCIInstitute/SCIRun/releases/tag/v5.0-beta.Z

**Desktop (please complete the following information):**

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by dcwhite** [comment]
If you used gcc, could you run your build through the debugger? 
```gdb ./SCIRun
run
bt
```
will generate a backtrace and I'll have more to work with. I've seen similar filesystem errors in the past, but I don't have an 18.04 machine to test on (SCIRun ought to work fine on 20.04).

**Comment by max1c** [comment]
I tried building under ubuntu 20.04 but now get:
[ 74%] Completed 'Python_external'
[ 74%] Built target Python_external
make: *** [Makefile:84: all] Error 2

No other errors or anything. Is there a list of apt dependencies necessary to be installed that's more detailed than this: http://sciinstitute.github.io/SCIRun/build.html#linux ?

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by dcwhite** [comment]
That backtrace helps. I think it's a bug in boost, but at least I can add some error checking on our side.

I'll need more of the build log to diagnose the failed 20.04 build. If you were running a `make -j6` for instance, try a single-core make first--sometimes the multicore make gets tripped up on the Python part of the build.

**Comment by max1c** [comment]
> That backtrace helps. I think it's a bug in boost, but at least I can add some error checking on our side.
> 
> I'll need more of the build log to diagnose the failed 20.04 build. If you were running a `make -j6` for instance, try a single-core make first--sometimes the multicore make gets tripped up on the Python part of the build.

Yes, that was indeed the issue. Here is the error after running make without -j: 
/usr/lib/qt5/bin/uic: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
make[5]: *** [Interface/Modules/Base/CMakeFiles/Interface_Modules_Base.dir/build.make:62: Interface/Modules/Base/ui_ModuleDialogBasic.h] Error 127
make[4]: *** [CMakeFiles/Makefile2:2718: Interface/Modules/Base/CMakeFiles/Interface_Modules_Base.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/SCIRun_external.dir/build.make:126: download/FwdInvToolkit/Stamp/SCIRun_external/SCIRun_external-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:121: CMakeFiles/SCIRun_external.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by max1c** [comment]
I compiled SCIRun under Ubuntu 20.04 and it's working. This can be closed. Thanks for help .
