### ISSUE TITLE
Get Sub Matrix returning NAN

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2324]
I ran into a weird bug using get submatrix. In the module below if I set get matrix slice to 0 (which will generate volume indices [0,1,2] the output matrix is full of nan/really high values. If I change to any other slice (any other set of three columns) then I get the expected output. Network attached for reference. Does not require external data.

![image](https://user-images.githubusercontent.com/38257234/135927864-6f720d3e-e92a-43da-8c79-48e651c3b14a.png)

![image](https://user-images.githubusercontent.com/38257234/135927892-81787900-6e6b-4e04-a9cb-f3649421ebc4.png)

![image](https://user-images.githubusercontent.com/38257234/135928110-0a9a4543-11d7-4298-81a7-5b7f0d11e72e.png)

version v5.0-beta.Z
[WeirdBug.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/7281434/WeirdBug.srn5.zip)

**Comment by dcwhite** [comment]
This line is the culprit:
https://github.com/SCIInstitute/SCIRun/blob/master/src/Core/Algorithms/Math/SelectSubMatrix.cc#L349
It's only selecting columns when the index is > 0, so the 0th column in the output is random garbage. This sort of copy-paste bug is the result of the heavily-nested code of the algorithm, trying to handle too many cases in a simplistic manner.
