### ISSUE TITLE
ViewSceneGeometryBuffer only works with one geometry

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2350]
In the attached example two geometries are provided to the buffer, but only one gets visualized on the output
[viewbufferbug.zip](https://github.com/SCIInstitute/SCIRun/files/7584526/viewbufferbug.zip)

https://user-images.githubusercontent.com/38257234/142939263-62e17e44-8bac-4a77-97e7-80a730c19ee8.mp4

.

**Comment by jab0707** [comment]
I think I was being dumb about how this feature works as I can get it to work properly now. This issue can be closed I think. I was just not using all of the output pipes from the buffer module.

**Comment by dcwhite** [comment]
No problem. Do continue to test it with different combinations of input/output, different numbers of "frames" on each port, stuff like that--there are probably some similar bugs lurking.
