### ISSUE TITLE
Cannot Delete showcolormap attached to geometry buffer

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2353]
in the attached network SCIRun crases any time I try to delete the show color map module
[UQFEM.zip](https://github.com/SCIInstitute/SCIRun/files/7652278/UQFEM.zip)

**Comment by jab0707** [comment]
Also if I try to open a new network or close SCIRun it also frezes up after executing that network.

**Comment by dcwhite** [comment]
@jab0707 Can you test this with the latest prerelease build? I think I fixed it

**Comment by dcwhite** [comment]
@jab0707 👀

**Comment by dcwhite** [comment]
@jab0707 👀  👀

**Comment by jab0707** [comment]
yes that seems to have fixed it
