### ISSUE TITLE
IQuant vis module porting

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#2354]
There was an experimental module developed for SR4 that has been requested to port for SR5.  

based on this paper:
[F. Jiao, J.M. Phillips, J.G. Stinstra, J. Kueger, R. Varma, E. Hsu, J. Korenberg, C.R. Johnson. “Metrics for Uncertainty Analysis and Visualization of Diffusion Tensor Images,” In Proceedings of the 5th international conference on Medical imaging and augmented reality (MIAR), Beijing, China, Springer-Verlag, Berlin, Heidelberg pp. 179--190. September, 2010.](http://www.sci.utah.edu/publications/jiao10/Jiao_fiber-uncertainty.pdf)

with this example net:
<img width="825" alt="Screen Shot 2021-11-26 at 2 33 54 PM" src="https://user-images.githubusercontent.com/3484631/144676488-85c1536e-e538-4575-88d5-d5662704d1cf.png">

source code here:
www.sci.utah.edu/~chris/fiber_diff_backup

**Comment by jessdtate** [comment]
The code looks in good shape.  We could try building in SR4 before porting

**Comment by dcwhite** [comment]
@jessdtate Could you
- [ ] zip up that directory and post here
- [ ] Post screenshots of the new module UIs for reference

I can take it from there without building in v4, most likely.

**Comment by dcwhite** [comment]
How are those bar graphs created on the ViewScenes?

**Comment by jessdtate** [comment]
it looks like Matlab plotting. they could have use InterfaceWithMatlab in another network, but I think they spliced the images.

**Comment by jessdtate** [comment]
here is the code:

[core.zip](https://github.com/SCIInstitute/SCIRun/files/7695866/core.zip)
[gui.zip](https://github.com/SCIInstitute/SCIRun/files/7695867/gui.zip)
[Module.zip](https://github.com/SCIInstitute/SCIRun/files/7695868/Module.zip)
[xml.zip](https://github.com/SCIInstitute/SCIRun/files/7695869/xml.zip)

**Comment by dcwhite** [comment]
@jessdtate I got the pipeline.srn network file converted. Here's what else is missing (besides the main new module):
- [ ] Module TendFiber
- [ ] Bundle output on SplitFieldByConnectedRegion
- [ ] ChooseField/ColorMap is replaced by ChooseInput, but it looks like the instances only ever have one input to choose? Huh?

The other two new modules are not used in that network.

**Comment by dcwhite** [comment]
Also, the picture of the network and the network file included are not the same ☹️ 

I'll try to reconnect stuff as best I can

**Comment by jessdtate** [comment]
I have this built in SR4, but the example net is not quite the same as the image.  I'll compare to SR5 soon

**Comment by jessdtate** [comment]
test data
[bundle_data.zip](https://github.com/SCIInstitute/SCIRun/files/8218192/bundle_data.zip)
