### ISSUE TITLE
Full SCIRun (Native) compilation support for ARM-based Apple Silicon with Qt 6 GUI

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#2360]
I was wondering if SCIRun binaries / full code compilation support will be available on ARM-based processors (i.e., Apple Silicon) and if so, what the timeline is.

**Comment by dcwhite** [comment]
Good news! A PR is in the works that supports Qt 6 and builds on Apple Silicon natively. There are still a lot of quirks to figure out with the GUI, but the OpenGL rendering works and it's blazing fast. When it's all merged I will update this issue with the next steps.

**Comment by dcwhite** [comment]
@moritzdannhauer The latest release includes an ARM installer! Check it out! https://github.com/SCIInstitute/SCIRun/releases/tag/v5.0-beta.2023
