### ISSUE TITLE
Field statistics

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2367]
In SCIRun4 there are modules ReportScalarFieldStats and CalculateFieldDataMetric, both of which calculate stats on the field data (see screenshot). Neither exists in SCIRun5. The only similar module seems to be GenerateROIStatistics, but this requires mesh atlas data. It would be very helpful to have modules that can generate stats on the entire input field. Can the old SCIRun4 modules be converted to SCIRun5?
![Screen Shot 2022-01-25 at 13 05 31](https://user-images.githubusercontent.com/20671873/151033871-4653a44e-19b8-4d1b-8cee-604b47f33db2.png)

**Comment by jessdtate** [comment]
ReportScalarFieldStats functionality can be mostly replicated with reportmatrixslicemeasure and displayhistogram.  I think we had some plans to combine the two into a single module, so maybe @dcwhite and i can revisit it.  

For some reason, I do not have CalculateFieldDataMetric in my build of SR 4.7, but I found it on the wiki page.  I think it would make sense to try to convert a form of this module to SR5.

**Comment by dcwhite** [comment]
I found the source code in svn so it should be pretty easy to convert.
