### ISSUE TITLE
Linux Crash with InterfaceWithPython

### ISSUE THREAD

**Issue by dennisnjeru** [SCIInstitute/SCIRun#2374]
**Describe the bug**
SCIRun crashes with segfault when using interfaceWithPython and a FieldOutput. 
Sometimes we get 
```
[2022-03-16 15:05:47.026] [root] [critical] producer is done with bad group, something went wrong. probably a race condition...
Segmentation fault (core dumped)

```
[test_interfacewithpython.zip](https://github.com/SCIInstitute/SCIRun/files/8274201/test_interfacewithpython.zip)

**Version**

v5.0-beta.Z.2021lunch

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.10

**Comment by dcwhite** [comment]
That error message usually happens with more complex networks. This is a pretty simple network, works fine on Mac. How often does the crash happen with it on Linux?

**Comment by jessdtate** [comment]
@dennisnjeru Can you try the network without the python console open?

**Comment by jessdtate** [comment]
may be just #2093

**Comment by RubioJr9** [comment]
Tested on @dennisnjeru's machine. Confirmed that the Python Console was open. Closing it solved the issue. This is okay to close.
