### ISSUE TITLE
SplitFileName Pathname empty on windows

### ISSUE THREAD

**Issue by ChantelC** [SCIInstitute/SCIRun#2375]
**Describe the bug**
Calling a scirun script from the command line on windows. 
SplitFileName from a ReadField that is set using an environment variable. The Pathname port is empty but the base, extension, and filename all work. 
The filepath is D:\Data\Chantel\UW\c765c3\Imaging\Registered\Electrodes\GeoStim\Repositioned\cont_pos_N_S_C.stl

**In all bug cases, some combination of screenshots, sample network(s), and input data should be attached. You can use any cloud storage links you want for networks and data.**

**To Reproduce**
I have attached the two python scripts one calls the seeg function to visualize leads and that calls scirun from the command line. I also attached the cont_pos_N_S_C.stl file.
[filepath_bug.zip](https://github.com/SCIInstitute/SCIRun/files/8306467/filepath_bug.zip)

**Expected behavior**
Pathname should be D:\Data\Chantel\UW\c765c3\Imaging\Registered\Electrodes\GeoStim\Repositioned\ instead of an empty string

**Version**
v5.0-beta.Y+Qt5.14.2

**Desktop (please complete the following information):**
 - OS: Windows
<img width="509" alt="image" src="https://user-images.githubusercontent.com/30699490/159050277-6639066e-d8f1-4164-bb83-038e47a1ba93.png">

**Comment by dcwhite** [comment]
The module was never tested on Windows, and it never worked there. I fixed it to be cross-platform.
