### ISSUE TITLE
Last ViewScene improvements for ZZZ

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2393]
Works much better now. Windows don't pop up unless you hover for a second. They show up in a usable location. Just a few things not completely working:

1. "Look down axis" menu didn't do anything when I tested it.
![Screen Shot 2022-07-27 at 23 01 25](https://user-images.githubusercontent.com/20671873/181412150-001f663a-539d-4b6e-8891-9a3f10b3c115.png)
2. It would be helpful for the lighting menu to have a reset button. If you screw up the values now it's hard to get them back to something usable.
![Screen Shot 2022-07-27 at 23 03 59](https://user-images.githubusercontent.com/20671873/181412172-b027b1bb-3b5b-4132-8c0f-2f50c2d9f848.png)
3. It would be helpful if the scale bar menu had a color option. The bar is currently white, which is not visible on a white background. 
![Screen Shot 2022-07-27 at 23 04 51](https://user-images.githubusercontent.com/20671873/181412187-1c613989-b518-421c-8879-ed50461117d5.png)

_Originally posted by @Sumientra in https://github.com/SCIInstitute/SCIRun/issues/2390#issuecomment-1197603885_

**Comment by jab0707** [comment]
the look down axis seems to work for me, but only when I click the button after selecting which axes to look down etc

**Comment by jab0707** [comment]
it would be helpful to have a "close all popups" button somewhere because occasionally they still get stuck open, and sometimes such that they cover the widget so that there is no way to get them to close

**Comment by dcwhite** [comment]
If you click the render window interior the popups should all close. But sometimes they pop back up. With the latest code this should not happen anymore though.

**Comment by dcwhite** [comment]
Combine 3 secondary light buttons: 
- [ ] on/off is now a enable toggle
- [ ] button will switch on/off the enabled lights
Saves 2 button spots.

**Comment by dcwhite** [comment]
New tab in preferences for render options
- [ ] Move 2 existing ones
- [ ] Expose 2 pop-up timing parameters

**Comment by jessdtate** [comment]
Here is an idea for some toolbar categories:
main:
 - autoview
 - object selection
 - snap to axis
 - lock view
 - screenshot
 - autorotate
render options:
 - scene color
 - orientation glyph
 - clipping
 - fog
 - materials
 - headlight
 - secondary light
 - scale bar
Advanced
 - Grouping
 - mouse controls
 - reporting

**Comment by dcwhite** [comment]
I've rearranged the toolbars into three, all movable; consolidated the 3 light buttons into 1; and implemented a gray-scale color option for the scalebar which is saved in the network file. Those will go into beta.ZZZ. For release after next (full 5.0) will be the additional toolbar config ideas, the undo/redo for the material options (along with every other screen, I hope), the look-down improvement, and the light toggle button improvement.
