### ISSUE TITLE
widget duplicate port problem

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#2397]
When using composite widgets (editmeshboudingbox and showandeditdipoles) there are problems when two of the same ports are sent to the same viewscene module -- the transform is applied twice.  GenerateSinglePointProbe does not seem to have the same problem, nor does GeneratePointSamplesFromField.  

I suppose the ideal solution would be to ignore the second port, but a check and an error would also work.  

[widget_duplicate_ports.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/9286070/widget_duplicate_ports.srn5.zip)

**Comment by dcwhite** [comment]
Should be a quick fix in the generic code to back propagate execution requests--check if same originating output port.
