### ISSUE TITLE
Embedded python tutorial

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#250]
I'd like to improve on Seg3d implementation and make it easier for users to start using the python interpreter and headless mode. A built-in tutorial would go a long way. 

- [x] First step: create basic text PythonWizard and attach to menu option. 
- [x] @dcwhite Do retrieve old example scripts from IBBM folder. 
- [x] @dcwhite Found the file, copy it here for reference and testing. 
- [x] @dcwhite will provide a function object to call that pastes a string in the python console from the wizard. 
- [x] Add buttons to test above function, using lines from script.
- [x] Will meet with @jessdtate to discuss level of detail.
- [x] @dcwhite Change python func to execute the input string
- [ ] @dcwhite See if ViewScene works enabled again
- [ ] Set save path as data directory
- [x] Combine pages into larger chunks. Start with more granular, then combine into bigger later on.
- [x] Add file input example: load a network
- [ ] change data file input parameter
- [x] Page for Wand button/runScript action
- [x] Page for InterfaceWithPython module
- [ ] Page for looping example with GetMatrixSlice (with help from @jessdtate)

**Comment by dcwhite** [comment]
This can come AFTER IBBM's initial hands-on tutorials; essentially convert those into code/wizards.

**Comment by dcwhite** [comment]
I'll grab @gduffley's scripts from the IBBM folder and use those.

**Comment by dcwhite** [comment]
Start with a text-based API description in a GUI window. Add known limitations.

**Comment by dcwhite** [comment]
@jessdtate Another good intern one?

**Comment by jessdtate** [comment]
Yeah, I think so.

**Comment by dcwhite** [comment]
Here is the IBBM tutorial script (needed a zip to upload here)
[python_lab_isosurface.py.zip](https://github.com/SCIInstitute/SCIRun/files/3843861/python_lab_isosurface.py.zip)
:
