### ISSUE TITLE
Better 2D plotting widget

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#254]
For SolveLinearSystem, for example.

Possibilities:
http://www.workslikeclockwork.com/index.php/components/qt-plotting-widget/
http://qwt.sourceforge.net/

Start with Qwt: license looks better.

- [x] Include Qwt files in src/Interface/Modules/Math
- [x] SolveLinearSystem error graph
- [x] some signal slot connections

**Comment by benjaminlarson** [comment]
To build Qwt: 
http://qwt.sourceforge.net/qwtinstall.html
To summarize:
1 - download, put in C:\Qwt or preference
2 - Configure the pro file using qmake. Using windows cmd "C:\Qt2013\bin\qmake.exe  qwt.pro"
3 - nmake
4 - nmake install

**Comment by benjaminlarson** [comment]
Cmake suggestions: 
https://github.com/jcfr/QwtExample/blob/master/CMakeLists.txt
and 
http://www.cmake.org/Wiki/CMakeUserFindQwt

**Comment by benjaminlarson** [comment]
For the designer plugins, after building qwt: 
1- copy: qwt_designer_plugin.dll, qwt_designer_plugin.exp, and qwt_designer_plugin.lib
from - C:\qwt-6.1.2\designer\plugins\designer
to - C:\Qt2013\plugins\designer

**Comment by aylakhan** [comment]
Are these the only Qt-based widgets we've come up with?

**Comment by dcwhite** [comment]
Here's another option from Qt directly:
http://doc.qt.io/QtCharts/qtcharts-getting-started.html

**Comment by aylakhan** [comment]
Looks nice, but sadly only available under commercial licenses.

**Comment by dcwhite** [comment]
@benjaminlarson Is there any code for this one? Could you do a PR if so?

**Comment by dcwhite** [comment]
@benjaminlarson Noticed https://github.com/benjaminlarson/SCIRunGUIPrototype/commits/benSolveLinearSystem. Make a PR, but not merged into SCIInstitute/master, SCIInstitute/someOtherBranch so we can work on it more.

**Comment by benjaminlarson** [comment]
@dcwhite I can't create a branch in SCIInstitute/SCIRun... If you could make one I'll PR on it.

**Comment by dcwhite** [comment]
Try https://github.com/SCIInstitute/SCIRun/tree/qwt

**Comment by benjaminlarson** [comment]
![solvelinearsystem](https://cloud.githubusercontent.com/assets/6341316/5925962/9f337098-a624-11e4-94c5-3562fbcb304c.PNG)

**Comment by benjaminlarson** [comment]
![solvelinearsystem2](https://cloud.githubusercontent.com/assets/6341316/5926111/e228b060-a625-11e4-871b-a8eea99fb45c.PNG)

**Comment by benjaminlarson** [comment]
@dcwhite @aylakhan if there is a function or range you'd like plotted let me know. It will take me 5 seconds.

**Comment by dcwhite** [comment]
@aylakhan This looks pretty nice. If we can agree on using Qwt, I can merge Ben's work, close this issue, and open several more for integrating Qwt and adding to various modules.

**Comment by aylakhan** [comment]
Barring writing our own, Qwt is the only viable option right now. The graph looks very good.
