### ISSUE TITLE
Clipping Planes: Spire

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#256]

**Comment by aylakhan** [comment]
@cbrightsci - please add a brief summary of what needs to be done

**Comment by aylakhan** [comment]
Minimum functionality: axis-aligned clipping planes.

![sr4_clipping](https://cloud.githubusercontent.com/assets/1399377/11641275/9d321a20-9cf4-11e5-832e-5db00604fc99.png)
