### ISSUE TITLE
Integrate Python: basic network control via Python commands/functions, part 2

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#266]
- [x] add module
- [x] execute network
- [x] remove module
- [x] add connection
- [ ] remove connection
- [ ] duplicate module
- [ ] new network
- [ ] load network
- [ ] save network
- [ ] remove module
- [ ] quit

And the main deliverable:

- [ ] have scirun.exe take a python script file and execute it, using the available above functions.

**Comment by dcwhite** [comment]
For Milestone Y, the above checked commands work on Windows only. Mac currently does not support Python-wrapped C++ objects for some reason (my feeling this is a regression in boost::python code, since it worked with an older version of boost+python back in 2013).

**Comment by dcwhite** [comment]
Linux is untested.

**Comment by dcwhite** [comment]
@aylakhan I'd like to close this issue for Y and reopen two more for Z: fix Mac python module wrapper, and continue working on commands.

**Comment by aylakhan** [comment]
Sure - that's a good idea
