### ISSUE TITLE
Test #179: Python Console

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#268]
Tests #179. 

This requires Windows with Python 3.3 installed.  Contact @dcwhite (by commenting on this issue below) if you are interested in testing now. The next release will make it much easier to test this.

**Comment by dcwhite** [comment]
This issue should be passed around to everyone to test and comment on. We need feedback.

**Comment by dcwhite** [comment]
As of today, Python works on Windows and Mac by building with Python turned on. No external Python install is needed.

**Comment by jessdtate** [comment]
When I run the python console: read = addModule("ReadMatrix"),  I get errors:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<SCIRun::PyModule>

This causes the read to be unassigned, though the module is placed in the network.  This happens with most modules I try, except one time with EvaluateLinearAlgebraUnary.  I was able to get this command to run without error: eval = addModule("EvaluateLinearAlgebraUnary").  However, it did not recognize the input parameters: eval.Operator or eval.ScalarValue.  I was only able to to this once.

**Comment by dcwhite** [comment]
Yes, that is the Windows-only API. Mac has new functions to use, which use all strings as input. Try this:
```
read = scirun_add_module("ReadMatrix")
scirun_set_module_state(read, "Filename", "/dev/foo.mat")
```
For an example, look at src/ExampleNets/pythonScripts/loopOverState.py.

**Comment by dcwhite** [comment]
Sorry for lack of documentation on new API. I will update the wiki page.

**Comment by jessdtate** [comment]
OK, that works better.  
I do still get errors when I try this line:
scirun_set_module_state(read, "Filename", "/dev/foo.mat")
error:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: Module state key Filename not defined.

If I open the UI, then the state variable can be set.  I am able set the state variables for other modules (EvaluateLinearAlgebraUnary: Operator, ScalarValue) without opening the UI.

**Comment by dcwhite** [comment]
Argh, I fixed that problem in ReadField. ReadMatrix needs its own fix. Give me a second...

**Comment by dcwhite** [comment]
This is the other, easier testing issue. If everyone can pop up a working python console, we can close this one.
