### ISSUE TITLE
Fix clang warnings

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#271]
I noticed some important ones, like initialization order and unused variables.

**Comment by dcwhite** [comment]
http://stackoverflow.com/questions/2368811/how-to-set-warning-level-in-cmake

**Comment by dcwhite** [comment]
http://stackoverflow.com/questions/4750880/can-i-treat-a-specific-warning-as-an-error

**Comment by dcwhite** [comment]
http://stackoverflow.com/questions/14231292/cmake-and-compiler-warnings

**Comment by dcwhite** [comment]
Make a report for Windows (Visual Studio 2015), Mac (clang), and Linux (gcc via Travis-ci).

**Comment by allywarner** [comment]
[clangWarningsReport.pdf](https://github.com/SCIInstitute/SCIRun/files/326423/clangWarningsReport.pdf)

**Comment by allywarner** [comment]
Mac clang warnings attached above.
