### ISSUE TITLE
Label objects in ViewScene

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#278]
Feature request from ECGToolkit feedback:

Labeling the objects in the ShowField modules (I think user meant ViewScene) would greatly help to differentiate them in complex displays (e.g. like in the torso tank simulation where one may wish to hide some of the displayed content).

**Comment by dcwhite** [comment]
@jessdtate IBBM

**Comment by dcwhite** [comment]
Let's design a new module that can take advantage of ShowField's text labeling....

**Comment by dcwhite** [comment]
This is working well enough.
