### ISSUE TITLE
Meet with users to look at graphics examples

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#28]
@cbrightsci will meet with:
- [x] Moritz (@moritzdannhauer): 4th floor office
- [x] Josh Blauer: 4th floor north side lab
- [x] Jess Tate (@jessdtate): 4th floor south side lab
- [x] Brett (@zaracay): 3rd floor north side lab

**Comment by cbrightsci** [comment]
Met with them a few times during test lunches. Will continue in future lunches.
