### ISSUE TITLE
Refactor Core/Datatypes

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#286]
The Field and Mesh classes should be placed in a Field subdirectory. Matrix classes should go in a Matrix subdirectory. It may be reasonable to place basic types such as Scalar and String in their own subdirectory as well. Same with Geometry.

Core/Utils/TypeIDTable is only used by Core/Datatypes classes and therefore should be moved to Core/Datatypes.

**Comment by dcwhite** [comment]
Check when `LegacyField` is used.
