### ISSUE TITLE
Subnets

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#287]
- [ ] network editor creation button: check if selection is fully path-connected
- [ ] Subnet module (composite pattern) needs to be implemented in GUI and dataflow
- [ ] Connections
- [ ] UI button behavior--how about connection picker?
- [ ] serialization
- [ ] other module interactions: delete, duplicate, etc

**Comment by zaracay** [comment]
Feature Requests:

1 - Duplicatable
2 - Ask user if they really, REALLY want to have every UI pop up display when they select the UI button

**Comment by dcwhite** [comment]
http://scirundocwiki.sci.utah.edu/SCIRunDocs/index.php/CIBC:Documentation:SCIRun:UserGuide:Networks#Creating_a_Sub-Network

**Comment by dcwhite** [comment]
Everything left over here is now on the above issue.
