### ISSUE TITLE
UVF/Tuvok-related issues

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#293]
Make github issues for these (e.g. a new Module, algorithm, file import, data on the mesh...)

**Comment by aylakhan** [comment]
Does this still apply? I think this issue is stale.

**Comment by dcwhite** [comment]
What's the plan for volume rendering in SCIRun 5?

**Comment by aylakhan** [comment]
I'm going to close this in favor of more specific issues.
