### ISSUE TITLE
Connection selection should match v4

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#305]
Right now the default GUI for a selected connection is not very good, especially when there are many connections--it's hard to see which connection is selected.

**Comment by dcwhite** [comment]
v4 has no "selected connection GUI"--there's no need for one. v5 supports keyboard deletion so that's why this is important, but it seems like it might be hard to customize the dotted rectangle selection UI provided by Qt.

**Comment by dcwhite** [comment]
@jessdtate Could you test this and give a verdict on fix/archive? Thanks.

**Comment by jessdtate** [comment]
I have a hard time remembering this. Is this for when the pipes are all on top of each other?  If so, the pipe selection is about as good as it is in 4 now.  Therefore it can be definitely archived if not closed.

**Comment by dcwhite** [comment]
Correct. There's probably no perfect GUI for this, when it gets to be a mess of pipes. I'll close it.
