### ISSUE TITLE
Network editor mini-map, part 2

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#318]
I have a working version of this that will be delivered in E. This issue is to continue the work to make it match SCIRun 4's mini-view.

**Comment by dcwhite** [comment]
@SCIInstitute/cibc-users @SCIInstitute/scirun-users @SCIInstitute/scirun-developers Calling all users of v5: what's your thinking on this unimplemented v4 feature? Please comment.

**Comment by zaracay** [comment]
In large networks, I'll actually use the minimap, so I would like to see it.  The zoom feature makes it less of a priority, but I just tested a large network and the zoom doesn't work great for navigating around a large network

In favor of keeping: 1
In favor of eliminating: 0

**Comment by jessdtate** [comment]
The scrolling combined with autoview for the network are pretty good tools.  I think the mini map could be nice, but I think it can be at least archived for now.
