### ISSUE TITLE
Module porting: RescaleColorMap

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#325]
Top 10 module: # 4.

Test network: 
https://github.com/SCIInstitute/SCIRun/blob/master/src/ExampleNets/regression/rescaleColorMap.srn5

First step to testing this module is to turn off ShowField's rescaling. Comment out the body of this function:
https://github.com/SCIInstitute/SCIRun/blob/master/src/Modules/Visualization/ShowField.cc#L287

Then run the network above. If RescaleColorMap is working correctly, it will replicate what SCIRun 4 produces:

![withandwithoutrescalecolormap](https://cloud.githubusercontent.com/assets/1399383/6495605/e8916b52-c288-11e4-81be-b9f8e8618a81.PNG)

**Comment by brigb123** [comment]
completed with fc87b9a

**Comment by dcwhite** [comment]
Needs testing before closing :)

**Comment by dcwhite** [comment]
@brigb123 Let's push this one to next month. We need several requirements and design meetings to do it right. I'll close the PRs.
