### ISSUE TITLE
Enable scripting and dynamic functions for fields and field data

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#335]
Python can play a role here. See SCIRun 3 and its dynamic compilation. Suggested by Darrell.

**Comment by dcwhite** [comment]
@jessdtate Is this issue moot with the introduction of InterfaceWithPython? That is, would it be useful to be able to call python from within the GUIs of Create/CalculateFieldData and similar modules?

**Comment by jessdtate** [comment]
the IWP module does fulfill these needs.  I'm not sure it would buy us much to have them in the parser.  I suppose it would depend on how hard it is to implement.  

The same goes for the dynamic compilation.

**Comment by dcwhite** [comment]
Thanks. It would be annoying and difficult, and not buy much. Dynamic compilation is also covered by Python in general.
