### ISSUE TITLE
Python on Mac bug #1: failed importing

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#368]
Example from running a script with some imports:

![screen shot 2013-06-05 at 3 01 16 pm](https://f.cloud.github.com/assets/1399383/614695/28f212a2-ce23-11e2-9db4-52051cf385e3.png)

Usually the second attempt, the same import will crash SCIRun with this error:

![screen shot 2013-06-05 at 3 02 55 pm](https://f.cloud.github.com/assets/1399383/614705/51bb79e4-ce23-11e2-82ab-7d6adf8c9171.png)

**Comment by aylakhan** [comment]
This should work on OS X now.

**Comment by aylakhan** [comment]
Should also work on Windows.

**Comment by aylakhan** [comment]
Works on OpenSuSE.
