### ISSUE TITLE
User testing: SCIRun Python interface

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#370]
Please check out https://github.com/SCIInstitute/SCIRunGUIPrototype/wiki/SCIRun-Python-API and then give the API a try. Access the Python shell from SCIRun with Cmd-Shift-Y, then try running a script directly with the --script command line option.

Then comment away below! This will be one of the main killer features of SCIRun 5, so we want lots and lots of testing and feedback.

**Comment by dcwhite** [comment]
This will be the main feedback issue for tomorrow's testing lunch.

**Comment by jessdtate** [comment]
matrix output for pythoninterface is not correct.  

matrix sent = [[1,2,3],[4,5,6]]
matrix seen = [[ 1,1,1],[5,5,5]]

**Comment by jessdtate** [comment]
string output has a lot of stuff:

output:
INPUT FROM InterfaceWithPython:0 port 2 NAME = InputString  Typename: String straight outta python

string should be :
'String straight outta python'

**Comment by dcwhite** [comment]
Fixed!
