### ISSUE TITLE
Add module support for streamlines with varying radii

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#387]
Related to https://github.com/SCIInstitute/SCIRunGUIPrototype/issues/386.

Existing streamline generating modules may have to be extended or new modules written to support rendering streamlines with varying radii.

There may also have to be support for the [SWC file format](http://research.mssm.edu/cnic/swc.html).

**Comment by dcwhite** [comment]
Closed and added to Archive Project.
