### ISSUE TITLE
Readfield loading tensor data fails

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#470]
ReadField: It seems that triangle surfaces (it seems to work for tet meshes in SCIRun5) do not work with tensors (6 elements) defined on elements or nodes. Vectors work fine.

**Comment by dcwhite** [comment]
@moritzdannhauer I seem to have misplaced the tensor field file you sent me. Do you remember if this is a general problem with any tensor field file? I will try to generate some cases from v4.

**Comment by moritzdannhauer** [comment]
I just tested tensors defined on triangle nodes and faces - it seemed to work.
However, the tensors defined on tetrahedral nodes or elements as well as for a point cloud did not work with readfield. Sent you an email with example data ...

**Comment by dcwhite** [comment]
It's fixed. It was another example of code clean up that broke serialization (an int used as a bool changed to a bool in this case).
