### ISSUE TITLE
Cleaver issues

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#486]
Stemming from #484:
- [ ] Include path is off: need a separate cleaver/include/cleaver directory
- [ ] Built as static or dynamic library? If latter, needs Windows dllexport stuff
- [ ] Replace "hard-coded" version with external library
- [ ] Exit calls removed--will get for free once we point to repo version.
- [x] GUI needs to be shrunk a bit, too spaced out on Windows
- [ ] @moritzdannhauer's padding issue

**Comment by dcwhite** [comment]
This module in a holding pattern, waiting on Cleaver 2.

**Comment by aylakhan** [comment]
Depends on #1407.

**Comment by dcwhite** [comment]
@jonbronson @jessdtate Here is one of the SCIRun/Cleaver issues we can discuss this week.
