### ISSUE TITLE
Migrate SCIRunData.

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#522]
Move SCIRunData from GForge Subversion repo to GitHub.

**Comment by dcwhite** [comment]
Let's explore GitHub Large File System for this.

**Comment by aylakhan** [comment]
Add Superbuild External for downloading SCIRunData from GForge SVN to bin/SCIRun.

**Comment by collint8** [comment]
I'm seeing advice to download the data from Gforge and to move the data to Github. Which would you like me to do?

**Comment by dcwhite** [comment]
Keep it in gforge for now. There will be a future issue to go through it, trim down the large files, and transition to github. This issue is to automate the download only.

**Comment by dcwhite** [comment]
Closed with #1607
