### ISSUE TITLE
ES Renderer: Tensor eigenvalues for tensor field coloring

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#531]
Requires Teem, which is available now.

**Comment by jessdtate** [comment]
@cbrightsci Is this on either of your old branches?

**Comment by dcwhite** [comment]
@jessdtate @RubioJr9 Can this one be closed now?

**Comment by jessdtate** [comment]
I think so.  I think it was in the last tensor merge

**Comment by RubioJr9** [comment]
I'm not fully sure what this ticket is requesting. Is this referring to RGB conversion?

**Comment by jessdtate** [comment]
This one might actually be for showfield, but I think that is implemented

**Comment by RubioJr9** [comment]
Aren't tensors only rendered with ShowFieldGlyphs?
