### ISSUE TITLE
Sorted Triangles

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#556]
Unsure as to the usefulness of this. We saw rendering
 artifacts in old scirun, inside of a single mesh object, that were indicative
 of incorrect triangle ordering.

**Comment by jessdtate** [comment]
@cbrightsci Could you elaborate on this one at all? If not, you can close it.

**Comment by cbrightsci** [comment]
There doesn't seem to be a need for this. Closing.
