### ISSUE TITLE
Color Map Interface

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#557]
Load and generate color maps -- not difficult.
 All rendering code is there, just need to create color maps. All code
 to generate color maps is at the bottom of SRInterface.h. If UI is finished.

**Comment by dcwhite** [comment]
We added Blackbody. I'll push this one until everything is stabilized.

**Comment by dcwhite** [comment]
There are issues made for the various features left to do. Closing this one now.
