### ISSUE TITLE
Approx Rendering (approx_div=0)

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#558]
Did not implement approximate rendering.
 I was unsure if it was used in old scirun, so I didn't both
 implementing it (affects edges and faces). See if this type of rendering is necessary.

**Comment by jessdtate** [comment]
@cbrightsci Same as #556.

**Comment by cbrightsci** [comment]
Not needed. If requests in the future look like they would need approximate rendering a new ticket can be made.
