### ISSUE TITLE
Add complex number support: scalars, matrices 

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#56]
Extend any real-number operation that makes sense. 

Essentially wrapping std::complex--interesting exercise in templates. 

New datatype for sure...new color?

Jess can supply example networks: algorithms, modules, etc.

----
This issue will encompass the following:
- [x] Create new official SCIRun datatype, with a new color. It will not be compatible with the existing real matrix type at this time. (Dan)
- [x] Add two simple modules, SendComplexMatrix and ReceiveComplexMatrix, to test the type in a network.

New issues will be created for next steps after that.

**Comment by moritzdannhauer** [comment]
I categorized the modules (which is debatable) that might need complex number support at some point:

1) high priority:
BuildFEMatrix, BuildTDCSMatrix, BuildBEMatrix(?)
SolveLinearSystem, SolveMinNormLeastSqSystem
AddKnownsToLinearSystem, AddLinkedNodesToLinearSystem
BuildVolRHS

2) medium-priority (those work on field data from possibly complex-valued simulations) 
CalculateGradients
CalculateCurrentDensity
GenerateStreamLines
GetFieldData

3) low-priority (general modules that could input and output complex-valued matrices)
AppendMatrix, CollectMatrix, GetSliceMatrix, SelectSubMatrix, SetSubMatrix 
CreateMatrix, ConvertMatrixType 
ComputeSVD, ComputePCA
EvaluateLinearAlgebraBinary, EvaluateLinearAlgebraUnary
ReportMatrixInfo

**Comment by dcwhite** [comment]
As expected, that's a lot of modules. Can we get a streamlined set for an initial deliverable?

**Comment by moritzdannhauer** [comment]
Category 1) is most valuable!

**Comment by dcwhite** [comment]
Clearly. By streamlined, I mean <5.

**Comment by moritzdannhauer** [comment]
Ok, how about those 3:
BuildFEMatrix
SolveLinearSystem
BuildTDCSMatrix

**Comment by dcwhite** [comment]
Next step: make a goal network, and post an annotated screenshot here. Notes can be pointing to where complex data is input/output/processed.

**Comment by dcwhite** [comment]
Also comment on the typical matrix/field sizes you'll want to try.

**Comment by moritzdannhauer** [comment]
Our goal is to use them for regular head geometries of about 100k..10M field nodes and matrix columns/rows.

**Comment by moritzdannhauer** [comment]
This is the simplest network I can think of right now.

![screen shot 2016-03-09 at 12 58 33 pm](https://cloud.githubusercontent.com/assets/2054570/13645011/c68d3710-e5f6-11e5-8037-f385bd86c6ae.png)

**Comment by dcwhite** [comment]
Thanks. I assume every object passed around there will be complex-valued. So matrices and fields are needed.

**Comment by dcwhite** [comment]
From Slack:
```
We could first do Matrices only and then extend to Fields.

dwhite [11:06 AM] 
does that mean the LHS matrix coming out of BuildFE would be real? or would BuildFE compute a complex matrix from a real field

moritz [11:07 AM] 
BuildFE would get a complex field and generate a complex matrix (edited)
```

**Comment by dcwhite** [comment]
How could we do matrices only first then?

**Comment by dcwhite** [comment]
I guess we could start with SolveLinearSystem only.

**Comment by moritzdannhauer** [comment]
I guess the first logical step is this:
![mockup](https://cloud.githubusercontent.com/assets/2054570/13676761/162c6c82-e6b5-11e5-9593-e7ecee610a3a.png)
1) So, we could simply treat any 2 element vector that happens to be data of a field as a (real, imag)-pair.
That would not require too many modifications, right?

2) We would need to create a Eigen Complex Matrix in an adjusted version of BuildFEMatrix.
Should the output be complex by default or possibly also real based on a GUI option?

**Comment by moritzdannhauer** [comment]
1) Ok, to be useful for BuildFEMatrix it needs to be a Field though and for now 2 element vector that holds a real and the imaginary part sounds very simple to me.
2) Sounds good, going complex needs a new color. How about red or brown?

**Comment by dcwhite** [comment]
1) The input is a complex field, but ReadField would just read the geometry, then two ReadMatrix modules to read in real and imaginary parts of the field data, then a module to combine into a complex matrix, then SetFieldData to set the complex data. This way no new I/O code is needed.
2) Red is reserved for errors and selections. I'll try brown. It's easy to change. Or should it be blue-ish since it's very similar to matrix blue?

**Comment by moritzdannhauer** [comment]
1) Ok, sounds reasonable.
2) Not many basic and distinctive colors are left. Black might not be distinctive. 
Brown then...
