### ISSUE TITLE
Save state of toolbars and dockwidgets on main window

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#568]
Main window ones are easy (see http://qt-project.org/doc/qt-4.8/qmainwindow.html#saveState), but will need to think about how/where state of module UIs are saved--probably in a session file corresponding to the network file rather than the global QSettings. Or, could store them in global QSettings but keyed off of the network file name.

**Comment by jessdtate** [comment]
Let's add yes/no for ViewScene, saved in the module state. That will close this. New issues for other modules and VS state will be made.
