### ISSUE TITLE
Linking SCIRun executable with WinMain entry point fails

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#574]
Applies to winInstaller branch. Linking SCIRun executable with WinMain entry point (created by adding WIN32 parameter to CMake command ADD_EXECUTABLE) fails with error LNK2019: unresolved external symbol WinMain referenced in function _tmainCRTStartup.

**Comment by dcwhite** [comment]
#856 broke command line arguments being forwarded. Told @mhansen1 to build RUN_TESTS to verify fix.
