### ISSUE TITLE
More module porting: actgauss-newton-inverse

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#589]
- [ ]  InterfaceWithMatlab (yikes)
- [x]  BuildSurfaceLaplacianMatrix (there are other matlab inverse implementations that do not require this module that we could use instead)

**Comment by dcwhite** [comment]
@jessdtate Can this one be converted to use InterfaceWithPython?

**Comment by jessdtate** [comment]
I've looked into most of the networks that use matlab in the fwd/inv toolkit and they should all work with python.  @jcollfont  was talking about restructuring some of these examples to make them a little simpler to.

**Comment by jcollfont** [comment]
Jess,

The restructure I am doing is on the Tihonov type of problems. That is any problem that is based on the regularied least squares minimization.

There are some of the matlab examples that are based on that and that could be ported.

The biggest limitation I find is that we do not have any method for convex optimization in SCIRun. Would it be possible to have some modules depending on external software such as CVX? We are already doing it for MATALB implementations.

**Comment by moritzdannhauer** [comment]
Hi Jaume, Seyhmus and I tried cvxpy with the new python interface of SCIRun5 for the reason be included permanantly. CVXpy is slightly different than CVX for matlab but maybe it is sufficient for 
your applications.

**Comment by jcollfont** [comment]
Huh!

Then we should write anything that needs optimization in python? Or have some module that solves convex problems by calling a pythin script?

**Comment by moritzdannhauer** [comment]
You just need to pipe in the matrices into the InterfaceWithPython. The actual optimization code running cvx is in that instance of the InterfaceWithPython module and can be saved too. I am sure we could provide snippets for InterfaceWithPython that include a generic optimization 'script' or some other way to have optimization framework ready. Maybe, if we separate the C++ code from the CVX-python code it might be easier to maintain and more usable for others ... just an idea.

**Comment by jessdtate** [comment]
I've converted the gauss-newton example to SCIRun 5 in the FwdInv toolkit.  it uses the same matlab code as the SCRIun4 implementation.  This issue can be closed.
