### ISSUE TITLE
Add Matrix<String> datatype to simulate string lists

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#596]
A convenience datatype, we can use Eigen's matrix template and just hold strings. Would need a new color. 

One interesting use case: a module reads a directory and outputs all file names as a list of strings. Using this would also be nicer than having to send one string as a concatenation of one's list of strings (requested by @moritzdannhauer).

**Comment by dcwhite** [comment]
@moritzdannhauer Is this still relevant since you can implement something similar in python now? If not, we will close it.

**Comment by moritzdannhauer** [comment]
Ok close it!
