### ISSUE TITLE
Limit size of expansion of mainwindow when pin all module UIs is clicked

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#631]
Tried it with a medium-sized network, and the UIs took up lots of space, pushing the view in the network editor down so you couldn't see any modules. Three aspects of a fix:
- [ ] Limit space on the right dock for module UIs
- [x] Somehow compress module UIs to mini-form so they all fit
- [x] Add a button to "center view" on modules in the network editor

**Comment by dcwhite** [comment]
Add automatic compression?

**Comment by dcwhite** [comment]
Needs some revisiting

**Comment by jcollfont** [comment]
Enabling the dock all option makes SCIRun quit with error:

QPixmap::scaled: Pixmap is a null pixmap
Segmentation fault: 11

**Comment by jcollfont** [comment]
It does not always repeat. I managed to set this option with no problem the second time I tried.

Maybe because I had less UIs to open?
