### ISSUE TITLE
Send message back to SCI for each valid user to record better statistics

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#632]
Idea from Nathan. Could use email (using https://github.com/bluetiger9/SmtpClient-for-Qt for example); could be voluntary or involuntary.

**Comment by dcwhite** [comment]
@jessdtate Needs exec-level discussion.

**Comment by dcwhite** [comment]
Basically same as #714, but anonymous.

**Comment by jessdtate** [comment]
The same issues for #714 apply here, with the added concern of privacy.

**Comment by dcwhite** [comment]
Close this as well?

**Comment by jessdtate** [comment]
The exec were concerned about credibility, though  something voluntary would work.  Mostly, they would rather you spend time on features.  If you think this is really easy to implement, I'm sure they won't mind it as long as it was an optional thing for the users.

**Comment by dcwhite** [comment]
http://www.qtcentre.org/threads/2221-Sending-email-using-Qt

**Comment by dcwhite** [comment]
Rather than try to send email with the SCIRun program, it's one line of Qt code to pop open the user's email client (using a `mailto` link). Thus it would be very easy to implement a voluntary message-back-to-us system. It could appear only the first time the user runs the program.

**Comment by jessdtate** [comment]
I'll bring it back to the exec and see what they think.

**Comment by dcwhite** [comment]
Any decision on this one? Useful for IBBM?

**Comment by jessdtate** [comment]
not for IBBM

**Comment by dcwhite** [comment]
Exec did not approve.
