### ISSUE TITLE
Beautify Module Widget part 3: Linux

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#648]
Continuation of #109.

- [ ] Module widget size is not scaling 100% to name (chops off last 6 letters in MFDFSTD for instance)
- [x] Checkboxes and radio buttons are missing outlines--hard to know they're there

**Comment by dcwhite** [comment]
Post-Qt5 #513

**Comment by dcwhite** [comment]
@jessdtate Might be one for @RubioJr9

**Comment by dcwhite** [comment]
Hey @RubioJr9 when you have a free 20 minutes, could you open up all the module UIs on your linux system and just check for any gross abnormalities? Thanks

**Comment by RubioJr9** [comment]
Yeah I can do that. One thing I have noticed is that the ViewScene options window does not let me move it around.

**Comment by RubioJr9** [comment]
I made it pretty comprehensive, but there are 4 critical ones listed up top.
[SCIRun_Linux_beautify.pdf](https://github.com/SCIInstitute/SCIRun/files/5575771/SCIRun_Linux_beautify.pdf)

**Comment by dcwhite** [comment]
I figured out a way to fix the invisible checkbox/radio button problem. But man those Linux module layouts are stubborn. I'll see what I get done today then push the rest for next milestone.

**Comment by dcwhite** [comment]
The module UIs on Linux look infinitely better NOT in 4k/hiDPI. @RubioJr9, what screen resolution did you use for your report?

**Comment by RubioJr9** [comment]
@dcwhite  I was using 1440p. The scaling is much worse in 2560x1600 on my 13" macbook. Text is a lot more cut off.
