### ISSUE TITLE
Network organization idea: button to rearrange modules based on execution order

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#661]
Just call the "parallel execution order" function and instead of executing, layout the modules in rows by execution group, in columns by name (?).

**Comment by dcwhite** [comment]
@gduffley This old issue sounds like something you'd like too.

**Comment by gduffley** [comment]
@dcwhite I'm not sure how easy it would be to do, because the outputs from modules being the inputs for different modules at different points downstream. That being said, if there is a way to do this, I am completely in favor of it. The neater we can make nets, the better
