### ISSUE TITLE
Module conversion: ShowColorMap, part 1

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#669]
Post-new renderer merge.

**Comment by dcwhite** [comment]
@cbrightsci @benjaminlarson @brigb123 I'll let you guys figure out how to divy this one up. Ben should add the module and make the GUI and leave the guts macroed out.

**Comment by benjaminlarson** [comment]
@dcwhite @cbrightsci @brigb123 Is anyone waiting on this? I have the GUI components done/implemented, but haven't figured out the text color option yet. I can PR now if you're ready, or wait till tomorrow.

**Comment by dcwhite** [comment]
@benjaminlarson Just do PR now, I'll merge it

**Comment by dcwhite** [comment]
@cbrightsci @brigb123 GUI and module skeleton are ready to fill in

**Comment by brigb123** [comment]
The scale draws now (no text) in a3479fde84ab96aab51a5d31948d9282a4985711. Color map needs to be forwarded exactly using the Color map object.

**Comment by brigb123** [comment]
3 color maps applied to faces and match scale bar. see 41d84fb28b528855ab81c9457583b2f6c942fd97

**Comment by dcwhite** [comment]
We can plan on closing this one after the test lunch tomorrow, then open a "Part 2" for the text labels and other features. A good start.
