### ISSUE TITLE
Registration option to gather better statistics

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#714]
From Nathan.

**Comment by dcwhite** [comment]
@jessdtate Needs exec discussion.

**Comment by dcwhite** [comment]
@jessdtate Any update on this one?

**Comment by jessdtate** [comment]
I haven't been able to get this in an exec meeting yet.  I will try for the next one.

**Comment by jessdtate** [comment]
The discussion we had with the exec concluded with the opinion that having users who publish with our software and can give statements support is the metric that will lead to more funding.  There is also the notion that increased steps will reduce the total number of users.  In light of those two ideas, the decision was that putting resources to registration would not help our funding prospects and should not be pursued.  This can be readdressed as funding opportunities appear.  This also applies to  #632
