### ISSUE TITLE
Matlab I/O library support, part 2: Write Matlab matrix has issues

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#715]
Right now we can read but not write Matlab matrix files. Pushing fix to next milestone.

**Comment by zaracay** [comment]
The WriteField Module in SCIRun 4 also has a .mat writing problem.  The reason that the files cannot be read is:

"Matrix 'tetmesh' cannot be translated into a SCIRun Field (one of the dimensions of fieldedge needs to be of size 4)"

There is no fieldedge in the file structure of the written .mat files...but there also isn't any such field in the Cleaver .mat outputs that are readable.

The file structure of the unreadble, SCIRun-written .mat files is:
scirunfield.fieldbasis
scirunfield.fieldbasisorder
scirunfield.fieldtype
scirunfield.field
scirunfield.fieldcell
scirunfield.meshbasis
scirunfield.meshbasisorder
scirunfield.meshtype
scirunfield.node
scirunfield.cell
scirunfield.property

The file structure of the readble, Cleaver-written .mat files is:
tetmesh.node
tetmesh.cell
tetmesh.field
tetmesh.fieldat

**Comment by aylakhan** [comment]
@zaracay please move your comments to a separate issue

**Comment by dcwhite** [comment]
I'll check python round-trip unit tests, this might be fixed.

**Comment by dcwhite** [comment]
@jessdtate Is this related to the scipy read problem?

**Comment by jessdtate** [comment]
I haven't seen any other problems with the matlab matrix files
