### ISSUE TITLE
Proper fix for #627

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#738]
#627 describes the Renderer start-up waiting/Timer problem. After merging I had to increase the wait period again since some regression networks were crashing. We need a proper solution, like locking the GUI thread during execution until the renderer is fully initialized.

**Comment by dcwhite** [comment]
@cbrightsci This can be delayed if we do some thorough testing on Gus, the demo machine.

**Comment by aylakhan** [comment]
Agreed. Please test all renderer and ViewScene module updates on Gus.

**Comment by aylakhan** [comment]
Must be done by R.

**Comment by dcwhite** [comment]
Bumping again. :-1:

**Comment by dcwhite** [comment]
@dcwhite Add cmd line parameter

**Comment by dcwhite** [comment]
@jessdtate IBBM

**Comment by dcwhite** [comment]
Will combine with #881.
