### ISSUE TITLE
Module porting: ConvertIndicesToFieldData

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#747]
Looks quite easy.

**Comment by dcwhite** [comment]
@benjaminlarson @jessdtate Goal of Tuesday?

**Comment by benjaminlarson** [comment]
@dcwhite any similar code, or idea how to do this? 
https://github.com/SCIInstitute/SCIRun/blob/master/src/Core/Algorithms/Legacy/Fields/FieldData/ConvertIndicesToFieldData.cc#L153
I believe we are trying to index into the dense matrix and set the value? I'm confused on  the first argument of the VField->set_value() call.

**Comment by dcwhite** [comment]
@benjaminlarson 
https://github.com/SCIInstitute/SCIRun/blob/master/src/Core/Algorithms/Legacy/Fields/FieldData/ConvertIndicesToFieldData.cc#L141

Eigen allows access to the internal pointer with the data() function, just change this call and the code that uses the pointer should work.
