### ISSUE TITLE
Boost versioning

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#759]
See #604

**Comment by aylakhan** [comment]
We have boost up to the latest (1.57) available for testing. Boost 1.57 is on [boost_1_57_test](https://github.com/CIBC-Internal/boost/tree/boost_1_57_test).

**Comment by dcwhite** [comment]
Tested with 1.58--will merge with master then @aylakhan can update boost repo's master to 1_58.

**Comment by dcwhite** [comment]
Closed with 12122da559df35eb0d62216f94e8ccd66a30c78f.
