### ISSUE TITLE
Set up CIBC-Internal/SCIRunTestData as external resource

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#764]
Download CIBC-Internal/SCIRunTestData as external resource if testing is enabled. It will make setting up and getting updates much easier, especially for automated testing.

**Comment by aylakhan** [comment]
Test data repo set up as CMake external. Closed in 685b24f3dd4141d113d50e65affc09d3b958909c.

**Comment by dcwhite** [comment]
I'll try enabling this in the travis build and see what happens.
