### ISSUE TITLE
ViewScene changes in N

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#766]
TODO

**Comment by cbrightsci** [comment]
Fixed the Back CULL 
Made normals face the proper direction. 
Fixed Index Buffer initialization. 
Made it so transparency objects are ordered in accord with the position of the camera. 
Configuration menu closes with the ViewScene. 
Adjusted Zoom. 
Fixed View of the Scene if adjusted without the mouse it was not updating the camera properly.
