### ISSUE TITLE
Tikhonov part 2

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#774]
Check the numbers, they are way off.

**Comment by dcwhite** [comment]
After fixing BuildNoiseColumnMatrix, the output looks much better. @jessdtate will verify one more time before closing.

**Comment by dcwhite** [comment]
@lizutah signed off on this one.

**Comment by aylakhan** [comment]
Let's make sure Jaume also gets a look at this before or at the next test lunch.
