### ISSUE TITLE
Fix stylesheet issues with experimental GUI

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#775]
Continuation of #758.

http://qt-project.org/doc/qt-4.8/stylesheet-examples.html

Main issues: 
- [ ] Disabled UIs are not distinguishable (try something out)
- [ ] File save/open dialog color scheme hasn't changed (may not be possible to change)
- [x] Tooltips need a dark style (global setting?)
- [ ] Dock widget titles don't conform (Mac)

Module UIs with problems:
* Windows
- [x] Table widget column headers in BrainStim, BuildBEMatrix
- [x] Tab widget tabs in BrainStim and ShowField

**Comment by benjaminlarson** [comment]
Tooltips weren't set globally, but work for the toolbars on the main window.

**Comment by dcwhite** [comment]
Rest pushed to #791
