### ISSUE TITLE
Gus Testing for demos

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#806]
Make sure:
- [x] Networks look good, i.e. module and connection layout 
- [x] All module GUIs are proper-sized
- [x] Copy network annotation from v4 files
- [x] Make notes more readable
- [x] Rendering is smooth
- [x] No dumb crashes
- [x] What else? @aylakhan @cbrightsci @brigb123 
- [x] Good network performance
- [x] All data and networks installed on Gus
- [x] ShowField GUI needs another pass after hiding widgets

**Comment by aylakhan** [comment]
- [ ] Good network performance

**Comment by dcwhite** [comment]
Having @benjaminlarson update the toolkit networks' module/connection notes.

**Comment by dcwhite** [comment]
Networks are updated so the layout is nicer. I couldn't test rendering speed, it seemed like something else heavy was running on the machine--after only a couple frames I got the rainbow spinner.

**Comment by dcwhite** [comment]
Monday morning I'll pull down latest code, build and run through the demos again. Barring any crashes or bad performance, this issue can be closed.

**Comment by dcwhite** [comment]
In testing we crashed while using Moritz's patch network. It was a problem with module ids--another ViewScene was added that had the same used ID. This led to crashes and other weird behavior. We'll try to replicate this post-EAB...

**Comment by dcwhite** [comment]
forward_problem was sluggish with play mode.
