### ISSUE TITLE
Edges arem

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#819]
faster transparency rendering isn't as nice with basic objects.

**Comment by dcwhite** [comment]
@cbrightsci You know you can edit the title after creating an issue right? :smirk_cat:

**Comment by cbrightsci** [comment]
@dcwhite The problem was that I fat-fingered the enter key when I was going for the apostrophe and that created the ticket. I knew I typod and hit the backspace key immediately and it brought me back to the issue creation where I finished the creation. I didn't realize the new issue had been created until I had created it again. I thought my only typo was the m until it was done.

Long story short... thanks for the info! :astonished:

**Comment by dcwhite** [comment]
I see. Lol. I think I've done that before.
