### ISSUE TITLE
ViewScene display toggle dropdown in menu bar, part 2

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#835]
Follow-up to #452.
- [ ] Need to be able to toggle pieces of each mesh input: faces, edges, nodes.
- [x] Better naming of objects coming in (right now just uses module IDs)
- [x] Test performance. Repeated clicking might cause problems. Probably want some sort of cache in place.
- [x] Make a nicer "display name" for the widget
- [x] Move the dropdown out, it doesn't behave nicely.

**Comment by dcwhite** [comment]
@jessdtate Here's the issue for splitting up the parts of a mesh in ViewScene object selection.

**Comment by dcwhite** [comment]
@cbrightsci will spawn a new issue for the first part and then close.

**Comment by cbrightsci** [comment]
closing and opening new issue for last part. #1462
