### ISSUE TITLE
Improve coloring in tikhonov-inverse visualization

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#837]
Users reported "too much glare" or something similar. @cbrightsci and @brigb123 suggested modifying shader code to tone it down a bit. 
![glare](https://cloud.githubusercontent.com/assets/1399383/6027574/4da72482-aba0-11e4-9ac7-0b81c1f769db.PNG)

**Comment by brigb123** [comment]
fixed with 34c192307c9d60ff3fd3361ee9af568d8db260c6
