### ISSUE TITLE
ShowField_save_settings

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#842]
ShowField does not save settings in the srn5 network file
After reloading settings are gone
Thanks!

**Comment by dcwhite** [comment]
Which settings in particular? A lot have been added recently. Specific replication steps would be nice.

**Comment by moritzdannhauer** [comment]
Colors appear not to be saved. Also, if you plot nodes as spheres also the size is not saved.
I will try to attach an srn5 network and input data in this thread.
P.S. I dont get an email when you comment on this issue.

**Comment by dcwhite** [comment]
@moritzdannhauer Nodes as spheres is disabled right now, so hold off on testing that. Which color, the "default mesh color"?

**Comment by moritzdannhauer** [comment]
How can I add some files here?

**Comment by moritzdannhauer** [comment]
Default is always gray

**Comment by moritzdannhauer** [comment]
I can visualize Spheres. And I like to have them

**Comment by moritzdannhauer** [comment]
1) Is there a way to make sure I get an email everytime you comment on my comments.
2) Do you want me to send you some files somehow?

**Comment by dcwhite** [comment]
@moritzdannhauer Yes, but sphere nodes are buggy now. We turned them off until it's stable. Patience. 

The issue interface only accepts images now. But you can paste a link to anything. Use Box or Dropbox preferably.

I'll test the color not being saved.

**Comment by moritzdannhauer** [comment]
thanks!

**Comment by dcwhite** [comment]
@moritzdannhauer Color saving is fixed in topic branch, will appear in Q release. I'll check node settings when we enable them.
