### ISSUE TITLE
Duplicate module with dynamic ports: needs testing

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#867]
@jessdtate reports strange behavior with CalculateFieldData, for example.

**Comment by dcwhite** [comment]
@jessdtate Tested this finally and it seems to work OK. Are you still having issues, and if so could you provide replication steps?

**Comment by jessdtate** [comment]
I should have documented this better to begin with.  a specific example is when you connect a field after a matrix (an number of matrices, and there might be a field too), the duplication will drop one of the connections be leave the port (hard to predict which).  If you try to reconnect it, SCIRun crashes.

**Comment by jessdtate** [comment]
Actually, I think it happens when a field has been connected, then disconnected, then reconnected, then the module duplicated.  Sounds complicated but is very common.

**Comment by jessdtate** [comment]
Another behavior that I was seeing before that I haven't been able to duplicate lately is that the duplicated module port actions would be linked to the original port and vis versa, so it was impossible to connect new modules to the duplicated port.  I don't think it crashed before though so maybe the crash is preventing that scenario.

**Comment by dcwhite** [comment]
Thanks. I will investigate these tomorrow.

**Comment by dcwhite** [comment]
Still a bug! I'll work on it next.
