### ISSUE TITLE
Module conversion: ShowColorMap, part 2

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#878]
Continuation of #669

Todo:
- [ ] Text size on Windows is way too small (pushed to #919)
- [x] Add Extra Space: change to X- and Y- spinner position selectors.

**Comment by brigb123** [comment]
completed with 7ca3baf. To be tested and merged into master with #877

**Comment by brigb123** [comment]
hopefully both fixed with #903 and #907
