### ISSUE TITLE
View Scene out-of-sync with Cylinders/Spheres

### ISSUE THREAD

**Issue by brigb123** [SCIInstitute/SCIRun#882]
When toggling between cylinders and lines for edges and spheres and points for nodes, as well as edges/nodes on/off, the view scene does not sync up with the required shader changes. In order to see the changes, ViewScene module must be deleted and re-added/connected to the network (sometimes twice if the axis doesn't show up). This works for OSX. @dcwhite says Windows does not respect the viewscene re-add.

To be tested with this commit : da6ec4f

This problem might be solved with #881 issue (except these problems occur 100% of the time).

**Comment by dcwhite** [comment]
I'll test after I implement #891

**Comment by dcwhite** [comment]
Working with the changes from #891. To be closed upon merging #877.
