### ISSUE TITLE
ShowField default coloring/rendering of vector and tensor data.

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#884]
From #270

**Comment by dcwhite** [comment]
@cbrightsci Is this branch getting merged soon?

**Comment by cbrightsci** [comment]
@dwhite the merge is a nightmare. It should be done soon.

**Comment by cbrightsci** [comment]
This will need to be redone... D:

**Comment by dcwhite** [comment]
@jessdtate will probe @cbrightsci's memory once again.

**Comment by dcwhite** [comment]
@jessdtate @RubioJr9 Is this one done too?

**Comment by RubioJr9** [comment]
Yes this was added for both vectors and tensors in https://github.com/SCIInstitute/SCIRun/pull/1868
