### ISSUE TITLE
Multithreading for GenerateStreamLines

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#888]
Single-threaded version is CPU-heavy, should be easy to parallelize.

**Comment by dcwhite** [comment]
@moritzdannhauer @SeyhmusGuler @jessdtate What's the priority of this one relative to all the other current issues/requests?

**Comment by jessdtate** [comment]
To me, this is less important than some of the missing features, but most of those are with the renderer (widgets, saving camera locations, scripting screen shots and the video options).  It would be nice to have by IBBM, but I think it would be low on the list.

**Comment by moritzdannhauer** [comment]
The renderer functionalities and a parallel version of generatestreamline have similar priority to me but not absolutely essential to IBBM. Lets talk again after IBBM to make it happen.

**Comment by dcwhite** [comment]
See #1209.

**Comment by dcwhite** [comment]
This is done, but has some potential numerical issues. We can close this after I add a checkbox to enable/disable multithreading.
