### ISSUE TITLE
SCIRun crash when include viewscene module

### ISSUE THREAD

**Issue by SeyhmusGuler** [SCIInstitute/SCIRun#890]
SCIRun5 crashes every time we are trying to put a vviewscene module in the network. 

It also breaks when loading a network with viewscenes.

This is a windows 7 machine with an integrated intel graphics card.

**Comment by SeyhmusGuler** [comment]
Intel(R) HD Graphics driver version: 8.15.10.2202

**Comment by dcwhite** [comment]
This is a known problem with Intel graphics. We have no workaround at this time, but you're the second to report it so we'll bump up the priority.

**Comment by ajanson** [comment]
Processor: Intel64 Family 6 Model 37

**Comment by gduffley** [comment]
This is happening to me every time I add a ViewScene. I am running the latest version, compiled from source, on my OpenSUSE13.2 workstation. The machine has a  GeForce GTX 970

**Comment by dcwhite** [comment]
@gduffley #701 is actually your issue. We have a fix in the works for Linux so watch that one.

**Comment by aylakhan** [comment]
Fix will be imeplementation of #853.
