### ISSUE TITLE
Refactor Geometry.h and ShowField.h using handle/body idiom

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#892]
Headers are too messy, they shouldn't expose all their internals.

**Comment by dcwhite** [comment]
@cbrightsci When do you head out of town? I will do this one while you're away.

**Comment by cbrightsci** [comment]
@dcwhite I leave Sunday.

**Comment by dcwhite** [comment]
Left to do: make a factory to create implementation classes. Goal is to remove all includes of GeometryImpl.h. Making a new issue for that.
