### ISSUE TITLE
CMake configure check: length of bin directory should be "small"

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#901]
Due to very long paths in certain external libraries, the Windows build can fail if the root binary directory (the path to SCIRun.sln) is longer than some threshold. We can provide a warning using CMake to point this out to those building on Windows. 

The CMake to use is
```
string(LENGTH ${CMAKE_BINARY_DIR} <output variable>) 
```
to get the length of the binary root and then a comparison with, say, 10; if the length is greater than 10, print a MESSAGE(WARNING "Binary directory is too long, the build might fail due to long path names"). 
This should all go inside a IF(WIN32) block since it's specific to that platform.

Let me know if you have any questions.

**Comment by mhansen1** [comment]
Just making sure, but this should be in the src/CMakeLists.txt file, right?

**Comment by aylakhan** [comment]
Yes. Try putting it near the top of the CMakeList.txt file, maybe just under the check for building in source directory (around line 50, I think).
