### ISSUE TITLE
Remove QWT headers from source

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#911]
QWT headers in source:
- [src/Interface/Modules/Math/qwt_global.h](https://github.com/SCIInstitute/SCIRun/blob/master/src/Interface/Modules/Math/qwt_global.h)
- [src/Interface/Modules/Math/qwt_plot.h](https://github.com/SCIInstitute/SCIRun/blob/master/src/Interface/Modules/Math/qwt_plot.h)

Should these be in the Qwt library (see #887)?

**Comment by dcwhite** [comment]
Yeah, they got slipped in there by Ben, should've moved them out.
