### ISSUE TITLE
Add RescaleColorMap module to toolkit networks.

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#913]
Update Forward/Inverse toolkit networks to use RescaleColorMap similar to the SCIRun 4 versions.

**Comment by mhansen1** [comment]
Just to make sure that I'm doing this correctly: For this I'm just adding in the RescaleColorMap module into the example networks in the same way that it was done in SCIRun 4, right?

**Comment by aylakhan** [comment]
Yes, that's correct.
