### ISSUE TITLE
Module porting: ClipVolumeByIsovalue (MarchingCubes)

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/SCIRun#922]
I would like to use some functionality provided in the SCIRun4 module "ClipVolumeByIsovalue".
Dan and me looked at the code of ClipVolumeByIsovalue and it seems that one major problem to
port it was code included from the MarchingCube implementation (used in the context of  TriSurf/QuadSurf).

**Comment by dcwhite** [comment]
Conversion notes
- [ ] GUI very simple; just add a radio button to the ExtractSimpleIsosurface UI
- [ ] Module code is pretty straightforward
- [ ] Algo code uses several hash maps (Algorithms\Fields\ClipMesh\ClipMeshByIsovalue.cc), yucky platform macros there. I can convert that next week if you want.

**Comment by moritzdannhauer** [comment]
Ok thanks, I gonna need to rewrite the parts that use "SparseRowMatrix".

**Comment by moritzdannhauer** [comment]
Do you want me to deal with them in a certain way?

**Comment by dcwhite** [comment]
Check out changes made to BaseMC.h:
https://github.com/SCIInstitute/SCIRun/commit/24e26c584826b5ed8f465e94aa37a3dbca1a9e75#diff-eea8304db94ad8931e628332ace86364

**Comment by dcwhite** [comment]
Do you need the "interpolant mapping matrix"? If not you can macro out that section and we can push the SparseBuilder code conversion to later.
