### ISSUE TITLE
Move Forward/Inverse toolkit to new repo

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#925]
Move Forward/Inverse toolkit networks and documentation to a new repo similar to BrainStimulator.

**Comment by aylakhan** [comment]
Added networks and documentation to Forward/Inverse toolkit to new repo and. BrainStimulator also contains  data. We should add data to the repo, but some of the regression networks also use the fwd/inverse data in SCIRunTestData. Should we duplication? We could use something like git subtrees to avoid copying files manually...

**Comment by dcwhite** [comment]
Not sure where the best place to house data since we can't replicate SCIRunData in github just yet, since it's too big. I'm fine with duplicating small data for test networks; whatever works for making it easy to run the regression tests.
