### ISSUE TITLE
WriteField Data I/O module produces unreadable .mat files

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/SCIRun#931]
The WriteField Module in SCIRun 4 also has a .mat writing problem. The reason that the files cannot be read is:

"Matrix 'tetmesh' cannot be translated into a SCIRun Field (one of the dimensions of fieldedge needs to be of size 4)"

There is no fieldedge in the file structure of the written .mat files...but there also isn't any such field in the Cleaver .mat outputs that are readable.

The file structure of the unreadble, SCIRun-written .mat files is:
scirunfield.fieldbasis
scirunfield.fieldbasisorder
scirunfield.fieldtype
scirunfield.field
scirunfield.fieldcell
scirunfield.meshbasis
scirunfield.meshbasisorder
scirunfield.meshtype
scirunfield.node
scirunfield.cell
scirunfield.property

The file structure of the readble, Cleaver-written .mat files is:
tetmesh.node
tetmesh.cell
tetmesh.field
tetmesh.fieldat

**Comment by aylakhan** [comment]
@zaracay - can you start digging into the matlab file code and see where the mapping between TetMesh and the Matlab field type is failing?

**Comment by zaracay** [comment]
I just tested all of the SCIRun 4.x versions.  None of them have a working copy.  Also, this only seems to be a problem with the tetmesh type.  

Another interesting discovery was that tetmesh files that I read into matlab and then saved out as .mat files were equally unreadable.  I even read in a .mat file from Cleaver and saved it out.  The original file was readable, the file saved out of matlab was not.  I'm not sure what that's all about, but I'm digging into it now.

**Comment by dcwhite** [comment]
Any updates on this issue?

**Comment by dcwhite** [comment]
Assigning back to me since I need to fix these in order for #1300 to be doable.

**Comment by dcwhite** [comment]
The error message from the code is wrong (copy/paste error). It should say `fieldcell` instead of `fieldedge`. So the cell matrix is the wrong dimension.

**Comment by dcwhite** [comment]
I was able to fix this by deleting some verification code that wasn't needed anymore, since the "fieldcell" data was not used in field construction. Now cell-data tetvols load fine from matlab format.
