### ISSUE TITLE
Running SCIRun from cmd.exe in Windows ignores command line arguments

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#945]
Arguments work in a bash shell on Windows, but not cmd.exe-based shells. Not sure how many users this would affect. Probably due to the Winmain change.

**Comment by aylakhan** [comment]
It would be nice to have command line options in cmd.exe. Could impact usability of headless version.

**Comment by dcwhite** [comment]
This was actually a bug with parsing the string from GetCommandLine().
