### ISSUE TITLE
Copy IBBM SCIRun networks to Exchange and start v5 versions here

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#946]
- [x] Copy v4 networks to Exchange
- [x] Manually convert to v5 and put in ExampleNets directory

**Comment by dcwhite** [comment]
@jessdtate Where are the networks listed in #918?

**Comment by jessdtate** [comment]
they are all in the /usr/sci/projects/IBBM/ directory.

**Comment by dcwhite** [comment]
ok thanks

**Comment by dcwhite** [comment]
Is there a public link to the data I can include? It's too big for github.

**Comment by dcwhite** [comment]
All networks mentioned in #918 added with https://github.com/SCIInstitute/SCIRun-Exchange/commit/ac5f7d73bd28f2616c42ebec85dfb8024da900af

**Comment by jessdtate** [comment]
I'm not sure what to do with the data.  I think they are planning to use a flash drive to distribute the data again.

**Comment by dcwhite** [comment]
ok

**Comment by aylakhan** [comment]
A readme file explaining where to find the data would be good.

**Comment by dcwhite** [comment]
Should it say, "Ask Jess for a USB drive?" Or I could just point to http://www.sci.utah.edu/download/scirun/ but that's somewhat confusing

**Comment by aylakhan** [comment]
How about data for IBBM participants will be provided during the course. Others can download from etc. @jesstate will there be a download link on the SCI website?

**Comment by jessdtate** [comment]
I don't know.  this is something that will probably need to go through the higher ups.  I would like it to be somewhere.  Most of the data are in the distributed example data repos (SCIRunData, etc) some of it isn't.  I can go through the networks and note where to get the data for each.  If the specific data is unavailable, I can describe it.

**Comment by lizutah** [comment]
We can worry about the final location of the data later.  For now, as long as it's some place we can access it on the sci file server, that will be fine.  We can move it to a more public place later.  Maybe we can just make sure that each network contains a readme that points to the data location?

**Comment by dcwhite** [comment]
@jessdtate Can I assign you that task? I'll make an issue

**Comment by jessdtate** [comment]
sure.
=

**Comment by dcwhite** [comment]
@jessdtate I needed https://github.com/SCIInstitute/SCIRun/blob/master/src/ExampleNets/IBBM2015/Registration_Network.srn5 to test RWC module. You can start adding the rest of the networks into that folder.
