### ISSUE TITLE
SolveInverseProblemWithTikhonov regularization matrices seem not to do anything

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#956]
While testing the SolveInverseProblemWithTikhonov, its output seems not to change when I am inputing a regularization matrix in either the solution or measurement constraing input

**Comment by dcwhite** [comment]
:+1:

**Comment by dcwhite** [comment]
@jcollfont I believe those ports are not hooked up yet at all. Some test networks would be helpful--the toolkit network does not have any inputs attached.

**Comment by dcwhite** [comment]
The ports are indeed hooked up and the values are passed into the algorithm code. See lines 230-280 of https://github.com/SCIInstitute/SCIRun/blob/master/src/Modules/Legacy/Inverse/SolveInverseProblemWithTikhonovImpl.cc. If you send me some test networks with data that show the expected results when these ports are used (no existing networks use them), I can have something to debug.

**Comment by dcwhite** [comment]
Any updates on this issue? Do the latest test cases exercise the additional ports? If so, please add comments to that PR referencing this issue.

**Comment by jcollfont** [comment]
The module is currently accepting regularization matrices for both source and measurement.

In both cases the matrices are being checked that they have the appropriate size and the errors are being thrown.
The tests for these issues are implemented.
