### ISSUE TITLE
load saved networks and inputs in viewScene / outputs of ShowField

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#957]
When saving a network with visualization of some fields, the pipes going out of ShowField feeding into viewScene sometimes do not work. 
To fix that one needs to eliminate the pipes and create them again. Then everything is fine.

**Comment by dcwhite** [comment]
@jcollfont Another one that's been seen before but is hard to replicate. If you figure out a consistent way to show this one, attach steps here.

**Comment by dcwhite** [comment]
@ajanson has reported this as well.

**Comment by dcwhite** [comment]
I finally saw this one in @jessdtate's network for recently-fixed bug #1416. Had to delete/reconnect for VS to work.

**Comment by dcwhite** [comment]
@jessdtate IBBM

**Comment by dcwhite** [comment]
@jessdtate Have you seen this one (much) recently?

**Comment by jessdtate** [comment]
I haven't seen it lately, but I don't think it has gone away.  It seems to have something to do with turning off the object in the VS configure menu.

**Comment by nids2001** [comment]
Missing geometry in ViewScene:
[defib_tutorial_ch3.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/3769524/defib_tutorial_ch3.srn5.zip)

Same network, but working:
[defib_tutorial_ch_3_2.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/3769581/defib_tutorial_ch_3_2.srn5.zip)

**Comment by dcwhite** [comment]
Thanks to @nids2001 for the "before/after" networks, I was able to figure this out and actually fix it!

**Comment by Sumientra** [comment]
I just had this happen and came to search for an issue. Glad to see Dan fixed it :) Is there a new installer for this?

**Comment by dcwhite** [comment]
Not yet, it’s still on a branch. Soon though
