### ISSUE TITLE
SolveInverseProblemWithTikhonov lambda selection limitations

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#958]
The slider in the lambda selection options only allows to select integers.

In the boxes to select bounds of the lambda search, there is a limited number of digits in the box and does not allow to add more. One needs to delete o's at the right hand side to add new stuff.
For example, the module opens with:
0.000100000
then, in order to write 0.00001 (one more zero before the one), one needs to delete a zero in the right hand side to make room for the new digit:
0.000010000

**Comment by dcwhite** [comment]
Qt's floating point widgets definitely need some work. We can leverage Seg3D's custom widgets for this.

**Comment by dcwhite** [comment]
Tried switching to SCIRun's "DoubleLineEdit" and these are not performing very well. I'll look at Seg3D code next milestone for this.
