### ISSUE TITLE
delete pipes

### ISSUE THREAD

**Issue by jcollfont** [SCIInstitute/SCIRun#959]
SCIRun won't let me select and delete a given pipe that connects two modules.
Tried selecting and pushing "delete" and didn't work. 
To be able to do so I had to restart SCIRun (reloading the network didn't work).   

It happened once and couldn't reproduce it so far...

**Comment by dcwhite** [comment]
@jcollfont Were there other pipes occluding said pipe in the network editor? Or was it a single isolated pipe? Let me know if you can reproduce consistently.

**Comment by jcollfont** [comment]
It does select the pipes, and I am capable of erasing them through the menu that opens with the second left click.

I cannot use the delete button from the keyboard.

It has happened twice, but Couldn't think of any consistent pattern that led to it. It happened after some time using SCIRun

**Comment by dcwhite** [comment]
@jessdtate This is the sort of stale issue that should just be closed.

**Comment by jessdtate** [comment]
yeah
