### ISSUE TITLE
Rotation on Trackpad

### ISSUE THREAD

**Issue by allywarner** [SCIInstitute/SCIRun#962]
I was unable to figure out how to rotate a scene using a trackpad in either legacy or new mouse mode settings. I tried left-click, right-click and button combinations with left and right-click and I could only translate and zoom.

**Comment by aylakhan** [comment]
Mouse and key combinations should be documented and shown in UI.

**Comment by dcwhite** [comment]
@cbrightsci Add a "Keyboard shortcuts" menu/button to the toolbar. Have it reflect the user's mouse config choice.

**Comment by jessdtate** [comment]
This is a bug having to do with the very first time SCIRun is opened.  The default is to use the new controls, and though the menu says it is the new controls, the controls are legacy.  if you change them to legacy and back (or reload SCIRun I assume) it will work.

**Comment by dcwhite** [comment]
@cbrightsci I added a shortcut widget to help with this; can you fix the checkbox to be the correct default?

**Comment by cbrightsci** [comment]
The issue was that it wasn't setting the default mouse to new configuration until you opened the config menu on viewscene. I changed it in preferences.cc to default to the new mouse.

**Comment by jessdtate** [comment]
I tried to test it, and I think it is working, but I'm not sure I had a pristine build

**Comment by moritzdannhauer** [comment]
I used it a little bit in the lunch and I really like it !!!
