### ISSUE TITLE
ShowField: detect properties of field

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#983]
When loading a point cloud in SCIRun (only node data, no edges or faces), ShowField currently defaults to show faces and edges. It would be good if ShowField defaulted to show nodes for files that only contain nodes

**Comment by dcwhite** [comment]
v4 does this. In fact if a field has no faces at all, for instance, you can't even check the "Show Faces" checkbox--clicking it does nothing.
