### ISSUE TITLE
ShowFieldGlyphs not working with constant basis vectors on TriSurf

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#984]
Tested on OS X. Glyphs from trisurf field with vectors in cells are not showing up in ViewScene [Test network](https://www.dropbox.com/s/rbx6ey9us0kk5pj/test_fieldglyphs_trisurf.srn5?dl=0).

**Comment by aylakhan** [comment]
Looks like a basis problem - adding ShowFieldGlyphs to the CalculateVectorMagnitudes network shows that vectors on nodes works.

**Comment by cbrightsci** [comment]
@aylakhan can you point me an example network for this so I can test out a possible fix?
