### ISSUE TITLE
mapfielddatanodes/elements

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#989]
need to have the option for applying nan for background value, similar to MapFieldDataFromSourceToDestination.

**Comment by dcwhite** [comment]
This sounds like one @jessdtate can implement himself now...

**Comment by jessdtate** [comment]
OK.  I can do that.  I will just ask @dcwhite if I get stuck anyway.

**Comment by dcwhite** [comment]
You mean this @dcwhite?
