### ISSUE TITLE
modules  that need the stop feature.  

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#990]
This is a list of modules that can often take a long time to execute and would be nice to have a stop feature.  I don't if it is possible to implement in all of them.

 - [x] GetFieldBoundary
 - [x] GetDomainBoundary
 - [ ] SolveLinearSystem
 - [x] ShowFieldGlyphs
 - [x] MapFieldDataOntoNodes/Elements
 - [x] MapFieldDataFromSourceToDestination
 - [x] CalculateSignedDistanceToField
 - [ ] InterfaceWithTegen
 - [ ] InterfaceWithCleaver

In theory, every module can take a long time to complete and require stopping if the data is big enough, but these are the ones that take more resources and time.

**Comment by dcwhite** [comment]
SLS, IWT, IWC all will require more careful interruption-point-planning so will come later.
